# **ResNet50 — EXP02 CBAM (Convolutional Block Attention Module)**

Versi CBAM dari `exp01-cnn-baseline.ipynb` (ResNet50 Baseline). Mengikuti prinsip isolasi yang sama seperti versi ECA: **SEMUA hyperparameter identik dengan baseline**, satu-satunya perubahan adalah penyisipan modul CBAM -- supaya efek CBAM terhadap performa bisa diatribusikan murni ke modul attention-nya, bukan ke confound lain.

**Perbedaan CBAM vs ECA:**
- ECA cuma channel attention (1D conv atas hasil avg-pool per channel).
- CBAM (Woo et al., 2018) punya **dua submodul sequential**: (1) *Channel Attention* -- shared MLP atas avg-pool DAN max-pool per channel, digabung lalu di-sigmoid; (2) *Spatial Attention* -- avg-pool & max-pool sepanjang axis channel, digabung jadi 2 channel, lalu conv 7x7 + sigmoid. Channel attention diterapkan dulu, baru spatial attention terhadap hasilnya (`x' = Mc(x) ⊗ x`, lalu `x'' = Ms(x') ⊗ x'`).

**Titik insersi CBAM (sama seperti ECA):**
- ResNet punya banyak feature map 4D di sepanjang backbone -- CBAM disisipkan di slot `.se` yang memang disediakan timm di setiap **Bottleneck block** (persis setelah `conv3`+`bn3`, sebelum residual add), sesuai desain CBAM asli yang memasang di seluruh backbone CNN, bukan cuma 1 titik.

## 1. Import & Setup

In [1]:
# 1. Install & Import
import os, copy, random
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
# PERBAIKAN (dari ViT exp01): AMP -- sebagian besar operasi forward jalan di
# float16 (lebih cepat & hemat VRAM di GPU RTX/Tensor Core), backward/update tetap
# presisi lewat GradScaler. Belum ada di kedua notebook ResNet sebelumnya.
from torch.cuda.amp import autocast, GradScaler

from torchvision import transforms, datasets
from PIL import Image
from tqdm import tqdm

import timm   # PERBAIKAN: torchvision.models -> timm, biar 1 API dipakai semua arsitektur (ResNet18/50, EfficientNet, ViT, dst)
import wandb

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, recall_score,
    classification_report, confusion_matrix, ConfusionMatrixDisplay
)

# Ambil API key dari environment variable
wandb_api_key = os.getenv("WANDB_API_KEY")

os.environ["TORCH_HOME"] = "D:/cache/torch"
os.environ["HF_HOME"] = "D:/cache/huggingface"

os.environ["WANDB_DIR"] = "D:/cache/wandb"
os.environ["WANDB_CACHE_DIR"] = "D:/cache/wandb_cache"

os.environ["TEMP"] = "D:/cache/temp"
os.environ["TMP"] = "D:/cache/temp"

os.environ["CUDA_CACHE_PATH"] = "D:/cache/cuda"

print(os.getcwd())

# Login ke wandb
wandb.login(key=wandb_api_key)

# PERBAIKAN (dari ViT exp01 + ResNet18): seed eksplisit -- EXP01-03 ResNet50 lama
# cuma nge-seed StratifiedKFold, TIDAK nge-seed init bobot FC head / urutan shuffle.
SEED = 42
random.seed(SEED); np.random.seed(SEED)
torch.manual_seed(SEED); torch.cuda.manual_seed_all(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# PERBAIKAN (dari ViT exp01): cudnn.benchmark auto-tune algoritma konvolusi
# tercepat untuk ukuran input yang konsisten (semua di-resize ke 224x224).
torch.backends.cudnn.benchmark = True

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from C:\Users\UNIDA\_netrc.

d:\Devianest_SkripsiTest\Code_CNN

wandb: Currently logged in as: devianestnarendra to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

Device: cuda

## 2. Config

In [2]:
TRAIN_DIR = r"D:\Devianest_SkripsiTest\train"
TEST_DIR  = r"D:\Devianest_SkripsiTest\test"

# PERBAIKAN (VSCode lokal): ganti "/kaggle/working" -> folder "outputs" relatif
# terhadap lokasi notebook ini. os.makedirs(..., exist_ok=True) otomatis bikin
# foldernya kalau belum ada, supaya tidak error "No such file or directory"
# saat pertama kali disimpan.
OUTPUT_DIR = "outputs"
os.makedirs(OUTPUT_DIR, exist_ok=True)

ARCH_KEY  = "EXP04_ResNet50_CBAM"
TIMM_NAME = "resnet50"

IMG_SIZE     = 224
BATCH_SIZE   = 32          # tetap seperti EXP01-03 (ResNet50 lebih berat dari ResNet18, batch lebih kecil)
EPOCHS       = 50
N_FOLDS      = 5
DROPOUT      = 0.3         # dipertahankan dari EXP01-03 (nilai yang sudah teruji utk ResNet50)
LR           = 1e-4        # PERBAIKAN: dipertahankan nilai ResNet (BUKAN LR ViT 3e-5) -- CNN historically
                            # lebih toleran ke LR sedikit lebih tinggi dibanding attention layer ViT yang sensitif
WEIGHT_DECAY = 1e-4         # dipertahankan nilai konvensi CNN transfer learning (bukan WD ViT 0.01)
LABEL_SMOOTHING = 0.1
EARLY_STOP_PATIENCE = 7     # PERBAIKAN: naik dari 5 -> 7 (lebih toleran sebelum berhenti)

WANDB_PROJECT = "SkinDisease-CNN"   # disamakan dengan notebook ResNet18, biar 1 project W&B

# ResNet50: unfreeze layer2/3/4 + fc -- sama scope kapasitas dengan EXP03 (untuk
# tetap bisa dibandingkan), TAPI training regime-nya sudah diperbaiki (lihat bawah).
UNFREEZE_PATTERNS = ["layer2", "layer3", "layer4", "fc"]

# PERBAIKAN (dari ViT exp01 + ResNet18): scheduler ReduceLROnPlateau disamakan
# PERSIS dengan setting yang sudah dipakai di ViT & ResNet18 -- root cause
# instabilitas ResNet50 lama adalah OneCycleLR yang di-set untuk siklus 50 epoch
# penuh, tapi EarlyStopping hampir selalu memotong training di epoch 11-22
# (SEBELUM fase anneal selesai) -- lihat diskusi sebelumnya soal Fold 4 yang
# selalu menang karena satu-satunya fold yang tidak pernah early-stop.
SCHEDULER_FACTOR    = 0.1
SCHEDULER_PATIENCE  = 2
SCHEDULER_THRESHOLD = 1e-4
SCHEDULER_MIN_LR    = 1e-7


# ── CBAM (Convolutional Block Attention Module) ──────────────────────────────
# PERBAIKAN: versi CBAM dari EXP01 -- SEMUA hyperparameter di atas dipertahankan
# PERSIS SAMA (LR, WEIGHT_DECAY, DROPOUT, UNFREEZE_PATTERNS, scheduler, dst) supaya
# efek CBAM terisolasi (tidak ada confound lain), sama seperti prinsip versi ECA.
USE_CBAM               = True
CBAM_REDUCTION_RATIO   = 16   # rasio reduksi shared MLP channel attention, default paper CBAM (Woo et al., 2018)
CBAM_SPATIAL_KERNEL_SIZE = 7  # ukuran kernel conv2d spatial attention, default paper CBAM

## 3. Dataset & Augmentasi

In [3]:
# PERBAIKAN: augmentasi disamakan PERSIS dengan versi terbaru ViT exp01 (medium,
# termasuk RandomResizedCrop) -- bukan versi ResNet18 yang belum pakai
# RandomResizedCrop. Ini penting supaya CNN dan ViT dibandingkan dengan
# preprocessing yang identik (bukan confound tambahan).
def get_transforms(img_size):
    train_tf = transforms.Compose([
        transforms.Resize((img_size, img_size)),
        transforms.RandomHorizontalFlip(),
        transforms.RandomRotation(10),
        transforms.ColorJitter(brightness=0.15, contrast=0.15, saturation=0.1),
        transforms.RandomResizedCrop(img_size, scale=(0.8, 1.0)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ])
    eval_tf = transforms.Compose([
        transforms.Resize((img_size, img_size)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ])
    return train_tf, eval_tf


classes = sorted(os.listdir(TRAIN_DIR))
class_to_idx = {c: i for i, c in enumerate(classes)}
num_classes = len(classes)

filepaths, labels = [], []
for label in classes:
    class_path = os.path.join(TRAIN_DIR, label)
    for img in os.listdir(class_path):
        filepaths.append(os.path.join(class_path, img))
        labels.append(class_to_idx[label])

print("Total Images :", len(filepaths))
print("Classes      :", num_classes)


class SkinDataset(Dataset):
    def __init__(self, filepaths, labels, transform=None):
        self.filepaths = filepaths
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return len(self.filepaths)

    def __getitem__(self, idx):
        image = Image.open(self.filepaths[idx]).convert("RGB")
        label = self.labels[idx]
        if self.transform:
            image = self.transform(image)
        return image, label

Total Images : 15557
Classes      : 23

## 4. Early Stopping (val_f1) + K-Fold

In [4]:
class EarlyStopping:
    # Kriteria val_f1 (bukan val_loss) -- konsisten dengan ViT exp01 & ResNet18:
    # lebih robust untuk data imbalanced (23 kelas DermNet) dibanding val_loss.
    def __init__(self, patience=5):
        self.patience = patience
        self.best_f1 = -np.inf
        self.counter = 0

    def step(self, val_f1):
        if val_f1 > self.best_f1:
            self.best_f1 = val_f1
            self.counter = 0
            return False
        self.counter += 1
        return self.counter >= self.patience


skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)

## 5. Model Builder + Freeze Strategy

In [5]:
# ── CBAM (Convolutional Block Attention Module) ──────────────────────────────
# Sama seperti versi ECA, titik insersinya identik karena arsitekturnya sama:
# - ResNet (CNN) punya feature map 4D (B, C, H, W) di SEPANJANG backbone -- setiap
#   Bottleneck block. timm sudah menyediakan slot khusus untuk ini: atribut
#   `.se` di tiap Bottleneck (dipakai bawaan buat SE-Net-style attention),
#   dipanggil PERSIS setelah conv3+bn3, SEBELUM residual add:
#       x = self.conv3(x); x = self.bn3(x)
#       if self.se is not None: x = self.se(x)
#       ...; x += shortcut; x = self.act3(x)
#   Bedanya dengan ECA: CBAM adalah 2 submodul SEQUENTIAL -- channel attention
#   dulu (Mc), baru spatial attention (Ms) terhadap hasil channel attention.
class ChannelAttention(nn.Module):
    # Channel attention CBAM: shared MLP (bottleneck 1x1 conv) diterapkan ke
    # HASIL avg-pool DAN max-pool secara terpisah, lalu dijumlahkan -- beda
    # dengan SE-Net/ECA yang cuma pakai avg-pool saja. Menambahkan max-pool
    # menangkap sinyal channel yang "menonjol", bukan cuma rata-rata.
    def __init__(self, channels, reduction_ratio=16):
        super().__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.max_pool = nn.AdaptiveMaxPool2d(1)
        hidden = max(channels // reduction_ratio, 1)
        self.mlp = nn.Sequential(
            nn.Conv2d(channels, hidden, kernel_size=1, bias=False),
            nn.ReLU(inplace=True),
            nn.Conv2d(hidden, channels, kernel_size=1, bias=False),
        )
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        # x: (B, C, H, W)
        avg_out = self.mlp(self.avg_pool(x))
        max_out = self.mlp(self.max_pool(x))
        y = self.sigmoid(avg_out + max_out)
        return x * y


class SpatialAttention(nn.Module):
    # Spatial attention CBAM: pool sepanjang axis CHANNEL (bukan spatial) --
    # avg & max per posisi (h, w) di-concat jadi 2-channel map, lalu conv 7x7
    # (kernel besar supaya konteks spasial lebih luas) + sigmoid.
    def __init__(self, kernel_size=7):
        super().__init__()
        self.conv = nn.Conv2d(2, 1, kernel_size=kernel_size, padding=(kernel_size - 1) // 2, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        # x: (B, C, H, W) -- sudah hasil channel attention
        avg_out = torch.mean(x, dim=1, keepdim=True)
        max_out, _ = torch.max(x, dim=1, keepdim=True)
        y = torch.cat([avg_out, max_out], dim=1)   # (B, 2, H, W)
        y = self.conv(y)
        y = self.sigmoid(y)
        return x * y


class CBAMAttention(nn.Module):
    # Gabungan sequential: channel attention dulu, baru spatial attention
    # terhadap hasilnya -- sesuai urutan channel-first yang terbukti lebih
    # baik di paper CBAM asli (Woo et al., 2018) dibanding urutan sebaliknya.
    def __init__(self, channels, reduction_ratio=16, spatial_kernel_size=7):
        super().__init__()
        self.channel_attention = ChannelAttention(channels, reduction_ratio)
        self.spatial_attention = SpatialAttention(spatial_kernel_size)

    def forward(self, x):
        x = self.channel_attention(x)
        x = self.spatial_attention(x)
        return x


def inject_cbam(model, reduction_ratio=16, spatial_kernel_size=7):
    # PERBAIKAN: CBAM disisipkan ke SEMUA Bottleneck block (layer1-4), bukan cuma
    # layer yang di-unfreeze -- sesuai desain CBAM asli yang memasang attention
    # di seluruh backbone. Scope freeze/unfreeze BACKBONE tetap diatur terpisah
    # lewat apply_freeze_strategy (lihat PERBAIKAN di bawah: modul CBAM sendiri
    # selalu trainable, terlepas dari block induknya beku atau tidak).
    n_injected = 0
    for layer_name in ["layer1", "layer2", "layer3", "layer4"]:
        layer = getattr(model, layer_name, None)
        if layer is None:
            continue
        for block in layer:
            channels = block.bn3.num_features
            block.se = CBAMAttention(channels, reduction_ratio=reduction_ratio, spatial_kernel_size=spatial_kernel_size)
            n_injected += 1
    print(f"  [CBAM] Disisipkan ke {n_injected} Bottleneck block (layer1-4).")
    return model

In [6]:
def build_model(num_classes, dropout=DROPOUT):
    # PERBAIKAN: head sederhana bawaan timm (Linear + drop_rate), BUKAN custom
    # Linear->BN->ReLU->Dropout->Linear seperti EXP01-03 lama. Diselaraskan dengan
    # ViT exp01 & ResNet18 -- supaya kapasitas head TIDAK jadi confound tambahan
    # saat membandingkan arsitektur (kalau satu arsitektur dikasih head lebih besar
    # dari yang lain, selisih performa bisa jadi cuma soal head, bukan backbone).
    model = timm.create_model(
        TIMM_NAME, pretrained=True, num_classes=num_classes, drop_rate=dropout
    )
    # PERBAIKAN (CBAM): sisipkan CBAM ke tiap Bottleneck SETELAH model pretrained
    # dibuat -- supaya bobot pretrained conv1/2/3/bn tidak tersentuh, cuma nambah
    # modul baru di slot `.se` yang random-init.
    if USE_CBAM:
        model = inject_cbam(model, reduction_ratio=CBAM_REDUCTION_RATIO, spatial_kernel_size=CBAM_SPATIAL_KERNEL_SIZE)
    return model


def apply_freeze_strategy(model, patterns=UNFREEZE_PATTERNS):
    for p in model.parameters():
        p.requires_grad = False
    for name, p in model.named_parameters():
        if any(pat in name for pat in patterns):
            p.requires_grad = True

    # PERBAIKAN (CBAM): modul CBAM SELALU trainable, terlepas dari UNFREEZE_PATTERNS
    # -- konsisten dengan versi ECA (attention submodule selalu unfrozen).
    # Bobotnya random-init (bukan pretrained), jadi kalau block induknya kebetulan
    # di luar scope unfreeze (mis. layer1), CBAM di block itu tidak boleh ikut beku,
    # kalau tidak dia jadi dead weight (random & tidak pernah di-update).
    if USE_CBAM:
        for module in model.modules():
            if isinstance(module, CBAMAttention):
                for p in module.parameters():
                    p.requires_grad = True

    n_trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    n_total = sum(p.numel() for p in model.parameters())
    print(f"  [{ARCH_KEY}] Trainable params: {n_trainable:,} / {n_total:,} ({100*n_trainable/n_total:.1f}%)")
    return model

## 6. Train 1 Fold

In [7]:
def train_one_fold(fold, train_idx, val_idx, run):
    train_tf, eval_tf = get_transforms(IMG_SIZE)

    train_files  = [filepaths[i] for i in train_idx]
    train_labels = [labels[i] for i in train_idx]
    val_files    = [filepaths[i] for i in val_idx]
    val_labels   = [labels[i] for i in val_idx]

    # PERBAIKAN (dari ViT exp01): pin_memory=True -- percepat transfer CPU->GPU.
    # num_workers=2 dari ResNet18 (lebih cepat load data daripada 0 di EXP03 lama).
    train_loader = DataLoader(
        SkinDataset(train_files, train_labels, train_tf),
        batch_size=BATCH_SIZE, shuffle=True, num_workers=0, pin_memory=True
    )
    val_loader = DataLoader(
        SkinDataset(val_files, val_labels, eval_tf),
        batch_size=BATCH_SIZE, shuffle=False, num_workers=0, pin_memory=True
    )

    # PERBAIKAN: reseed per fold -- inisialisasi FC head & urutan shuffle
    # reproducible, tidak tergantung urutan eksekusi fold sebelumnya.
    random.seed(SEED + fold); np.random.seed(SEED + fold)
    torch.manual_seed(SEED + fold); torch.cuda.manual_seed_all(SEED + fold)

    model = build_model(num_classes)
    model = apply_freeze_strategy(model)
    model = model.to(device)

    # PERBAIKAN (dari ViT exp01): class_weights dinormalisasi supaya rata-rata = 1.
    # EXP01-03 & ResNet18 sebelumnya cuma 1./bincount TANPA normalisasi --
    # magnitude weight antar kelas timpang, jadi salah satu sumber loss yang
    # "melompat" tergantung komposisi kelas tiap batch.
    class_counts  = np.bincount(train_labels, minlength=num_classes)
    class_weights = 1. / torch.tensor(class_counts, dtype=torch.float)
    class_weights = class_weights / class_weights.sum() * num_classes

    criterion = nn.CrossEntropyLoss(
        weight=class_weights.to(device), label_smoothing=LABEL_SMOOTHING
    )
    optimizer = optim.AdamW(
        filter(lambda p: p.requires_grad, model.parameters()),
        lr=LR, weight_decay=WEIGHT_DECAY
    )
    # PERBAIKAN: scheduler disamakan persis dengan ViT exp01 & ResNet18 -- root
    # cause instabilitas ResNet50 lama (OneCycleLR + EarlyStopping yang memotong
    # sebelum siklus selesai) sudah tidak ada lagi di sini.
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode="max", factor=SCHEDULER_FACTOR, patience=SCHEDULER_PATIENCE,
        threshold=SCHEDULER_THRESHOLD, min_lr=SCHEDULER_MIN_LR
    )

    # PERBAIKAN (dari ViT exp01): AMP -- autocast di forward pass, GradScaler
    # untuk backward/update supaya gradient float16 tidak underflow.
    scaler = GradScaler()

    early_stopping = EarlyStopping(patience=EARLY_STOP_PATIENCE)
    best_val_f1 = -np.inf
    # PERBAIKAN: tracking accuracy/precision/recall di titik checkpoint terbaik juga
    # (sebelumnya cuma f1) -- supaya format output/summary sama seperti ViT exp01,
    # yang melaporkan keempat metrik (bukan cuma F1) di rekap akhir.
    best_val_acc = -np.inf
    best_val_precision = -np.inf
    best_val_recall = -np.inf
    best_val_loss = np.inf
    best_train_loss = np.inf
    best_model_path = None
    train_losses, val_losses = [], []

    for epoch in range(EPOCHS):
        print(f"\n[{ARCH_KEY} | fold {fold+1}] Epoch {epoch+1}/{EPOCHS} (LR: {optimizer.param_groups[0]['lr']:.2e})")

        # TRAIN
        model.train()
        train_loss = 0
        for imgs, tgts in tqdm(train_loader, desc="Train"):
            imgs, tgts = imgs.to(device), tgts.to(device)
            optimizer.zero_grad()
            with autocast():
                loss = criterion(model(imgs), tgts)
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
            train_loss += loss.item()

        # VALIDATION
        model.eval()
        val_loss = 0
        preds, trues = [], []
        with torch.no_grad():
            for imgs, tgts in tqdm(val_loader, desc="Val"):
                imgs, tgts = imgs.to(device), tgts.to(device)
                with autocast():
                    outputs = model(imgs)
                    v_loss  = criterion(outputs, tgts)
                val_loss += v_loss.item()
                preds.extend(outputs.argmax(1).cpu().numpy())
                trues.extend(tgts.cpu().numpy())

        avg_train_loss = train_loss / len(train_loader)
        avg_val_loss   = val_loss / len(val_loader)

        acc       = accuracy_score(trues, preds)
        precision = precision_score(trues, preds, average="weighted", zero_division=0)
        recall    = recall_score(trues, preds, average="weighted", zero_division=0)
        f1        = f1_score(trues, preds, average="weighted", zero_division=0)

        scheduler.step(f1)

        train_losses.append(avg_train_loss)
        val_losses.append(avg_val_loss)

        print(f"Train Loss : {avg_train_loss:.4f} | Val Loss  : {avg_val_loss:.4f}")
        print(f"Accuracy   : {acc:.4f}  | Precision : {precision:.4f}")
        print(f"Recall     : {recall:.4f}  | F1 Score  : {f1:.4f}")

        run.log({
            "epoch": epoch + 1,
            f"fold_{fold+1}/train_loss": avg_train_loss,
            f"fold_{fold+1}/val_loss": avg_val_loss,
            f"fold_{fold+1}/accuracy": acc,
            f"fold_{fold+1}/precision": precision,
            f"fold_{fold+1}/recall": recall,
            f"fold_{fold+1}/f1_score": f1,
            f"fold_{fold+1}/lr": optimizer.param_groups[0]["lr"],
        })

        # SAVE BEST MODEL -- kriteria val_f1 tertinggi (bukan val_loss terendah)
        if f1 > best_val_f1:
            best_val_f1 = f1
            best_val_acc = acc
            best_val_precision = precision
            best_val_recall = recall
            best_val_loss = avg_val_loss
            best_train_loss = avg_train_loss

            save_path = f"{OUTPUT_DIR}/{ARCH_KEY}_fold{fold+1}.pth"
            torch.save({
                "model_state_dict": model.state_dict(),
                "val_loss": avg_val_loss,
                "f1": f1,
                "fold": fold + 1,
                "arch": ARCH_KEY,
            }, save_path)
            best_model_path = save_path
            print(f"  ✓ Model saved → {save_path} (F1: {f1:.4f})")

        if early_stopping.step(f1):
            print("Early Stopping Triggered")
            break

    # ── PLOT LOSS CURVE PER FOLD ──────────────────────────────────────────────
    epochs_ran = range(1, len(train_losses) + 1)
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(epochs_ran, train_losses, label="Train Loss", marker="o", markersize=3)
    ax.plot(epochs_ran, val_losses, label="Val Loss", marker="o", markersize=3)
    ax.set_title(f"{ARCH_KEY} — Fold {fold+1} Loss Curve")
    ax.set_xlabel("Epoch"); ax.set_ylabel("Loss")
    ax.legend(); ax.grid(True, alpha=0.3)
    curve_path = f"{OUTPUT_DIR}/{ARCH_KEY}_Fold_{fold+1}_Loss_Curve.png"
    fig.savefig(curve_path, dpi=150, bbox_inches="tight")
    run.log({f"Loss_Curve/Fold_{fold+1}": wandb.Image(curve_path)})
    plt.close(fig)

    return {
        "arch": ARCH_KEY,
        "fold": fold + 1,
        "train_loss": best_train_loss,
        "val_loss": best_val_loss,
        # PERBAIKAN: sertakan accuracy/precision/recall (bukan cuma f1), supaya
        # results_df punya kolom yang sama seperti fold_accuracies/fold_precision/
        # fold_recall/fold_f1 di ViT exp01.
        "accuracy": best_val_acc,
        "precision": best_val_precision,
        "recall": best_val_recall,
        "f1": best_val_f1,
        "model_path": best_model_path,
    }

## 7. MAIN LOOP — 5 Fold (ResNet50)

Kalau waktu habis di tengah jalan: checkpoint tiap fold udah ke-save duluan (di `all_results`), aman buat dilanjut manual per-fold.

In [8]:
all_results = []

run = wandb.init(
    project="SkinDisease-CNN",
    entity="devianestnarendra_Team",
    name=f"{ARCH_KEY}",
    reinit=True,
    config={
        "architecture": ARCH_KEY,
        "n_folds": N_FOLDS,
        "epochs": EPOCHS,
        "batch_size": BATCH_SIZE,
        "img_size": IMG_SIZE,
        "optimizer": "AdamW",
        "scheduler": f"ReduceLROnPlateau(mode=max, factor={SCHEDULER_FACTOR}, patience={SCHEDULER_PATIENCE})",
        "lr": LR,
        "dropout": DROPOUT,
        "weight_decay": WEIGHT_DECAY,
        "label_smoothing": LABEL_SMOOTHING,
        "unfreeze_patterns": UNFREEZE_PATTERNS,
        "checkpoint_criteria": "best_val_f1",
        "amp": True,
        "seed": SEED,
        "use_cbam": USE_CBAM,
        "cbam_reduction_ratio": CBAM_REDUCTION_RATIO,
        "cbam_spatial_kernel_size": CBAM_SPATIAL_KERNEL_SIZE,
    }
)

for fold, (train_idx, val_idx) in enumerate(skf.split(filepaths, labels)):
    result = train_one_fold(fold, train_idx, val_idx, run)
    all_results.append(result)

run.finish()

results_df = pd.DataFrame(all_results)
results_df

wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.

C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:54: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler()

  [CBAM] Disisipkan ke 16 Bottleneck block (layer1-4).
  [EXP04_ResNet50_CBAM] Trainable params: 25,846,327 / 26,071,671 (99.1%)

[EXP04_ResNet50_CBAM | fold 1] Epoch 1/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [04:19<00:00,  1.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:48<00:00,  2.01it/s]

Train Loss : 3.1606 | Val Loss  : 3.1581
Accuracy   : 0.1899  | Precision : 0.2913
Recall     : 0.1899  | F1 Score  : 0.1633
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.1633)

[EXP04_ResNet50_CBAM | fold 1] Epoch 2/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:59<00:00,  2.17it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 2.9204 | Val Loss  : 2.9304
Accuracy   : 0.2667  | Precision : 0.2833
Recall     : 0.2667  | F1 Score  : 0.2464
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.2464)

[EXP04_ResNet50_CBAM | fold 1] Epoch 3/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:59<00:00,  2.16it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.62it/s]

Train Loss : 2.7273 | Val Loss  : 2.8030
Accuracy   : 0.3091  | Precision : 0.3465
Recall     : 0.3091  | F1 Score  : 0.2945
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.2945)

[EXP04_ResNet50_CBAM | fold 1] Epoch 4/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [03:02<00:00,  2.13it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.53it/s]

Train Loss : 2.5892 | Val Loss  : 2.7427
Accuracy   : 0.3271  | Precision : 0.4000
Recall     : 0.3271  | F1 Score  : 0.3211
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.3211)

[EXP04_ResNet50_CBAM | fold 1] Epoch 5/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:58<00:00,  2.17it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.55it/s]

Train Loss : 2.4787 | Val Loss  : 2.6812
Accuracy   : 0.3480  | Precision : 0.4003
Recall     : 0.3480  | F1 Score  : 0.3425
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.3425)

[EXP04_ResNet50_CBAM | fold 1] Epoch 6/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [03:00<00:00,  2.16it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.62it/s]

Train Loss : 2.3825 | Val Loss  : 2.6372
Accuracy   : 0.3676  | Precision : 0.4266
Recall     : 0.3676  | F1 Score  : 0.3656
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.3656)

[EXP04_ResNet50_CBAM | fold 1] Epoch 7/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.57it/s]

Train Loss : 2.3005 | Val Loss  : 2.5949
Accuracy   : 0.3875  | Precision : 0.4433
Recall     : 0.3875  | F1 Score  : 0.3845
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.3845)

[EXP04_ResNet50_CBAM | fold 1] Epoch 8/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:58<00:00,  2.18it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.62it/s]

Train Loss : 2.2155 | Val Loss  : 2.5325
Accuracy   : 0.4062  | Precision : 0.4548
Recall     : 0.4062  | F1 Score  : 0.4095
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.4095)

[EXP04_ResNet50_CBAM | fold 1] Epoch 9/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.62it/s]

Train Loss : 2.1418 | Val Loss  : 2.5321
Accuracy   : 0.4152  | Precision : 0.4636
Recall     : 0.4152  | F1 Score  : 0.4147
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.4147)

[EXP04_ResNet50_CBAM | fold 1] Epoch 10/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:58<00:00,  2.18it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.52it/s]

Train Loss : 2.0681 | Val Loss  : 2.4925
Accuracy   : 0.4277  | Precision : 0.4750
Recall     : 0.4277  | F1 Score  : 0.4284
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.4284)

[EXP04_ResNet50_CBAM | fold 1] Epoch 11/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:59<00:00,  2.17it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.59it/s]

Train Loss : 1.9980 | Val Loss  : 2.4948
Accuracy   : 0.4393  | Precision : 0.4889
Recall     : 0.4393  | F1 Score  : 0.4413
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.4413)

[EXP04_ResNet50_CBAM | fold 1] Epoch 12/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:57<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.60it/s]

Train Loss : 1.9371 | Val Loss  : 2.4432
Accuracy   : 0.4515  | Precision : 0.5016
Recall     : 0.4515  | F1 Score  : 0.4546
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.4546)

[EXP04_ResNet50_CBAM | fold 1] Epoch 13/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:58<00:00,  2.18it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.54it/s]

Train Loss : 1.8702 | Val Loss  : 2.4562
Accuracy   : 0.4534  | Precision : 0.5058
Recall     : 0.4534  | F1 Score  : 0.4573
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.4573)

[EXP04_ResNet50_CBAM | fold 1] Epoch 14/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:59<00:00,  2.17it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.61it/s]

Train Loss : 1.8226 | Val Loss  : 2.4510
Accuracy   : 0.4605  | Precision : 0.5223
Recall     : 0.4605  | F1 Score  : 0.4667
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.4667)

[EXP04_ResNet50_CBAM | fold 1] Epoch 15/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:58<00:00,  2.18it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.55it/s]

Train Loss : 1.7483 | Val Loss  : 2.4172
Accuracy   : 0.4714  | Precision : 0.5286
Recall     : 0.4714  | F1 Score  : 0.4789
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.4789)

[EXP04_ResNet50_CBAM | fold 1] Epoch 16/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:59<00:00,  2.17it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.54it/s]

Train Loss : 1.7055 | Val Loss  : 2.4015
Accuracy   : 0.4804  | Precision : 0.5257
Recall     : 0.4804  | F1 Score  : 0.4841
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.4841)

[EXP04_ResNet50_CBAM | fold 1] Epoch 17/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:57<00:00,  2.19it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.61it/s]

Train Loss : 1.6548 | Val Loss  : 2.3899
Accuracy   : 0.4826  | Precision : 0.5269
Recall     : 0.4826  | F1 Score  : 0.4867
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.4867)

[EXP04_ResNet50_CBAM | fold 1] Epoch 18/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:57<00:00,  2.19it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.54it/s]

Train Loss : 1.6065 | Val Loss  : 2.4146
Accuracy   : 0.4814  | Precision : 0.5237
Recall     : 0.4814  | F1 Score  : 0.4822

[EXP04_ResNet50_CBAM | fold 1] Epoch 19/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [03:00<00:00,  2.15it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.59it/s]

Train Loss : 1.5603 | Val Loss  : 2.3860
Accuracy   : 0.4891  | Precision : 0.5301
Recall     : 0.4891  | F1 Score  : 0.4924
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.4924)

[EXP04_ResNet50_CBAM | fold 1] Epoch 20/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:57<00:00,  2.19it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.5125 | Val Loss  : 2.3707
Accuracy   : 0.4907  | Precision : 0.5326
Recall     : 0.4907  | F1 Score  : 0.4938
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.4938)

[EXP04_ResNet50_CBAM | fold 1] Epoch 21/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.4697 | Val Loss  : 2.3504
Accuracy   : 0.5096  | Precision : 0.5450
Recall     : 0.5096  | F1 Score  : 0.5125
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.5125)

[EXP04_ResNet50_CBAM | fold 1] Epoch 22/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:57<00:00,  2.19it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.63it/s]

Train Loss : 1.4218 | Val Loss  : 2.3413
Accuracy   : 0.5141  | Precision : 0.5459
Recall     : 0.5141  | F1 Score  : 0.5163
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.5163)

[EXP04_ResNet50_CBAM | fold 1] Epoch 23/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:57<00:00,  2.19it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.62it/s]

Train Loss : 1.4009 | Val Loss  : 2.3647
Accuracy   : 0.5093  | Precision : 0.5462
Recall     : 0.5093  | F1 Score  : 0.5144

[EXP04_ResNet50_CBAM | fold 1] Epoch 24/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [03:00<00:00,  2.16it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.57it/s]

Train Loss : 1.3604 | Val Loss  : 2.3315
Accuracy   : 0.5312  | Precision : 0.5608
Recall     : 0.5312  | F1 Score  : 0.5351
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.5351)

[EXP04_ResNet50_CBAM | fold 1] Epoch 25/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:59<00:00,  2.17it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:28<00:00,  3.47it/s]

Train Loss : 1.3352 | Val Loss  : 2.3129
Accuracy   : 0.5331  | Precision : 0.5557
Recall     : 0.5331  | F1 Score  : 0.5360
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.5360)

[EXP04_ResNet50_CBAM | fold 1] Epoch 26/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:59<00:00,  2.17it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.63it/s]

Train Loss : 1.3023 | Val Loss  : 2.3305
Accuracy   : 0.5276  | Precision : 0.5508
Recall     : 0.5276  | F1 Score  : 0.5294

[EXP04_ResNet50_CBAM | fold 1] Epoch 27/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:58<00:00,  2.18it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.57it/s]

Train Loss : 1.2821 | Val Loss  : 2.3067
Accuracy   : 0.5341  | Precision : 0.5553
Recall     : 0.5341  | F1 Score  : 0.5350

[EXP04_ResNet50_CBAM | fold 1] Epoch 28/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:58<00:00,  2.18it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:28<00:00,  3.43it/s]

Train Loss : 1.2585 | Val Loss  : 2.2839
Accuracy   : 0.5418  | Precision : 0.5581
Recall     : 0.5418  | F1 Score  : 0.5423
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.5423)

[EXP04_ResNet50_CBAM | fold 1] Epoch 29/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [03:02<00:00,  2.14it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.61it/s]

Train Loss : 1.2514 | Val Loss  : 2.3010
Accuracy   : 0.5389  | Precision : 0.5546
Recall     : 0.5389  | F1 Score  : 0.5394

[EXP04_ResNet50_CBAM | fold 1] Epoch 30/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:59<00:00,  2.17it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.55it/s]

Train Loss : 1.2131 | Val Loss  : 2.2672
Accuracy   : 0.5530  | Precision : 0.5690
Recall     : 0.5530  | F1 Score  : 0.5557
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.5557)

[EXP04_ResNet50_CBAM | fold 1] Epoch 31/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:59<00:00,  2.17it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.60it/s]

Train Loss : 1.1951 | Val Loss  : 2.2856
Accuracy   : 0.5469  | Precision : 0.5682
Recall     : 0.5469  | F1 Score  : 0.5484

[EXP04_ResNet50_CBAM | fold 1] Epoch 32/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:58<00:00,  2.17it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.70it/s]

Train Loss : 1.1722 | Val Loss  : 2.2799
Accuracy   : 0.5572  | Precision : 0.5739
Recall     : 0.5572  | F1 Score  : 0.5591
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.5591)

[EXP04_ResNet50_CBAM | fold 1] Epoch 33/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:59<00:00,  2.17it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.61it/s]

Train Loss : 1.1510 | Val Loss  : 2.2857
Accuracy   : 0.5530  | Precision : 0.5707
Recall     : 0.5530  | F1 Score  : 0.5541

[EXP04_ResNet50_CBAM | fold 1] Epoch 34/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:59<00:00,  2.16it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.52it/s]

Train Loss : 1.1403 | Val Loss  : 2.2549
Accuracy   : 0.5652  | Precision : 0.5779
Recall     : 0.5652  | F1 Score  : 0.5647
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.5647)

[EXP04_ResNet50_CBAM | fold 1] Epoch 35/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [03:00<00:00,  2.16it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:28<00:00,  3.43it/s]

Train Loss : 1.1356 | Val Loss  : 2.2325
Accuracy   : 0.5684  | Precision : 0.5792
Recall     : 0.5684  | F1 Score  : 0.5708
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.5708)

[EXP04_ResNet50_CBAM | fold 1] Epoch 36/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:59<00:00,  2.16it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.57it/s]

Train Loss : 1.1091 | Val Loss  : 2.2558
Accuracy   : 0.5649  | Precision : 0.5737
Recall     : 0.5649  | F1 Score  : 0.5658

[EXP04_ResNet50_CBAM | fold 1] Epoch 37/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [03:00<00:00,  2.16it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.54it/s]

Train Loss : 1.0962 | Val Loss  : 2.2392
Accuracy   : 0.5790  | Precision : 0.5878
Recall     : 0.5790  | F1 Score  : 0.5804
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.5804)

[EXP04_ResNet50_CBAM | fold 1] Epoch 38/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:57<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.60it/s]

Train Loss : 1.0878 | Val Loss  : 2.2517
Accuracy   : 0.5694  | Precision : 0.5797
Recall     : 0.5694  | F1 Score  : 0.5699

[EXP04_ResNet50_CBAM | fold 1] Epoch 39/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:58<00:00,  2.17it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.69it/s]

Train Loss : 1.0672 | Val Loss  : 2.2368
Accuracy   : 0.5749  | Precision : 0.5815
Recall     : 0.5749  | F1 Score  : 0.5752

[EXP04_ResNet50_CBAM | fold 1] Epoch 40/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:58<00:00,  2.17it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.69it/s]

Train Loss : 1.0684 | Val Loss  : 2.2584
Accuracy   : 0.5652  | Precision : 0.5707
Recall     : 0.5652  | F1 Score  : 0.5647

[EXP04_ResNet50_CBAM | fold 1] Epoch 41/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.63it/s]

Train Loss : 1.0344 | Val Loss  : 2.2252
Accuracy   : 0.5816  | Precision : 0.5873
Recall     : 0.5816  | F1 Score  : 0.5813
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.5813)

[EXP04_ResNet50_CBAM | fold 1] Epoch 42/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.69it/s]

Train Loss : 1.0198 | Val Loss  : 2.2319
Accuracy   : 0.5807  | Precision : 0.5872
Recall     : 0.5807  | F1 Score  : 0.5794

[EXP04_ResNet50_CBAM | fold 1] Epoch 43/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:58<00:00,  2.18it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.59it/s]

Train Loss : 1.0140 | Val Loss  : 2.2331
Accuracy   : 0.5787  | Precision : 0.5852
Recall     : 0.5787  | F1 Score  : 0.5781

[EXP04_ResNet50_CBAM | fold 1] Epoch 44/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [03:01<00:00,  2.14it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:28<00:00,  3.48it/s]

Train Loss : 1.0122 | Val Loss  : 2.2133
Accuracy   : 0.5890  | Precision : 0.5941
Recall     : 0.5890  | F1 Score  : 0.5890
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.5890)

[EXP04_ResNet50_CBAM | fold 1] Epoch 45/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [03:00<00:00,  2.15it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.59it/s]

Train Loss : 1.0089 | Val Loss  : 2.2246
Accuracy   : 0.5852  | Precision : 0.5916
Recall     : 0.5852  | F1 Score  : 0.5859

[EXP04_ResNet50_CBAM | fold 1] Epoch 46/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:57<00:00,  2.19it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.60it/s]

Train Loss : 1.0065 | Val Loss  : 2.1983
Accuracy   : 0.5832  | Precision : 0.5860
Recall     : 0.5832  | F1 Score  : 0.5823

[EXP04_ResNet50_CBAM | fold 1] Epoch 47/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:59<00:00,  2.16it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.0037 | Val Loss  : 2.2033
Accuracy   : 0.5900  | Precision : 0.5947
Recall     : 0.5900  | F1 Score  : 0.5894
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold1.pth (F1: 0.5894)

[EXP04_ResNet50_CBAM | fold 1] Epoch 48/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.22it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 0.9971 | Val Loss  : 2.2064
Accuracy   : 0.5871  | Precision : 0.5889
Recall     : 0.5871  | F1 Score  : 0.5855

[EXP04_ResNet50_CBAM | fold 1] Epoch 49/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.22it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 0.9977 | Val Loss  : 2.2145
Accuracy   : 0.5868  | Precision : 0.5944
Recall     : 0.5868  | F1 Score  : 0.5872

[EXP04_ResNet50_CBAM | fold 1] Epoch 50/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:57<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.68it/s]

Train Loss : 0.9932 | Val Loss  : 2.2086
Accuracy   : 0.5835  | Precision : 0.5886
Recall     : 0.5835  | F1 Score  : 0.5837

C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:54: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler()

  [CBAM] Disisipkan ke 16 Bottleneck block (layer1-4).
  [EXP04_ResNet50_CBAM] Trainable params: 25,846,327 / 26,071,671 (99.1%)

[EXP04_ResNet50_CBAM | fold 2] Epoch 1/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [03:00<00:00,  2.16it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.63it/s]

Train Loss : 3.1496 | Val Loss  : 3.1378
Accuracy   : 0.2008  | Precision : 0.2543
Recall     : 0.2008  | F1 Score  : 0.1766
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.1766)

[EXP04_ResNet50_CBAM | fold 2] Epoch 2/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.63it/s]

Train Loss : 2.9512 | Val Loss  : 3.0020
Accuracy   : 0.2410  | Precision : 0.3175
Recall     : 0.2410  | F1 Score  : 0.2270
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.2270)

[EXP04_ResNet50_CBAM | fold 2] Epoch 3/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 2.7914 | Val Loss  : 2.9063
Accuracy   : 0.2841  | Precision : 0.3259
Recall     : 0.2841  | F1 Score  : 0.2724
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.2724)

[EXP04_ResNet50_CBAM | fold 2] Epoch 4/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 2.6624 | Val Loss  : 2.7849
Accuracy   : 0.3123  | Precision : 0.3536
Recall     : 0.3123  | F1 Score  : 0.2981
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.2981)

[EXP04_ResNet50_CBAM | fold 2] Epoch 5/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 2.5445 | Val Loss  : 2.7419
Accuracy   : 0.3332  | Precision : 0.3814
Recall     : 0.3332  | F1 Score  : 0.3257
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.3257)

[EXP04_ResNet50_CBAM | fold 2] Epoch 6/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 2.4434 | Val Loss  : 2.7008
Accuracy   : 0.3548  | Precision : 0.4145
Recall     : 0.3548  | F1 Score  : 0.3459
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.3459)

[EXP04_ResNet50_CBAM | fold 2] Epoch 7/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.63it/s]

Train Loss : 2.3520 | Val Loss  : 2.6312
Accuracy   : 0.3776  | Precision : 0.4336
Recall     : 0.3776  | F1 Score  : 0.3782
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.3782)

[EXP04_ResNet50_CBAM | fold 2] Epoch 8/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 2.2637 | Val Loss  : 2.5979
Accuracy   : 0.3924  | Precision : 0.4504
Recall     : 0.3924  | F1 Score  : 0.3958
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.3958)

[EXP04_ResNet50_CBAM | fold 2] Epoch 9/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 2.1759 | Val Loss  : 2.5534
Accuracy   : 0.4036  | Precision : 0.4573
Recall     : 0.4036  | F1 Score  : 0.4090
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.4090)

[EXP04_ResNet50_CBAM | fold 2] Epoch 10/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 2.0998 | Val Loss  : 2.5262
Accuracy   : 0.4181  | Precision : 0.4734
Recall     : 0.4181  | F1 Score  : 0.4205
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.4205)

[EXP04_ResNet50_CBAM | fold 2] Epoch 11/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 2.0166 | Val Loss  : 2.4958
Accuracy   : 0.4406  | Precision : 0.4959
Recall     : 0.4406  | F1 Score  : 0.4463
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.4463)

[EXP04_ResNet50_CBAM | fold 2] Epoch 12/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.63it/s]

Train Loss : 1.9616 | Val Loss  : 2.4872
Accuracy   : 0.4470  | Precision : 0.5116
Recall     : 0.4470  | F1 Score  : 0.4513
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.4513)

[EXP04_ResNet50_CBAM | fold 2] Epoch 13/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.8852 | Val Loss  : 2.4696
Accuracy   : 0.4496  | Precision : 0.5074
Recall     : 0.4496  | F1 Score  : 0.4552
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.4552)

[EXP04_ResNet50_CBAM | fold 2] Epoch 14/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.62it/s]

Train Loss : 1.8262 | Val Loss  : 2.4689
Accuracy   : 0.4486  | Precision : 0.5103
Recall     : 0.4486  | F1 Score  : 0.4542

[EXP04_ResNet50_CBAM | fold 2] Epoch 15/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.62it/s]

Train Loss : 1.7665 | Val Loss  : 2.4113
Accuracy   : 0.4785  | Precision : 0.5154
Recall     : 0.4785  | F1 Score  : 0.4809
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.4809)

[EXP04_ResNet50_CBAM | fold 2] Epoch 16/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.63it/s]

Train Loss : 1.6986 | Val Loss  : 2.4206
Accuracy   : 0.4733  | Precision : 0.5217
Recall     : 0.4733  | F1 Score  : 0.4766

[EXP04_ResNet50_CBAM | fold 2] Epoch 17/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.63it/s]

Train Loss : 1.6403 | Val Loss  : 2.4002
Accuracy   : 0.4781  | Precision : 0.5228
Recall     : 0.4781  | F1 Score  : 0.4828
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.4828)

[EXP04_ResNet50_CBAM | fold 2] Epoch 18/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.63it/s]

Train Loss : 1.6003 | Val Loss  : 2.3868
Accuracy   : 0.4849  | Precision : 0.5245
Recall     : 0.4849  | F1 Score  : 0.4878
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.4878)

[EXP04_ResNet50_CBAM | fold 2] Epoch 19/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.63it/s]

Train Loss : 1.5396 | Val Loss  : 2.3635
Accuracy   : 0.4987  | Precision : 0.5405
Recall     : 0.4987  | F1 Score  : 0.5029
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.5029)

[EXP04_ResNet50_CBAM | fold 2] Epoch 20/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.63it/s]

Train Loss : 1.5013 | Val Loss  : 2.3754
Accuracy   : 0.4987  | Precision : 0.5327
Recall     : 0.4987  | F1 Score  : 0.5013

[EXP04_ResNet50_CBAM | fold 2] Epoch 21/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.4592 | Val Loss  : 2.3588
Accuracy   : 0.5051  | Precision : 0.5359
Recall     : 0.5051  | F1 Score  : 0.5068
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.5068)

[EXP04_ResNet50_CBAM | fold 2] Epoch 22/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.63it/s]

Train Loss : 1.4221 | Val Loss  : 2.3547
Accuracy   : 0.5084  | Precision : 0.5533
Recall     : 0.5084  | F1 Score  : 0.5154
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.5154)

[EXP04_ResNet50_CBAM | fold 2] Epoch 23/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.61it/s]

Train Loss : 1.3901 | Val Loss  : 2.3327
Accuracy   : 0.5141  | Precision : 0.5455
Recall     : 0.5141  | F1 Score  : 0.5167
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.5167)

[EXP04_ResNet50_CBAM | fold 2] Epoch 24/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.63it/s]

Train Loss : 1.3622 | Val Loss  : 2.3091
Accuracy   : 0.5337  | Precision : 0.5560
Recall     : 0.5337  | F1 Score  : 0.5364
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.5364)

[EXP04_ResNet50_CBAM | fold 2] Epoch 25/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.63it/s]

Train Loss : 1.3309 | Val Loss  : 2.3068
Accuracy   : 0.5251  | Precision : 0.5489
Recall     : 0.5251  | F1 Score  : 0.5263

[EXP04_ResNet50_CBAM | fold 2] Epoch 26/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.63it/s]

Train Loss : 1.2980 | Val Loss  : 2.3326
Accuracy   : 0.5244  | Precision : 0.5533
Recall     : 0.5244  | F1 Score  : 0.5274

[EXP04_ResNet50_CBAM | fold 2] Epoch 27/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.62it/s]

Train Loss : 1.2741 | Val Loss  : 2.3085
Accuracy   : 0.5292  | Precision : 0.5517
Recall     : 0.5292  | F1 Score  : 0.5319

[EXP04_ResNet50_CBAM | fold 2] Epoch 28/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.62it/s]

Train Loss : 1.2294 | Val Loss  : 2.2817
Accuracy   : 0.5392  | Precision : 0.5584
Recall     : 0.5392  | F1 Score  : 0.5420
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.5420)

[EXP04_ResNet50_CBAM | fold 2] Epoch 29/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.63it/s]

Train Loss : 1.2011 | Val Loss  : 2.2905
Accuracy   : 0.5421  | Precision : 0.5648
Recall     : 0.5421  | F1 Score  : 0.5445
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.5445)

[EXP04_ResNet50_CBAM | fold 2] Epoch 30/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.62it/s]

Train Loss : 1.1934 | Val Loss  : 2.2769
Accuracy   : 0.5476  | Precision : 0.5645
Recall     : 0.5476  | F1 Score  : 0.5497
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.5497)

[EXP04_ResNet50_CBAM | fold 2] Epoch 31/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.56it/s]

Train Loss : 1.1848 | Val Loss  : 2.2712
Accuracy   : 0.5495  | Precision : 0.5698
Recall     : 0.5495  | F1 Score  : 0.5525
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.5525)

[EXP04_ResNet50_CBAM | fold 2] Epoch 32/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [03:00<00:00,  2.16it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.60it/s]

Train Loss : 1.1925 | Val Loss  : 2.2865
Accuracy   : 0.5450  | Precision : 0.5662
Recall     : 0.5450  | F1 Score  : 0.5472

[EXP04_ResNet50_CBAM | fold 2] Epoch 33/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:58<00:00,  2.18it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.60it/s]

Train Loss : 1.1801 | Val Loss  : 2.2841
Accuracy   : 0.5485  | Precision : 0.5702
Recall     : 0.5485  | F1 Score  : 0.5509

[EXP04_ResNet50_CBAM | fold 2] Epoch 34/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:57<00:00,  2.19it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.58it/s]

Train Loss : 1.1722 | Val Loss  : 2.2880
Accuracy   : 0.5514  | Precision : 0.5717
Recall     : 0.5514  | F1 Score  : 0.5545
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.5545)

[EXP04_ResNet50_CBAM | fold 2] Epoch 35/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [03:02<00:00,  2.13it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:28<00:00,  3.48it/s]

Train Loss : 1.1678 | Val Loss  : 2.2759
Accuracy   : 0.5469  | Precision : 0.5666
Recall     : 0.5469  | F1 Score  : 0.5493

[EXP04_ResNet50_CBAM | fold 2] Epoch 36/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [03:02<00:00,  2.13it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:28<00:00,  3.49it/s]

Train Loss : 1.1646 | Val Loss  : 2.2591
Accuracy   : 0.5572  | Precision : 0.5707
Recall     : 0.5572  | F1 Score  : 0.5589
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.5589)

[EXP04_ResNet50_CBAM | fold 2] Epoch 37/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [03:00<00:00,  2.15it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.61it/s]

Train Loss : 1.1700 | Val Loss  : 2.2669
Accuracy   : 0.5559  | Precision : 0.5751
Recall     : 0.5559  | F1 Score  : 0.5587

[EXP04_ResNet50_CBAM | fold 2] Epoch 38/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:59<00:00,  2.17it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.1590 | Val Loss  : 2.2682
Accuracy   : 0.5527  | Precision : 0.5698
Recall     : 0.5527  | F1 Score  : 0.5544

[EXP04_ResNet50_CBAM | fold 2] Epoch 39/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [03:00<00:00,  2.16it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.63it/s]

Train Loss : 1.1605 | Val Loss  : 2.2589
Accuracy   : 0.5556  | Precision : 0.5685
Recall     : 0.5556  | F1 Score  : 0.5568

[EXP04_ResNet50_CBAM | fold 2] Epoch 40/50 (LR: 1.00e-06)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:59<00:00,  2.17it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.62it/s]

Train Loss : 1.1504 | Val Loss  : 2.2864
Accuracy   : 0.5530  | Precision : 0.5763
Recall     : 0.5530  | F1 Score  : 0.5568

[EXP04_ResNet50_CBAM | fold 2] Epoch 41/50 (LR: 1.00e-06)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:58<00:00,  2.18it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.1505 | Val Loss  : 2.2776
Accuracy   : 0.5527  | Precision : 0.5726
Recall     : 0.5527  | F1 Score  : 0.5563

[EXP04_ResNet50_CBAM | fold 2] Epoch 42/50 (LR: 1.00e-06)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:59<00:00,  2.17it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.1493 | Val Loss  : 2.2674
Accuracy   : 0.5582  | Precision : 0.5767
Recall     : 0.5582  | F1 Score  : 0.5611
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.5611)

[EXP04_ResNet50_CBAM | fold 2] Epoch 43/50 (LR: 1.00e-06)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:57<00:00,  2.19it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 1.1540 | Val Loss  : 2.2564
Accuracy   : 0.5601  | Precision : 0.5730
Recall     : 0.5601  | F1 Score  : 0.5617
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold2.pth (F1: 0.5617)

[EXP04_ResNet50_CBAM | fold 2] Epoch 44/50 (LR: 1.00e-06)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:57<00:00,  2.19it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 1.1458 | Val Loss  : 2.2771
Accuracy   : 0.5546  | Precision : 0.5745
Recall     : 0.5546  | F1 Score  : 0.5566

[EXP04_ResNet50_CBAM | fold 2] Epoch 45/50 (LR: 1.00e-06)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:57<00:00,  2.19it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.1461 | Val Loss  : 2.2635
Accuracy   : 0.5598  | Precision : 0.5743
Recall     : 0.5598  | F1 Score  : 0.5612

[EXP04_ResNet50_CBAM | fold 2] Epoch 46/50 (LR: 1.00e-06)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.1479 | Val Loss  : 2.2706
Accuracy   : 0.5546  | Precision : 0.5712
Recall     : 0.5546  | F1 Score  : 0.5560

[EXP04_ResNet50_CBAM | fold 2] Epoch 47/50 (LR: 1.00e-07)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:57<00:00,  2.19it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.62it/s]

Train Loss : 1.1454 | Val Loss  : 2.2633
Accuracy   : 0.5566  | Precision : 0.5748
Recall     : 0.5566  | F1 Score  : 0.5588

[EXP04_ResNet50_CBAM | fold 2] Epoch 48/50 (LR: 1.00e-07)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.63it/s]

Train Loss : 1.1466 | Val Loss  : 2.2718
Accuracy   : 0.5517  | Precision : 0.5700
Recall     : 0.5517  | F1 Score  : 0.5544

[EXP04_ResNet50_CBAM | fold 2] Epoch 49/50 (LR: 1.00e-07)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.61it/s]

Train Loss : 1.1475 | Val Loss  : 2.2564
Accuracy   : 0.5533  | Precision : 0.5673
Recall     : 0.5533  | F1 Score  : 0.5553

[EXP04_ResNet50_CBAM | fold 2] Epoch 50/50 (LR: 1.00e-07)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.1432 | Val Loss  : 2.2631
Accuracy   : 0.5540  | Precision : 0.5708
Recall     : 0.5540  | F1 Score  : 0.5567
Early Stopping Triggered

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:54: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler()

  [CBAM] Disisipkan ke 16 Bottleneck block (layer1-4).
  [EXP04_ResNet50_CBAM] Trainable params: 25,846,327 / 26,071,671 (99.1%)

[EXP04_ResNet50_CBAM | fold 3] Epoch 1/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [03:33<00:00,  1.82it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:47<00:00,  2.07it/s]

Train Loss : 3.1691 | Val Loss  : 3.1824
Accuracy   : 0.1655  | Precision : 0.2616
Recall     : 0.1655  | F1 Score  : 0.1410
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.1410)

[EXP04_ResNet50_CBAM | fold 3] Epoch 2/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 2.9353 | Val Loss  : 3.0455
Accuracy   : 0.2131  | Precision : 0.3085
Recall     : 0.2131  | F1 Score  : 0.2053
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.2053)

[EXP04_ResNet50_CBAM | fold 3] Epoch 3/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.63it/s]

Train Loss : 2.7650 | Val Loss  : 2.8992
Accuracy   : 0.2755  | Precision : 0.3227
Recall     : 0.2755  | F1 Score  : 0.2613
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.2613)

[EXP04_ResNet50_CBAM | fold 3] Epoch 4/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.63it/s]

Train Loss : 2.6264 | Val Loss  : 2.8190
Accuracy   : 0.3031  | Precision : 0.3730
Recall     : 0.3031  | F1 Score  : 0.2993
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.2993)

[EXP04_ResNet50_CBAM | fold 3] Epoch 5/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.63it/s]

Train Loss : 2.5165 | Val Loss  : 2.7923
Accuracy   : 0.3124  | Precision : 0.3963
Recall     : 0.3124  | F1 Score  : 0.3075
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.3075)

[EXP04_ResNet50_CBAM | fold 3] Epoch 6/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.63it/s]

Train Loss : 2.4158 | Val Loss  : 2.7072
Accuracy   : 0.3478  | Precision : 0.4198
Recall     : 0.3478  | F1 Score  : 0.3488
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.3488)

[EXP04_ResNet50_CBAM | fold 3] Epoch 7/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.62it/s]

Train Loss : 2.3298 | Val Loss  : 2.6413
Accuracy   : 0.3729  | Precision : 0.4425
Recall     : 0.3729  | F1 Score  : 0.3792
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.3792)

[EXP04_ResNet50_CBAM | fold 3] Epoch 8/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.62it/s]

Train Loss : 2.2346 | Val Loss  : 2.6292
Accuracy   : 0.3780  | Precision : 0.4573
Recall     : 0.3780  | F1 Score  : 0.3826
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.3826)

[EXP04_ResNet50_CBAM | fold 3] Epoch 9/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.60it/s]

Train Loss : 2.1570 | Val Loss  : 2.5829
Accuracy   : 0.3979  | Precision : 0.4675
Recall     : 0.3979  | F1 Score  : 0.4045
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.4045)

[EXP04_ResNet50_CBAM | fold 3] Epoch 10/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.63it/s]

Train Loss : 2.0802 | Val Loss  : 2.5519
Accuracy   : 0.4159  | Precision : 0.4813
Recall     : 0.4159  | F1 Score  : 0.4249
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.4249)

[EXP04_ResNet50_CBAM | fold 3] Epoch 11/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 2.0093 | Val Loss  : 2.5385
Accuracy   : 0.4214  | Precision : 0.4941
Recall     : 0.4214  | F1 Score  : 0.4312
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.4312)

[EXP04_ResNet50_CBAM | fold 3] Epoch 12/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.9441 | Val Loss  : 2.5033
Accuracy   : 0.4253  | Precision : 0.4811
Recall     : 0.4253  | F1 Score  : 0.4297

[EXP04_ResNet50_CBAM | fold 3] Epoch 13/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.8717 | Val Loss  : 2.4925
Accuracy   : 0.4365  | Precision : 0.4988
Recall     : 0.4365  | F1 Score  : 0.4432
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.4432)

[EXP04_ResNet50_CBAM | fold 3] Epoch 14/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.68it/s]

Train Loss : 1.8154 | Val Loss  : 2.4581
Accuracy   : 0.4529  | Precision : 0.5088
Recall     : 0.4529  | F1 Score  : 0.4610
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.4610)

[EXP04_ResNet50_CBAM | fold 3] Epoch 15/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.7441 | Val Loss  : 2.4741
Accuracy   : 0.4606  | Precision : 0.5164
Recall     : 0.4606  | F1 Score  : 0.4667
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.4667)

[EXP04_ResNet50_CBAM | fold 3] Epoch 16/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.6960 | Val Loss  : 2.4359
Accuracy   : 0.4677  | Precision : 0.5172
Recall     : 0.4677  | F1 Score  : 0.4750
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.4750)

[EXP04_ResNet50_CBAM | fold 3] Epoch 17/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.6390 | Val Loss  : 2.4059
Accuracy   : 0.4860  | Precision : 0.5292
Recall     : 0.4860  | F1 Score  : 0.4925
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.4925)

[EXP04_ResNet50_CBAM | fold 3] Epoch 18/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.5943 | Val Loss  : 2.4102
Accuracy   : 0.4921  | Precision : 0.5325
Recall     : 0.4921  | F1 Score  : 0.5001
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.5001)

[EXP04_ResNet50_CBAM | fold 3] Epoch 19/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.5460 | Val Loss  : 2.4159
Accuracy   : 0.4879  | Precision : 0.5262
Recall     : 0.4879  | F1 Score  : 0.4941

[EXP04_ResNet50_CBAM | fold 3] Epoch 20/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.5127 | Val Loss  : 2.4082
Accuracy   : 0.4937  | Precision : 0.5338
Recall     : 0.4937  | F1 Score  : 0.4998

[EXP04_ResNet50_CBAM | fold 3] Epoch 21/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.4640 | Val Loss  : 2.3786
Accuracy   : 0.5050  | Precision : 0.5401
Recall     : 0.5050  | F1 Score  : 0.5102
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.5102)

[EXP04_ResNet50_CBAM | fold 3] Epoch 22/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.22it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 1.4281 | Val Loss  : 2.3778
Accuracy   : 0.5085  | Precision : 0.5310
Recall     : 0.5085  | F1 Score  : 0.5120
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.5120)

[EXP04_ResNet50_CBAM | fold 3] Epoch 23/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.22it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.3956 | Val Loss  : 2.3941
Accuracy   : 0.5111  | Precision : 0.5470
Recall     : 0.5111  | F1 Score  : 0.5168
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.5168)

[EXP04_ResNet50_CBAM | fold 3] Epoch 24/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.3718 | Val Loss  : 2.3447
Accuracy   : 0.5272  | Precision : 0.5517
Recall     : 0.5272  | F1 Score  : 0.5309
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.5309)

[EXP04_ResNet50_CBAM | fold 3] Epoch 25/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.3320 | Val Loss  : 2.3786
Accuracy   : 0.5114  | Precision : 0.5424
Recall     : 0.5114  | F1 Score  : 0.5166

[EXP04_ResNet50_CBAM | fold 3] Epoch 26/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.62it/s]

Train Loss : 1.3130 | Val Loss  : 2.3582
Accuracy   : 0.5284  | Precision : 0.5488
Recall     : 0.5284  | F1 Score  : 0.5324
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.5324)

[EXP04_ResNet50_CBAM | fold 3] Epoch 27/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.2806 | Val Loss  : 2.3452
Accuracy   : 0.5227  | Precision : 0.5447
Recall     : 0.5227  | F1 Score  : 0.5253

[EXP04_ResNet50_CBAM | fold 3] Epoch 28/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.2637 | Val Loss  : 2.3512
Accuracy   : 0.5326  | Precision : 0.5559
Recall     : 0.5326  | F1 Score  : 0.5369
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.5369)

[EXP04_ResNet50_CBAM | fold 3] Epoch 29/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.2469 | Val Loss  : 2.3532
Accuracy   : 0.5320  | Precision : 0.5553
Recall     : 0.5320  | F1 Score  : 0.5342

[EXP04_ResNet50_CBAM | fold 3] Epoch 30/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.2105 | Val Loss  : 2.3461
Accuracy   : 0.5333  | Precision : 0.5505
Recall     : 0.5333  | F1 Score  : 0.5350

[EXP04_ResNet50_CBAM | fold 3] Epoch 31/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.1846 | Val Loss  : 2.3388
Accuracy   : 0.5436  | Precision : 0.5616
Recall     : 0.5436  | F1 Score  : 0.5457
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.5457)

[EXP04_ResNet50_CBAM | fold 3] Epoch 32/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.1679 | Val Loss  : 2.3415
Accuracy   : 0.5394  | Precision : 0.5512
Recall     : 0.5394  | F1 Score  : 0.5414

[EXP04_ResNet50_CBAM | fold 3] Epoch 33/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.1566 | Val Loss  : 2.3662
Accuracy   : 0.5301  | Precision : 0.5505
Recall     : 0.5301  | F1 Score  : 0.5331

[EXP04_ResNet50_CBAM | fold 3] Epoch 34/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.1464 | Val Loss  : 2.3426
Accuracy   : 0.5413  | Precision : 0.5627
Recall     : 0.5413  | F1 Score  : 0.5443

[EXP04_ResNet50_CBAM | fold 3] Epoch 35/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.63it/s]

Train Loss : 1.1014 | Val Loss  : 2.3305
Accuracy   : 0.5500  | Precision : 0.5672
Recall     : 0.5500  | F1 Score  : 0.5526
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.5526)

[EXP04_ResNet50_CBAM | fold 3] Epoch 36/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.0876 | Val Loss  : 2.3015
Accuracy   : 0.5529  | Precision : 0.5684
Recall     : 0.5529  | F1 Score  : 0.5553
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.5553)

[EXP04_ResNet50_CBAM | fold 3] Epoch 37/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.0770 | Val Loss  : 2.3017
Accuracy   : 0.5596  | Precision : 0.5704
Recall     : 0.5596  | F1 Score  : 0.5611
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.5611)

[EXP04_ResNet50_CBAM | fold 3] Epoch 38/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.0774 | Val Loss  : 2.3099
Accuracy   : 0.5464  | Precision : 0.5603
Recall     : 0.5464  | F1 Score  : 0.5488

[EXP04_ResNet50_CBAM | fold 3] Epoch 39/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.0719 | Val Loss  : 2.3012
Accuracy   : 0.5535  | Precision : 0.5659
Recall     : 0.5535  | F1 Score  : 0.5561

[EXP04_ResNet50_CBAM | fold 3] Epoch 40/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.63it/s]

Train Loss : 1.0670 | Val Loss  : 2.3015
Accuracy   : 0.5551  | Precision : 0.5652
Recall     : 0.5551  | F1 Score  : 0.5572

[EXP04_ResNet50_CBAM | fold 3] Epoch 41/50 (LR: 1.00e-06)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.63it/s]

Train Loss : 1.0602 | Val Loss  : 2.2902
Accuracy   : 0.5538  | Precision : 0.5625
Recall     : 0.5538  | F1 Score  : 0.5551

[EXP04_ResNet50_CBAM | fold 3] Epoch 42/50 (LR: 1.00e-06)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.63it/s]

Train Loss : 1.0631 | Val Loss  : 2.3172
Accuracy   : 0.5545  | Precision : 0.5699
Recall     : 0.5545  | F1 Score  : 0.5569

[EXP04_ResNet50_CBAM | fold 3] Epoch 43/50 (LR: 1.00e-06)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.63it/s]

Train Loss : 1.0634 | Val Loss  : 2.2921
Accuracy   : 0.5509  | Precision : 0.5604
Recall     : 0.5509  | F1 Score  : 0.5525

[EXP04_ResNet50_CBAM | fold 3] Epoch 44/50 (LR: 1.00e-07)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.0588 | Val Loss  : 2.2874
Accuracy   : 0.5619  | Precision : 0.5717
Recall     : 0.5619  | F1 Score  : 0.5639
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold3.pth (F1: 0.5639)

[EXP04_ResNet50_CBAM | fold 3] Epoch 45/50 (LR: 1.00e-07)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.63it/s]

Train Loss : 1.0621 | Val Loss  : 2.2897
Accuracy   : 0.5532  | Precision : 0.5626
Recall     : 0.5532  | F1 Score  : 0.5540

[EXP04_ResNet50_CBAM | fold 3] Epoch 46/50 (LR: 1.00e-07)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.63it/s]

Train Loss : 1.0628 | Val Loss  : 2.2926
Accuracy   : 0.5561  | Precision : 0.5664
Recall     : 0.5561  | F1 Score  : 0.5577

[EXP04_ResNet50_CBAM | fold 3] Epoch 47/50 (LR: 1.00e-07)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.0641 | Val Loss  : 2.3218
Accuracy   : 0.5497  | Precision : 0.5650
Recall     : 0.5497  | F1 Score  : 0.5521

[EXP04_ResNet50_CBAM | fold 3] Epoch 48/50 (LR: 1.00e-07)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.0571 | Val Loss  : 2.2980
Accuracy   : 0.5519  | Precision : 0.5639
Recall     : 0.5519  | F1 Score  : 0.5545

[EXP04_ResNet50_CBAM | fold 3] Epoch 49/50 (LR: 1.00e-07)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.0620 | Val Loss  : 2.3022
Accuracy   : 0.5522  | Precision : 0.5646
Recall     : 0.5522  | F1 Score  : 0.5536

[EXP04_ResNet50_CBAM | fold 3] Epoch 50/50 (LR: 1.00e-07)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:57<00:00,  2.19it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.0581 | Val Loss  : 2.3071
Accuracy   : 0.5567  | Precision : 0.5713
Recall     : 0.5567  | F1 Score  : 0.5592

C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:54: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler()

  [CBAM] Disisipkan ke 16 Bottleneck block (layer1-4).
  [EXP04_ResNet50_CBAM] Trainable params: 25,846,327 / 26,071,671 (99.1%)

[EXP04_ResNet50_CBAM | fold 4] Epoch 1/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.68it/s]

Train Loss : 3.1562 | Val Loss  : 3.1459
Accuracy   : 0.1935  | Precision : 0.2284
Recall     : 0.1935  | F1 Score  : 0.1731
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.1731)

[EXP04_ResNet50_CBAM | fold 4] Epoch 2/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 2.9095 | Val Loss  : 2.9753
Accuracy   : 0.2520  | Precision : 0.3134
Recall     : 0.2520  | F1 Score  : 0.2418
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.2418)

[EXP04_ResNet50_CBAM | fold 4] Epoch 3/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 2.7413 | Val Loss  : 2.8482
Accuracy   : 0.3025  | Precision : 0.3604
Recall     : 0.3025  | F1 Score  : 0.2846
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.2846)

[EXP04_ResNet50_CBAM | fold 4] Epoch 4/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 2.6084 | Val Loss  : 2.7681
Accuracy   : 0.3259  | Precision : 0.3903
Recall     : 0.3259  | F1 Score  : 0.3212
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.3212)

[EXP04_ResNet50_CBAM | fold 4] Epoch 5/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 2.4982 | Val Loss  : 2.7000
Accuracy   : 0.3523  | Precision : 0.4096
Recall     : 0.3523  | F1 Score  : 0.3517
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.3517)

[EXP04_ResNet50_CBAM | fold 4] Epoch 6/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 2.4020 | Val Loss  : 2.6204
Accuracy   : 0.3841  | Precision : 0.4237
Recall     : 0.3841  | F1 Score  : 0.3808
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.3808)

[EXP04_ResNet50_CBAM | fold 4] Epoch 7/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 2.3155 | Val Loss  : 2.6018
Accuracy   : 0.3803  | Precision : 0.4331
Recall     : 0.3803  | F1 Score  : 0.3767

[EXP04_ResNet50_CBAM | fold 4] Epoch 8/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.63it/s]

Train Loss : 2.2362 | Val Loss  : 2.5518
Accuracy   : 0.4021  | Precision : 0.4561
Recall     : 0.4021  | F1 Score  : 0.4063
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.4063)

[EXP04_ResNet50_CBAM | fold 4] Epoch 9/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 2.1600 | Val Loss  : 2.5424
Accuracy   : 0.4057  | Precision : 0.4678
Recall     : 0.4057  | F1 Score  : 0.4107
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.4107)

[EXP04_ResNet50_CBAM | fold 4] Epoch 10/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 2.0803 | Val Loss  : 2.4899
Accuracy   : 0.4359  | Precision : 0.4928
Recall     : 0.4359  | F1 Score  : 0.4433
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.4433)

[EXP04_ResNet50_CBAM | fold 4] Epoch 11/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 2.0119 | Val Loss  : 2.4439
Accuracy   : 0.4507  | Precision : 0.4905
Recall     : 0.4507  | F1 Score  : 0.4510
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.4510)

[EXP04_ResNet50_CBAM | fold 4] Epoch 12/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.9510 | Val Loss  : 2.4567
Accuracy   : 0.4465  | Precision : 0.4922
Recall     : 0.4465  | F1 Score  : 0.4506

[EXP04_ResNet50_CBAM | fold 4] Epoch 13/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.8795 | Val Loss  : 2.4238
Accuracy   : 0.4680  | Precision : 0.5173
Recall     : 0.4680  | F1 Score  : 0.4718
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.4718)

[EXP04_ResNet50_CBAM | fold 4] Epoch 14/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.63it/s]

Train Loss : 1.8228 | Val Loss  : 2.4133
Accuracy   : 0.4732  | Precision : 0.5267
Recall     : 0.4732  | F1 Score  : 0.4785
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.4785)

[EXP04_ResNet50_CBAM | fold 4] Epoch 15/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.7666 | Val Loss  : 2.3816
Accuracy   : 0.4960  | Precision : 0.5400
Recall     : 0.4960  | F1 Score  : 0.5040
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.5040)

[EXP04_ResNet50_CBAM | fold 4] Epoch 16/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.7183 | Val Loss  : 2.3635
Accuracy   : 0.5005  | Precision : 0.5362
Recall     : 0.5005  | F1 Score  : 0.5046
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.5046)

[EXP04_ResNet50_CBAM | fold 4] Epoch 17/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 1.6709 | Val Loss  : 2.3590
Accuracy   : 0.4976  | Precision : 0.5388
Recall     : 0.4976  | F1 Score  : 0.5015

[EXP04_ResNet50_CBAM | fold 4] Epoch 18/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:57<00:00,  2.19it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.68it/s]

Train Loss : 1.6165 | Val Loss  : 2.3557
Accuracy   : 0.4995  | Precision : 0.5360
Recall     : 0.4995  | F1 Score  : 0.5039

[EXP04_ResNet50_CBAM | fold 4] Epoch 19/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.5748 | Val Loss  : 2.3539
Accuracy   : 0.5014  | Precision : 0.5523
Recall     : 0.5014  | F1 Score  : 0.5087
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.5087)

[EXP04_ResNet50_CBAM | fold 4] Epoch 20/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.5335 | Val Loss  : 2.3311
Accuracy   : 0.5124  | Precision : 0.5504
Recall     : 0.5124  | F1 Score  : 0.5187
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.5187)

[EXP04_ResNet50_CBAM | fold 4] Epoch 21/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.4953 | Val Loss  : 2.3386
Accuracy   : 0.5127  | Precision : 0.5516
Recall     : 0.5127  | F1 Score  : 0.5175

[EXP04_ResNet50_CBAM | fold 4] Epoch 22/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.61it/s]

Train Loss : 1.4509 | Val Loss  : 2.3331
Accuracy   : 0.5249  | Precision : 0.5679
Recall     : 0.5249  | F1 Score  : 0.5310
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.5310)

[EXP04_ResNet50_CBAM | fold 4] Epoch 23/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.4140 | Val Loss  : 2.3136
Accuracy   : 0.5339  | Precision : 0.5625
Recall     : 0.5339  | F1 Score  : 0.5375
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.5375)

[EXP04_ResNet50_CBAM | fold 4] Epoch 24/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.3897 | Val Loss  : 2.3053
Accuracy   : 0.5349  | Precision : 0.5692
Recall     : 0.5349  | F1 Score  : 0.5401
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.5401)

[EXP04_ResNet50_CBAM | fold 4] Epoch 25/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.3566 | Val Loss  : 2.3195
Accuracy   : 0.5301  | Precision : 0.5624
Recall     : 0.5301  | F1 Score  : 0.5351

[EXP04_ResNet50_CBAM | fold 4] Epoch 26/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.3321 | Val Loss  : 2.3117
Accuracy   : 0.5362  | Precision : 0.5688
Recall     : 0.5362  | F1 Score  : 0.5410
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.5410)

[EXP04_ResNet50_CBAM | fold 4] Epoch 27/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 1.2954 | Val Loss  : 2.2749
Accuracy   : 0.5471  | Precision : 0.5729
Recall     : 0.5471  | F1 Score  : 0.5492
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.5492)

[EXP04_ResNet50_CBAM | fold 4] Epoch 28/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.22it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 1.2745 | Val Loss  : 2.2987
Accuracy   : 0.5464  | Precision : 0.5747
Recall     : 0.5464  | F1 Score  : 0.5522
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.5522)

[EXP04_ResNet50_CBAM | fold 4] Epoch 29/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.22it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 1.2567 | Val Loss  : 2.2957
Accuracy   : 0.5403  | Precision : 0.5723
Recall     : 0.5403  | F1 Score  : 0.5457

[EXP04_ResNet50_CBAM | fold 4] Epoch 30/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.22it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.2381 | Val Loss  : 2.2669
Accuracy   : 0.5500  | Precision : 0.5715
Recall     : 0.5500  | F1 Score  : 0.5526
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.5526)

[EXP04_ResNet50_CBAM | fold 4] Epoch 31/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.2125 | Val Loss  : 2.2639
Accuracy   : 0.5497  | Precision : 0.5675
Recall     : 0.5497  | F1 Score  : 0.5520

[EXP04_ResNet50_CBAM | fold 4] Epoch 32/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.1877 | Val Loss  : 2.2655
Accuracy   : 0.5535  | Precision : 0.5777
Recall     : 0.5535  | F1 Score  : 0.5571
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.5571)

[EXP04_ResNet50_CBAM | fold 4] Epoch 33/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.1794 | Val Loss  : 2.2603
Accuracy   : 0.5529  | Precision : 0.5774
Recall     : 0.5529  | F1 Score  : 0.5578
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.5578)

[EXP04_ResNet50_CBAM | fold 4] Epoch 34/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 1.1708 | Val Loss  : 2.2369
Accuracy   : 0.5731  | Precision : 0.5866
Recall     : 0.5731  | F1 Score  : 0.5744
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.5744)

[EXP04_ResNet50_CBAM | fold 4] Epoch 35/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.68it/s]

Train Loss : 1.1449 | Val Loss  : 2.2456
Accuracy   : 0.5632  | Precision : 0.5824
Recall     : 0.5632  | F1 Score  : 0.5672

[EXP04_ResNet50_CBAM | fold 4] Epoch 36/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.1323 | Val Loss  : 2.2287
Accuracy   : 0.5744  | Precision : 0.5834
Recall     : 0.5744  | F1 Score  : 0.5758
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.5758)

[EXP04_ResNet50_CBAM | fold 4] Epoch 37/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.69it/s]

Train Loss : 1.1193 | Val Loss  : 2.2682
Accuracy   : 0.5635  | Precision : 0.5782
Recall     : 0.5635  | F1 Score  : 0.5659

[EXP04_ResNet50_CBAM | fold 4] Epoch 38/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 1.0973 | Val Loss  : 2.2350
Accuracy   : 0.5706  | Precision : 0.5796
Recall     : 0.5706  | F1 Score  : 0.5718

[EXP04_ResNet50_CBAM | fold 4] Epoch 39/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.22it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 1.0881 | Val Loss  : 2.2321
Accuracy   : 0.5824  | Precision : 0.5930
Recall     : 0.5824  | F1 Score  : 0.5839
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.5839)

[EXP04_ResNet50_CBAM | fold 4] Epoch 40/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.0768 | Val Loss  : 2.2363
Accuracy   : 0.5837  | Precision : 0.5976
Recall     : 0.5837  | F1 Score  : 0.5865
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.5865)

[EXP04_ResNet50_CBAM | fold 4] Epoch 41/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 1.0625 | Val Loss  : 2.2429
Accuracy   : 0.5738  | Precision : 0.5887
Recall     : 0.5738  | F1 Score  : 0.5774

[EXP04_ResNet50_CBAM | fold 4] Epoch 42/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 1.0654 | Val Loss  : 2.2454
Accuracy   : 0.5789  | Precision : 0.5875
Recall     : 0.5789  | F1 Score  : 0.5793

[EXP04_ResNet50_CBAM | fold 4] Epoch 43/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.0548 | Val Loss  : 2.2278
Accuracy   : 0.5831  | Precision : 0.5975
Recall     : 0.5831  | F1 Score  : 0.5866
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.5866)

[EXP04_ResNet50_CBAM | fold 4] Epoch 44/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 1.0405 | Val Loss  : 2.2087
Accuracy   : 0.5857  | Precision : 0.5977
Recall     : 0.5857  | F1 Score  : 0.5874
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.5874)

[EXP04_ResNet50_CBAM | fold 4] Epoch 45/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.0311 | Val Loss  : 2.2171
Accuracy   : 0.5882  | Precision : 0.5985
Recall     : 0.5882  | F1 Score  : 0.5907
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.5907)

[EXP04_ResNet50_CBAM | fold 4] Epoch 46/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.0120 | Val Loss  : 2.2150
Accuracy   : 0.5902  | Precision : 0.5979
Recall     : 0.5902  | F1 Score  : 0.5909
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.5909)

[EXP04_ResNet50_CBAM | fold 4] Epoch 47/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 1.0103 | Val Loss  : 2.2030
Accuracy   : 0.5902  | Precision : 0.5965
Recall     : 0.5902  | F1 Score  : 0.5914
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.5914)

[EXP04_ResNet50_CBAM | fold 4] Epoch 48/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.0090 | Val Loss  : 2.2122
Accuracy   : 0.6001  | Precision : 0.6095
Recall     : 0.6001  | F1 Score  : 0.6008
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold4.pth (F1: 0.6008)

[EXP04_ResNet50_CBAM | fold 4] Epoch 49/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.0008 | Val Loss  : 2.2149
Accuracy   : 0.5921  | Precision : 0.6041
Recall     : 0.5921  | F1 Score  : 0.5946

[EXP04_ResNet50_CBAM | fold 4] Epoch 50/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 0.9964 | Val Loss  : 2.2162
Accuracy   : 0.5988  | Precision : 0.6081
Recall     : 0.5988  | F1 Score  : 0.6007

C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:54: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler()

  [CBAM] Disisipkan ke 16 Bottleneck block (layer1-4).
  [EXP04_ResNet50_CBAM] Trainable params: 25,846,327 / 26,071,671 (99.1%)

[EXP04_ResNet50_CBAM | fold 5] Epoch 1/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 3.1524 | Val Loss  : 3.1435
Accuracy   : 0.1723  | Precision : 0.2262
Recall     : 0.1723  | F1 Score  : 0.1410
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.1410)

[EXP04_ResNet50_CBAM | fold 5] Epoch 2/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 2.9016 | Val Loss  : 2.9594
Accuracy   : 0.2533  | Precision : 0.3035
Recall     : 0.2533  | F1 Score  : 0.2320
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.2320)

[EXP04_ResNet50_CBAM | fold 5] Epoch 3/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:57<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.68it/s]

Train Loss : 2.7301 | Val Loss  : 2.8455
Accuracy   : 0.3089  | Precision : 0.3567
Recall     : 0.3089  | F1 Score  : 0.2993
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.2993)

[EXP04_ResNet50_CBAM | fold 5] Epoch 4/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:57<00:00,  2.19it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 2.6066 | Val Loss  : 2.7747
Accuracy   : 0.3295  | Precision : 0.3819
Recall     : 0.3295  | F1 Score  : 0.3198
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.3198)

[EXP04_ResNet50_CBAM | fold 5] Epoch 5/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:57<00:00,  2.19it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 2.5019 | Val Loss  : 2.7550
Accuracy   : 0.3481  | Precision : 0.4166
Recall     : 0.3481  | F1 Score  : 0.3411
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.3411)

[EXP04_ResNet50_CBAM | fold 5] Epoch 6/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:57<00:00,  2.19it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 2.4126 | Val Loss  : 2.6710
Accuracy   : 0.3668  | Precision : 0.4277
Recall     : 0.3668  | F1 Score  : 0.3646
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.3646)

[EXP04_ResNet50_CBAM | fold 5] Epoch 7/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 2.3244 | Val Loss  : 2.6197
Accuracy   : 0.3857  | Precision : 0.4526
Recall     : 0.3857  | F1 Score  : 0.3879
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.3879)

[EXP04_ResNet50_CBAM | fold 5] Epoch 8/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 2.2391 | Val Loss  : 2.5811
Accuracy   : 0.3995  | Precision : 0.4662
Recall     : 0.3995  | F1 Score  : 0.4022
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.4022)

[EXP04_ResNet50_CBAM | fold 5] Epoch 9/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 2.1534 | Val Loss  : 2.5327
Accuracy   : 0.4137  | Precision : 0.4646
Recall     : 0.4137  | F1 Score  : 0.4162
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.4162)

[EXP04_ResNet50_CBAM | fold 5] Epoch 10/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 2.0874 | Val Loss  : 2.4765
Accuracy   : 0.4417  | Precision : 0.4814
Recall     : 0.4417  | F1 Score  : 0.4425
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.4425)

[EXP04_ResNet50_CBAM | fold 5] Epoch 11/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 2.0167 | Val Loss  : 2.4897
Accuracy   : 0.4449  | Precision : 0.5002
Recall     : 0.4449  | F1 Score  : 0.4457
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.4457)

[EXP04_ResNet50_CBAM | fold 5] Epoch 12/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.9574 | Val Loss  : 2.4706
Accuracy   : 0.4536  | Precision : 0.5165
Recall     : 0.4536  | F1 Score  : 0.4588
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.4588)

[EXP04_ResNet50_CBAM | fold 5] Epoch 13/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:43<00:00,  2.38it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.8925 | Val Loss  : 2.4358
Accuracy   : 0.4584  | Precision : 0.5084
Recall     : 0.4584  | F1 Score  : 0.4617
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.4617)

[EXP04_ResNet50_CBAM | fold 5] Epoch 14/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 1.8320 | Val Loss  : 2.4381
Accuracy   : 0.4622  | Precision : 0.5107
Recall     : 0.4622  | F1 Score  : 0.4677
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.4677)

[EXP04_ResNet50_CBAM | fold 5] Epoch 15/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.63it/s]

Train Loss : 1.7755 | Val Loss  : 2.3855
Accuracy   : 0.4841  | Precision : 0.5201
Recall     : 0.4841  | F1 Score  : 0.4895
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.4895)

[EXP04_ResNet50_CBAM | fold 5] Epoch 16/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.7136 | Val Loss  : 2.4006
Accuracy   : 0.4924  | Precision : 0.5345
Recall     : 0.4924  | F1 Score  : 0.4985
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.4985)

[EXP04_ResNet50_CBAM | fold 5] Epoch 17/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.62it/s]

Train Loss : 1.6760 | Val Loss  : 2.3910
Accuracy   : 0.4950  | Precision : 0.5362
Recall     : 0.4950  | F1 Score  : 0.4994
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.4994)

[EXP04_ResNet50_CBAM | fold 5] Epoch 18/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.6154 | Val Loss  : 2.4164
Accuracy   : 0.4966  | Precision : 0.5408
Recall     : 0.4966  | F1 Score  : 0.4990

[EXP04_ResNet50_CBAM | fold 5] Epoch 19/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.63it/s]

Train Loss : 1.5753 | Val Loss  : 2.3691
Accuracy   : 0.5076  | Precision : 0.5460
Recall     : 0.5076  | F1 Score  : 0.5131
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.5131)

[EXP04_ResNet50_CBAM | fold 5] Epoch 20/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.61it/s]

Train Loss : 1.5362 | Val Loss  : 2.3637
Accuracy   : 0.5127  | Precision : 0.5542
Recall     : 0.5127  | F1 Score  : 0.5193
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.5193)

[EXP04_ResNet50_CBAM | fold 5] Epoch 21/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:58<00:00,  2.19it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.4872 | Val Loss  : 2.3772
Accuracy   : 0.5088  | Precision : 0.5442
Recall     : 0.5088  | F1 Score  : 0.5114

[EXP04_ResNet50_CBAM | fold 5] Epoch 22/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:57<00:00,  2.19it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.4585 | Val Loss  : 2.3682
Accuracy   : 0.5104  | Precision : 0.5580
Recall     : 0.5104  | F1 Score  : 0.5153

[EXP04_ResNet50_CBAM | fold 5] Epoch 23/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.4225 | Val Loss  : 2.3384
Accuracy   : 0.5336  | Precision : 0.5612
Recall     : 0.5336  | F1 Score  : 0.5377
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.5377)

[EXP04_ResNet50_CBAM | fold 5] Epoch 24/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.3884 | Val Loss  : 2.3475
Accuracy   : 0.5374  | Precision : 0.5675
Recall     : 0.5374  | F1 Score  : 0.5418
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.5418)

[EXP04_ResNet50_CBAM | fold 5] Epoch 25/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.3495 | Val Loss  : 2.3477
Accuracy   : 0.5358  | Precision : 0.5659
Recall     : 0.5358  | F1 Score  : 0.5405

[EXP04_ResNet50_CBAM | fold 5] Epoch 26/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.3303 | Val Loss  : 2.3173
Accuracy   : 0.5384  | Precision : 0.5631
Recall     : 0.5384  | F1 Score  : 0.5407

[EXP04_ResNet50_CBAM | fold 5] Epoch 27/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.3021 | Val Loss  : 2.2967
Accuracy   : 0.5558  | Precision : 0.5791
Recall     : 0.5558  | F1 Score  : 0.5610
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.5610)

[EXP04_ResNet50_CBAM | fold 5] Epoch 28/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.2778 | Val Loss  : 2.3414
Accuracy   : 0.5342  | Precision : 0.5630
Recall     : 0.5342  | F1 Score  : 0.5376

[EXP04_ResNet50_CBAM | fold 5] Epoch 29/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.2607 | Val Loss  : 2.3022
Accuracy   : 0.5497  | Precision : 0.5789
Recall     : 0.5497  | F1 Score  : 0.5548

[EXP04_ResNet50_CBAM | fold 5] Epoch 30/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.2359 | Val Loss  : 2.3039
Accuracy   : 0.5554  | Precision : 0.5763
Recall     : 0.5554  | F1 Score  : 0.5561

[EXP04_ResNet50_CBAM | fold 5] Epoch 31/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.1932 | Val Loss  : 2.2792
Accuracy   : 0.5683  | Precision : 0.5840
Recall     : 0.5683  | F1 Score  : 0.5696
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.5696)

[EXP04_ResNet50_CBAM | fold 5] Epoch 32/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.1720 | Val Loss  : 2.2768
Accuracy   : 0.5693  | Precision : 0.5852
Recall     : 0.5693  | F1 Score  : 0.5711
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.5711)

[EXP04_ResNet50_CBAM | fold 5] Epoch 33/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.22it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.68it/s]

Train Loss : 1.1674 | Val Loss  : 2.2739
Accuracy   : 0.5648  | Precision : 0.5813
Recall     : 0.5648  | F1 Score  : 0.5673

[EXP04_ResNet50_CBAM | fold 5] Epoch 34/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.1594 | Val Loss  : 2.2555
Accuracy   : 0.5731  | Precision : 0.5866
Recall     : 0.5731  | F1 Score  : 0.5741
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.5741)

[EXP04_ResNet50_CBAM | fold 5] Epoch 35/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.1557 | Val Loss  : 2.2654
Accuracy   : 0.5683  | Precision : 0.5843
Recall     : 0.5683  | F1 Score  : 0.5704

[EXP04_ResNet50_CBAM | fold 5] Epoch 36/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.1445 | Val Loss  : 2.2496
Accuracy   : 0.5757  | Precision : 0.5889
Recall     : 0.5757  | F1 Score  : 0.5774
  ✓ Model saved → outputs/EXP04_ResNet50_CBAM_fold5.pth (F1: 0.5774)

[EXP04_ResNet50_CBAM | fold 5] Epoch 37/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.1435 | Val Loss  : 2.2697
Accuracy   : 0.5706  | Precision : 0.5882
Recall     : 0.5706  | F1 Score  : 0.5715

[EXP04_ResNet50_CBAM | fold 5] Epoch 38/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.20it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 1.1430 | Val Loss  : 2.2604
Accuracy   : 0.5625  | Precision : 0.5785
Recall     : 0.5625  | F1 Score  : 0.5639

[EXP04_ResNet50_CBAM | fold 5] Epoch 39/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.63it/s]

Train Loss : 1.1424 | Val Loss  : 2.2498
Accuracy   : 0.5696  | Precision : 0.5813
Recall     : 0.5696  | F1 Score  : 0.5703

[EXP04_ResNet50_CBAM | fold 5] Epoch 40/50 (LR: 1.00e-06)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.1300 | Val Loss  : 2.2540
Accuracy   : 0.5709  | Precision : 0.5845
Recall     : 0.5709  | F1 Score  : 0.5717

[EXP04_ResNet50_CBAM | fold 5] Epoch 41/50 (LR: 1.00e-06)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.1269 | Val Loss  : 2.2450
Accuracy   : 0.5760  | Precision : 0.5867
Recall     : 0.5760  | F1 Score  : 0.5767

[EXP04_ResNet50_CBAM | fold 5] Epoch 42/50 (LR: 1.00e-06)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:56<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.1302 | Val Loss  : 2.2643
Accuracy   : 0.5648  | Precision : 0.5802
Recall     : 0.5648  | F1 Score  : 0.5658

[EXP04_ResNet50_CBAM | fold 5] Epoch 43/50 (LR: 1.00e-07)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.21it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.1307 | Val Loss  : 2.2601
Accuracy   : 0.5696  | Precision : 0.5825
Recall     : 0.5696  | F1 Score  : 0.5706
Early Stopping Triggered

,arch,fold,train_loss,val_loss,accuracy,precision,recall,f1,model_path
0,EXP04_ResNet50_CBAM,1,1.003737,2.203251,0.589974,0.594686,0.589974,0.589395,outputs/EXP04_ResNet50_CBAM_fold1.pth
1,EXP04_ResNet50_CBAM,2,1.153994,2.256412,0.560090,0.572952,0.560090,0.561720,outputs/EXP04_ResNet50_CBAM_fold2.pth
2,EXP04_ResNet50_CBAM,3,1.058845,2.287378,0.561877,0.571653,0.561877,0.563868,outputs/EXP04_ResNet50_CBAM_fold3.pth
3,EXP04_ResNet50_CBAM,4,1.008970,2.212225,0.600129,0.609496,0.600129,0.600760,outputs/EXP04_ResNet50_CBAM_fold4.pth
4,EXP04_ResNet50_CBAM,5,1.144472,2.249579,0.575699,0.588896,0.575699,0.577367,outputs/EXP04_ResNet50_CBAM_fold5.pth

## 8. Rekap 5-Fold

In [9]:
# PERBAIKAN: format summary disamakan persis dengan ViT exp01 -- laporkan
# Mean ± Std untuk keempat metrik (Accuracy, Precision, Recall, F1), bukan
# cuma F1 saja.
print("\n" + "="*50)
print(f"  FINAL RESULT — ALL FOLDS ({ARCH_KEY})")
print("="*50)
print(f"Mean Accuracy  : {results_df['accuracy'].mean():.4f} ± {results_df['accuracy'].std():.4f}")
print(f"Mean Precision : {results_df['precision'].mean():.4f} ± {results_df['precision'].std():.4f}")
print(f"Mean Recall    : {results_df['recall'].mean():.4f} ± {results_df['recall'].std():.4f}")
print(f"Mean F1 Score  : {results_df['f1'].mean():.4f} ± {results_df['f1'].std():.4f}")

# ── WANDB LOG SUMMARY (format sama seperti ViT exp01) ─────────────────────────
try:
    run.log({
        "summary/mean_accuracy"  : results_df["accuracy"].mean(),
        "summary/mean_precision" : results_df["precision"].mean(),
        "summary/mean_recall"    : results_df["recall"].mean(),
        "summary/mean_f1"        : results_df["f1"].mean(),
        "summary/std_accuracy"   : results_df["accuracy"].std(),
        "summary/std_precision"  : results_df["precision"].std(),
        "summary/std_recall"     : results_df["recall"].std(),
        "summary/std_f1"         : results_df["f1"].std(),
    })
except Exception as e:
    print(f"  ⚠ W&B log summary gagal (dilewati): {e}")

# ── GRAFIK: 4 metrik per fold (bukan cuma F1) ──────────────────────────────────
fig, axes = plt.subplots(1, 4, figsize=(20, 4))
metric_cols = ["accuracy", "precision", "recall", "f1"]
metric_titles = ["Accuracy", "Precision", "Recall", "F1-Score"]

for ax, col, title in zip(axes, metric_cols, metric_titles):
    ax.bar(results_df["fold"].astype(str), results_df[col], color="#1f3a5f")
    ax.axhline(results_df[col].mean(), color="red", linestyle="--", label=f"Mean = {results_df[col].mean():.3f}")
    ax.set_xlabel("Fold"); ax.set_ylabel(f"Val {title}")
    ax.set_title(f"{ARCH_KEY} — {title} per Fold")
    ax.set_ylim(0, 1); ax.legend()

plt.tight_layout()
plt.savefig(f"{OUTPUT_DIR}/{ARCH_KEY}_fold_metrics_chart.png", dpi=200)
plt.show()

results_df.to_csv(f"{OUTPUT_DIR}/{ARCH_KEY}_all_folds.csv", index=False)

==================================================
  FINAL RESULT — ALL FOLDS (EXP04_ResNet50_CBAM)
==================================================
Mean Accuracy  : 0.5776 ± 0.0175
Mean Precision : 0.5875 ± 0.0158
Mean Recall    : 0.5776 ± 0.0175
Mean F1 Score  : 0.5786 ± 0.0167
  ⚠ W&B log summary gagal (dilewati): Run (7quzcmr1) is finished. The call to `log` will be ignored. Please make sure that you are using an active run.

C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\1248490208.py:41: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## 9. Test Evaluation (Fold Terbaik)

In [10]:
best_fold_result = max(all_results, key=lambda r: r["f1"])
best_overall_path = best_fold_result["model_path"]
print(f"Fold terbaik    : {best_fold_result['fold']}")
print(f"Checkpoint      : {best_overall_path}")
print(f"Val F1 terbaik  : {best_fold_result['f1']:.4f}")

_, eval_tf = get_transforms(IMG_SIZE)
test_dataset = datasets.ImageFolder(TEST_DIR, transform=eval_tf)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

model = build_model(num_classes)
model = model.to(device)
checkpoint = torch.load(best_overall_path, map_location=device)
model.load_state_dict(checkpoint["model_state_dict"])
model.eval()

y_true, y_pred = [], []
with torch.no_grad():
    for imgs, tgts in tqdm(test_loader, desc="Test"):
        imgs = imgs.to(device)
        with autocast():
            out = model(imgs)
        y_true.extend(tgts.numpy())
        y_pred.extend(out.argmax(1).cpu().numpy())

acc = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average="weighted", zero_division=0)
recall = recall_score(y_true, y_pred, average="weighted", zero_division=0)
f1 = f1_score(y_true, y_pred, average="weighted", zero_division=0)

print(f"Accuracy  : {acc:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1-Score  : {f1:.4f}")
print()
print(classification_report(y_true, y_pred, target_names=classes, zero_division=0))

cm = confusion_matrix(y_true, y_pred)
fig, ax = plt.subplots(figsize=(15, 15))
ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=classes).plot(cmap="Blues", ax=ax, xticks_rotation=90)
plt.tight_layout()
plt.savefig(f"{OUTPUT_DIR}/{ARCH_KEY}_Test_Confusion_Matrix.png", dpi=150, bbox_inches="tight")
plt.show()

test_summary_df = pd.DataFrame([{
    "arch": ARCH_KEY, "Accuracy": acc, "Precision": precision, "Recall": recall, "F1": f1
}])
test_summary_df.to_csv(f"{OUTPUT_DIR}/{ARCH_KEY}_Test_Summary.csv", index=False)
print(f"\n✓ Test summary disimpan -> {OUTPUT_DIR}/{ARCH_KEY}_Test_Summary.csv")

Fold terbaik    : 4
Checkpoint      : outputs/EXP04_ResNet50_CBAM_fold4.pth
Val F1 terbaik  : 0.6008
  [CBAM] Disisipkan ke 16 Bottleneck block (layer1-4).

Test:   0%|          | 0/126 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3000596476.py:21: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Test: 100%|██████████| 126/126 [00:53<00:00,  2.33it/s]

Accuracy  : 0.6072
Precision : 0.6202
Recall    : 0.6072
F1-Score  : 0.6083

                                                                    precision    recall  f1-score   support

                                           Acne and Rosacea Photos       0.77      0.90      0.83       312
Actinic Keratosis Basal Cell Carcinoma and other Malignant Lesions       0.70      0.59      0.64       288
                                          Atopic Dermatitis Photos       0.50      0.58      0.54       123
                                            Bullous Disease Photos       0.54      0.48      0.51       113
                Cellulitis Impetigo and other Bacterial Infections       0.32      0.51      0.39        73
                                                     Eczema Photos       0.57      0.66      0.61       309
                                      Exanthems and Drug Eruptions       0.42      0.59      0.49       101
                 Hair Loss Photos Alopecia and other Hair Diseases       0.49      0.72      0.58        60
                                  Herpes HPV and other STDs Photos       0.45      0.48      0.47       102
                      Light Diseases and Disorders of Pigmentation       0.53      0.43      0.47       143
                        Lupus and other Connective Tissue diseases       0.63      0.45      0.52       105
                               Melanoma Skin Cancer Nevi and Moles       0.71      0.72      0.71       116
                                Nail Fungus and other Nail Disease       0.83      0.76      0.79       261
                    Poison Ivy Photos and other Contact Dermatitis       0.46      0.57      0.51        65
             Psoriasis pictures Lichen Planus and related diseases       0.65      0.50      0.57       352
             Scabies Lyme Disease and other Infestations and Bites       0.49      0.45      0.47       108
                      Seborrheic Keratoses and other Benign Tumors       0.67      0.59      0.63       343
                                                  Systemic Disease       0.44      0.62      0.52       152
            Tinea Ringworm Candidiasis and other Fungal Infections       0.71      0.58      0.64       325
                                                   Urticaria Hives       0.57      0.64      0.60        53
                                                   Vascular Tumors       0.63      0.59      0.61       121
                                                 Vasculitis Photos       0.50      0.63      0.56       105
                        Warts Molluscum and other Viral Infections       0.60      0.57      0.58       272

                                                          accuracy                           0.61      4002
                                                         macro avg       0.57      0.59      0.58      4002
                                                      weighted avg       0.62      0.61      0.61      4002


✓ Test summary disimpan -> outputs/EXP04_ResNet50_CBAM_Test_Summary.csv

C:\Users\UNIDA\AppData\Local\Temp\ipykernel_15268\3000596476.py:43: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## 9b. Per-Image Test Prediction (True/False per gambar)

Dump terpisah dari summary agregat di atas -- CSV ini berisi 1 baris per gambar test (filepath, label asli, label prediksi, benar/salah), supaya bisa dicek manual gambar mana saja yang salah diklasifikasikan (misal untuk lampiran/analisis kualitatif di skripsi).

In [11]:
# PERBAIKAN: dump prediksi per-gambar (bukan cuma summary agregat) -- pakai
# y_true/y_pred/test_dataset yang sudah dihitung di cell sebelumnya (state Jupyter
# masih ada, tidak perlu re-run inference).
test_filepaths = [fp for fp, _ in test_dataset.samples]   # urutan sama dgn y_true/y_pred (shuffle=False)
assert len(test_filepaths) == len(y_true) == len(y_pred), "Jumlah filepath tidak sama dengan jumlah prediksi!"

per_image_df = pd.DataFrame({
    "filepath": test_filepaths,
    "true_label": [classes[t] for t in y_true],
    "pred_label": [classes[p] for p in y_pred],
    "correct": [t == p for t, p in zip(y_true, y_pred)],
})

per_image_csv_path = f"{OUTPUT_DIR}/{ARCH_KEY}_Test_PerImage_Predictions.csv"
per_image_df.to_csv(per_image_csv_path, index=False)

n_correct = int(per_image_df["correct"].sum())
n_total = len(per_image_df)
print(f"✓ Per-image prediction disimpan -> {per_image_csv_path}")
print(f"  Benar : {n_correct} / {n_total} ({100 * n_correct / n_total:.2f}%)")
print(f"  Salah : {n_total - n_correct} / {n_total} ({100 * (n_total - n_correct) / n_total:.2f}%)")

# Preview baris yang salah -- 10 contoh pertama, berguna buat dicek manual
per_image_df[~per_image_df["correct"]].head(10)

✓ Per-image prediction disimpan -> outputs/EXP04_ResNet50_CBAM_Test_PerImage_Predictions.csv
  Benar : 2430 / 4002 (60.72%)
  Salah : 1572 / 4002 (39.28%)

,filepath,true_label,pred_label,correct
5,D:\Devianest_SkripsiTest\test\Acne and Rosacea...,Acne and Rosacea Photos,Tinea Ringworm Candidiasis and other Fungal In...,False
14,D:\Devianest_SkripsiTest\test\Acne and Rosacea...,Acne and Rosacea Photos,Melanoma Skin Cancer Nevi and Moles,False
17,D:\Devianest_SkripsiTest\test\Acne and Rosacea...,Acne and Rosacea Photos,Warts Molluscum and other Viral Infections,False
55,D:\Devianest_SkripsiTest\test\Acne and Rosacea...,Acne and Rosacea Photos,Atopic Dermatitis Photos,False
66,D:\Devianest_SkripsiTest\test\Acne and Rosacea...,Acne and Rosacea Photos,Tinea Ringworm Candidiasis and other Fungal In...,False
73,D:\Devianest_SkripsiTest\test\Acne and Rosacea...,Acne and Rosacea Photos,Actinic Keratosis Basal Cell Carcinoma and oth...,False
80,D:\Devianest_SkripsiTest\test\Acne and Rosacea...,Acne and Rosacea Photos,Bullous Disease Photos,False
83,D:\Devianest_SkripsiTest\test\Acne and Rosacea...,Acne and Rosacea Photos,Exanthems and Drug Eruptions,False
90,D:\Devianest_SkripsiTest\test\Acne and Rosacea...,Acne and Rosacea Photos,Atopic Dermatitis Photos,False
95,D:\Devianest_SkripsiTest\test\Acne and Rosacea...,Acne and Rosacea Photos,Atopic Dermatitis Photos,False

## Catatan

- **Isolasi variabel**: satu-satunya perbedaan dari `exp01-cnn-baseline.ipynb` adalah `USE_CBAM=True` + penyisipan `CBAMAttention` di tiap Bottleneck (`layer1-4`). Semua hyperparameter lain (LR, WEIGHT_DECAY, DROPOUT, UNFREEZE_PATTERNS, scheduler, augmentasi, seed) identik -- supaya selisih F1 vs EXP01 bisa diatribusikan murni ke CBAM.
- **Titik insersi**: slot `.se` bawaan timm Bottleneck (dipanggil setelah `conv3+bn3`, sebelum residual add) -- bukan hack, ini memang disediakan timm untuk attention module CNN-native (SE-Net dkk), jadi tidak perlu re-write forward pass ResNet secara manual.
- **CBAM = 2 submodul sequential**: channel attention (avg-pool + max-pool -> shared MLP -> sigmoid) diterapkan dulu ke input, baru spatial attention (avg + max sepanjang channel -> conv 7x7 -> sigmoid) diterapkan ke hasilnya. Ini beda dari ECA yang cuma 1 submodul channel attention (tanpa max-pool, tanpa spatial attention).
- **CBAM selalu trainable**: meskipun `layer1` di luar `UNFREEZE_PATTERNS` (backbone-nya beku), modul CBAM di `layer1` tetap dilatih -- karena bobotnya random-init, bukan pretrained. Ini prinsip yang sama dengan versi ECA.
- **Checkpoint & test evaluation**: karena `build_model()` sudah otomatis memanggil `inject_cbam()` saat `USE_CBAM=True`, sel Test Evaluation (§9) TIDAK perlu perubahan apa pun -- `build_model(num_classes)` di situ akan otomatis merekonstruksi arsitektur ber-CBAM sebelum `load_state_dict`, jadi key-nya pasti cocok dengan checkpoint hasil training.
- Checkpoint format & kolom `results_df` tetap sama seperti EXP01 -- tinggal `pd.concat()` untuk rekap akhir baseline vs ECA vs CBAM.