# **ResNet50 — EXP02 ECA (Efficient Channel Attention)**

Versi ECA dari `exp01-cnn-baseline.ipynb` (ResNet50 Baseline). Mengikuti prinsip isolasi yang sama seperti `exp02-vit-base-16-eca.ipynb` (ViT track): **SEMUA hyperparameter identik dengan baseline**, satu-satunya perubahan adalah penyisipan modul ECA -- supaya efek ECA terhadap performa bisa diatribusikan murni ke modul attention-nya, bukan ke confound lain.

**Titik insersi ECA (beda dengan ViT):**
- ViT (exp02 ViT) cuma punya 1 titik insersi valid: `patch_embed` (satu-satunya representasi 4D sebelum jadi token sequence).
- ResNet punya banyak feature map 4D di sepanjang backbone -- ECA disisipkan di slot `.se` yang memang disediakan timm di setiap **Bottleneck block** (persis setelah `conv3`+`bn3`, sebelum residual add), sesuai desain ECA-Net asli (Wang et al., 2020) yang memasang di seluruh backbone CNN, bukan cuma 1 titik.

## 1. Import & Setup

In [1]:
# 1. Install & Import
import os, copy, random
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
# PERBAIKAN (dari ViT exp01): AMP -- sebagian besar operasi forward jalan di
# float16 (lebih cepat & hemat VRAM di GPU RTX/Tensor Core), backward/update tetap
# presisi lewat GradScaler. Belum ada di kedua notebook ResNet sebelumnya.
from torch.cuda.amp import autocast, GradScaler

from torchvision import transforms, datasets
from PIL import Image
from tqdm import tqdm

import timm   # PERBAIKAN: torchvision.models -> timm, biar 1 API dipakai semua arsitektur (ResNet18/50, EfficientNet, ViT, dst)
import wandb

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, recall_score,
    classification_report, confusion_matrix, ConfusionMatrixDisplay
)

# Ambil API key dari environment variable
wandb_api_key = os.getenv("WANDB_API_KEY")

os.environ["TORCH_HOME"] = "D:/cache/torch"
os.environ["HF_HOME"] = "D:/cache/huggingface"

os.environ["WANDB_DIR"] = "D:/cache/wandb"
os.environ["WANDB_CACHE_DIR"] = "D:/cache/wandb_cache"

os.environ["TEMP"] = "D:/cache/temp"
os.environ["TMP"] = "D:/cache/temp"

os.environ["CUDA_CACHE_PATH"] = "D:/cache/cuda"

print(os.getcwd())

# Login ke wandb
wandb.login(key=wandb_api_key)

# PERBAIKAN (dari ViT exp01 + ResNet18): seed eksplisit -- EXP01-03 ResNet50 lama
# cuma nge-seed StratifiedKFold, TIDAK nge-seed init bobot FC head / urutan shuffle.
SEED = 42
random.seed(SEED); np.random.seed(SEED)
torch.manual_seed(SEED); torch.cuda.manual_seed_all(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# PERBAIKAN (dari ViT exp01): cudnn.benchmark auto-tune algoritma konvolusi
# tercepat untuk ukuran input yang konsisten (semua di-resize ke 224x224).
torch.backends.cudnn.benchmark = True

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from C:\Users\UNIDA\_netrc.

d:\Devianest_SkripsiTest\Code_CNN

wandb: Currently logged in as: devianestnarendra to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

Device: cuda

## 2. Config

In [2]:
TRAIN_DIR = r"D:\Devianest_SkripsiTest\train"
TEST_DIR  = r"D:\Devianest_SkripsiTest\test"

# PERBAIKAN (VSCode lokal): ganti "/kaggle/working" -> folder "outputs" relatif
# terhadap lokasi notebook ini. os.makedirs(..., exist_ok=True) otomatis bikin
# foldernya kalau belum ada, supaya tidak error "No such file or directory"
# saat pertama kali disimpan.
OUTPUT_DIR = "outputs"
os.makedirs(OUTPUT_DIR, exist_ok=True)

ARCH_KEY  = "EXP02_ResNet50_ECA"
TIMM_NAME = "resnet50"

IMG_SIZE     = 224
BATCH_SIZE   = 32          # tetap seperti EXP01-03 (ResNet50 lebih berat dari ResNet18, batch lebih kecil)
EPOCHS       = 50
N_FOLDS      = 5
DROPOUT      = 0.3         # dipertahankan dari EXP01-03 (nilai yang sudah teruji utk ResNet50)
LR           = 1e-4        # PERBAIKAN: dipertahankan nilai ResNet (BUKAN LR ViT 3e-5) -- CNN historically
                            # lebih toleran ke LR sedikit lebih tinggi dibanding attention layer ViT yang sensitif
WEIGHT_DECAY = 1e-4         # dipertahankan nilai konvensi CNN transfer learning (bukan WD ViT 0.01)
LABEL_SMOOTHING = 0.1
EARLY_STOP_PATIENCE = 7     # PERBAIKAN: naik dari 5 -> 7 (lebih toleran sebelum berhenti)

WANDB_PROJECT = "SkinDisease-CNN"   # disamakan dengan notebook ResNet18, biar 1 project W&B

# ResNet50: unfreeze layer2/3/4 + fc -- sama scope kapasitas dengan EXP03 (untuk
# tetap bisa dibandingkan), TAPI training regime-nya sudah diperbaiki (lihat bawah).
UNFREEZE_PATTERNS = ["layer2", "layer3", "layer4", "fc"]

# PERBAIKAN (dari ViT exp01 + ResNet18): scheduler ReduceLROnPlateau disamakan
# PERSIS dengan setting yang sudah dipakai di ViT & ResNet18 -- root cause
# instabilitas ResNet50 lama adalah OneCycleLR yang di-set untuk siklus 50 epoch
# penuh, tapi EarlyStopping hampir selalu memotong training di epoch 11-22
# (SEBELUM fase anneal selesai) -- lihat diskusi sebelumnya soal Fold 4 yang
# selalu menang karena satu-satunya fold yang tidak pernah early-stop.
SCHEDULER_FACTOR    = 0.1
SCHEDULER_PATIENCE  = 2
SCHEDULER_THRESHOLD = 1e-4
SCHEDULER_MIN_LR    = 1e-7


# ── ECA (Efficient Channel Attention) ────────────────────────────────────────
# PERBAIKAN: versi ECA dari EXP01 -- SEMUA hyperparameter di atas dipertahankan
# PERSIS SAMA (LR, WEIGHT_DECAY, DROPOUT, UNFREEZE_PATTERNS, scheduler, dst) supaya
# efek ECA terisolasi (tidak ada confound lain), sama seperti prinsip exp02 ViT ECA.
USE_ECA    = True
ECA_K_SIZE = 3   # ukuran kernel conv1d ECA, k=3 default (sama seperti exp02 ViT ECA)

## 3. Dataset & Augmentasi

In [3]:
# PERBAIKAN: augmentasi disamakan PERSIS dengan versi terbaru ViT exp01 (medium,
# termasuk RandomResizedCrop) -- bukan versi ResNet18 yang belum pakai
# RandomResizedCrop. Ini penting supaya CNN dan ViT dibandingkan dengan
# preprocessing yang identik (bukan confound tambahan).
def get_transforms(img_size):
    train_tf = transforms.Compose([
        transforms.Resize((img_size, img_size)),
        transforms.RandomHorizontalFlip(),
        transforms.RandomRotation(10),
        transforms.ColorJitter(brightness=0.15, contrast=0.15, saturation=0.1),
        transforms.RandomResizedCrop(img_size, scale=(0.8, 1.0)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ])
    eval_tf = transforms.Compose([
        transforms.Resize((img_size, img_size)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ])
    return train_tf, eval_tf


classes = sorted(os.listdir(TRAIN_DIR))
class_to_idx = {c: i for i, c in enumerate(classes)}
num_classes = len(classes)

filepaths, labels = [], []
for label in classes:
    class_path = os.path.join(TRAIN_DIR, label)
    for img in os.listdir(class_path):
        filepaths.append(os.path.join(class_path, img))
        labels.append(class_to_idx[label])

print("Total Images :", len(filepaths))
print("Classes      :", num_classes)


class SkinDataset(Dataset):
    def __init__(self, filepaths, labels, transform=None):
        self.filepaths = filepaths
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return len(self.filepaths)

    def __getitem__(self, idx):
        image = Image.open(self.filepaths[idx]).convert("RGB")
        label = self.labels[idx]
        if self.transform:
            image = self.transform(image)
        return image, label

Total Images : 15557
Classes      : 23

## 4. Early Stopping (val_f1) + K-Fold

In [4]:
class EarlyStopping:
    # Kriteria val_f1 (bukan val_loss) -- konsisten dengan ViT exp01 & ResNet18:
    # lebih robust untuk data imbalanced (23 kelas DermNet) dibanding val_loss.
    def __init__(self, patience=5):
        self.patience = patience
        self.best_f1 = -np.inf
        self.counter = 0

    def step(self, val_f1):
        if val_f1 > self.best_f1:
            self.best_f1 = val_f1
            self.counter = 0
            return False
        self.counter += 1
        return self.counter >= self.patience


skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)

## 5. Model Builder + Freeze Strategy

In [5]:
# ── ECA (Efficient Channel Attention) ────────────────────────────────────────
# Sama seperti exp02-vit-base-16-eca.ipynb, tapi titik insersinya beda karena
# arsitekturnya beda:
# - ViT cuma punya 1 representasi 4D (feature map) di seluruh model, yaitu tepat
#   setelah patch_embed.proj, sebelum di-flatten jadi token sequence -- makanya
#   ECA cuma disisipkan di 1 titik itu.
# - ResNet (CNN) punya feature map 4D (B, C, H, W) di SEPANJANG backbone -- setiap
#   Bottleneck block. timm sudah menyediakan slot khusus untuk ini: atribut
#   `.se` di tiap Bottleneck (dipakai bawaan buat SE-Net-style attention),
#   dipanggil PERSIS setelah conv3+bn3, SEBELUM residual add:
#       x = self.conv3(x); x = self.bn3(x)
#       if self.se is not None: x = self.se(x)
#       ...; x += shortcut; x = self.act3(x)
#   Titik ini insersion-equivalent dengan patch_embed ViT: representasi masih
#   4D (C, H, W), belum berubah bentuk/residual.
class ECAAttention(nn.Module):
    def __init__(self, channels, k_size=3):
        super().__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.conv = nn.Conv1d(1, 1, kernel_size=k_size, padding=(k_size - 1) // 2, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        # x: (B, C, H, W)
        y = self.avg_pool(x)
        y = y.squeeze(-1).transpose(-1, -2)
        y = self.conv(y)
        y = y.transpose(-1, -2).unsqueeze(-1)
        y = self.sigmoid(y)
        return x * y.expand_as(x)


def inject_eca(model, k_size=3):
    # PERBAIKAN: ECA disisipkan ke SEMUA Bottleneck block (layer1-4), bukan cuma
    # layer yang di-unfreeze -- sesuai desain ECA-Net asli yang memasang attention
    # di seluruh backbone. Scope freeze/unfreeze BACKBONE tetap diatur terpisah
    # lewat apply_freeze_strategy (lihat PERBAIKAN di bawah: modul ECA sendiri
    # selalu trainable, terlepas dari block induknya beku atau tidak).
    n_injected = 0
    for layer_name in ["layer1", "layer2", "layer3", "layer4"]:
        layer = getattr(model, layer_name, None)
        if layer is None:
            continue
        for block in layer:
            channels = block.bn3.num_features
            block.se = ECAAttention(channels, k_size=k_size)
            n_injected += 1
    print(f"  [ECA] Disisipkan ke {n_injected} Bottleneck block (layer1-4).")
    return model

In [6]:
def build_model(num_classes, dropout=DROPOUT):
    # PERBAIKAN: head sederhana bawaan timm (Linear + drop_rate), BUKAN custom
    # Linear->BN->ReLU->Dropout->Linear seperti EXP01-03 lama. Diselaraskan dengan
    # ViT exp01 & ResNet18 -- supaya kapasitas head TIDAK jadi confound tambahan
    # saat membandingkan arsitektur (kalau satu arsitektur dikasih head lebih besar
    # dari yang lain, selisih performa bisa jadi cuma soal head, bukan backbone).
    model = timm.create_model(
        TIMM_NAME, pretrained=True, num_classes=num_classes, drop_rate=dropout
    )
    # PERBAIKAN (ECA): sisipkan ECA ke tiap Bottleneck SETELAH model pretrained
    # dibuat -- supaya bobot pretrained conv1/2/3/bn tidak tersentuh, cuma nambah
    # modul baru di slot `.se` yang random-init.
    if USE_ECA:
        model = inject_eca(model, k_size=ECA_K_SIZE)
    return model


def apply_freeze_strategy(model, patterns=UNFREEZE_PATTERNS):
    for p in model.parameters():
        p.requires_grad = False
    for name, p in model.named_parameters():
        if any(pat in name for pat in patterns):
            p.requires_grad = True

    # PERBAIKAN (ECA): modul ECA SELALU trainable, terlepas dari UNFREEZE_PATTERNS
    # -- konsisten dengan exp02 ViT ECA (attention submodule selalu unfrozen).
    # Bobotnya random-init (bukan pretrained), jadi kalau block induknya kebetulan
    # di luar scope unfreeze (mis. layer1), ECA di block itu tidak boleh ikut beku,
    # kalau tidak dia jadi dead weight (random & tidak pernah di-update).
    if USE_ECA:
        for module in model.modules():
            if isinstance(module, ECAAttention):
                for p in module.parameters():
                    p.requires_grad = True

    n_trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    n_total = sum(p.numel() for p in model.parameters())
    print(f"  [{ARCH_KEY}] Trainable params: {n_trainable:,} / {n_total:,} ({100*n_trainable/n_total:.1f}%)")
    return model

## 6. Train 1 Fold

In [7]:
def train_one_fold(fold, train_idx, val_idx, run):
    train_tf, eval_tf = get_transforms(IMG_SIZE)

    train_files  = [filepaths[i] for i in train_idx]
    train_labels = [labels[i] for i in train_idx]
    val_files    = [filepaths[i] for i in val_idx]
    val_labels   = [labels[i] for i in val_idx]

    # PERBAIKAN (dari ViT exp01): pin_memory=True -- percepat transfer CPU->GPU.
    # num_workers=2 dari ResNet18 (lebih cepat load data daripada 0 di EXP03 lama).
    train_loader = DataLoader(
        SkinDataset(train_files, train_labels, train_tf),
        batch_size=BATCH_SIZE, shuffle=True, num_workers=0, pin_memory=True
    )
    val_loader = DataLoader(
        SkinDataset(val_files, val_labels, eval_tf),
        batch_size=BATCH_SIZE, shuffle=False, num_workers=0, pin_memory=True
    )

    # PERBAIKAN: reseed per fold -- inisialisasi FC head & urutan shuffle
    # reproducible, tidak tergantung urutan eksekusi fold sebelumnya.
    random.seed(SEED + fold); np.random.seed(SEED + fold)
    torch.manual_seed(SEED + fold); torch.cuda.manual_seed_all(SEED + fold)

    model = build_model(num_classes)
    model = apply_freeze_strategy(model)
    model = model.to(device)

    # PERBAIKAN (dari ViT exp01): class_weights dinormalisasi supaya rata-rata = 1.
    # EXP01-03 & ResNet18 sebelumnya cuma 1./bincount TANPA normalisasi --
    # magnitude weight antar kelas timpang, jadi salah satu sumber loss yang
    # "melompat" tergantung komposisi kelas tiap batch.
    class_counts  = np.bincount(train_labels, minlength=num_classes)
    class_weights = 1. / torch.tensor(class_counts, dtype=torch.float)
    class_weights = class_weights / class_weights.sum() * num_classes

    criterion = nn.CrossEntropyLoss(
        weight=class_weights.to(device), label_smoothing=LABEL_SMOOTHING
    )
    optimizer = optim.AdamW(
        filter(lambda p: p.requires_grad, model.parameters()),
        lr=LR, weight_decay=WEIGHT_DECAY
    )
    # PERBAIKAN: scheduler disamakan persis dengan ViT exp01 & ResNet18 -- root
    # cause instabilitas ResNet50 lama (OneCycleLR + EarlyStopping yang memotong
    # sebelum siklus selesai) sudah tidak ada lagi di sini.
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode="max", factor=SCHEDULER_FACTOR, patience=SCHEDULER_PATIENCE,
        threshold=SCHEDULER_THRESHOLD, min_lr=SCHEDULER_MIN_LR
    )

    # PERBAIKAN (dari ViT exp01): AMP -- autocast di forward pass, GradScaler
    # untuk backward/update supaya gradient float16 tidak underflow.
    scaler = GradScaler()

    early_stopping = EarlyStopping(patience=EARLY_STOP_PATIENCE)
    best_val_f1 = -np.inf
    # PERBAIKAN: tracking accuracy/precision/recall di titik checkpoint terbaik juga
    # (sebelumnya cuma f1) -- supaya format output/summary sama seperti ViT exp01,
    # yang melaporkan keempat metrik (bukan cuma F1) di rekap akhir.
    best_val_acc = -np.inf
    best_val_precision = -np.inf
    best_val_recall = -np.inf
    best_val_loss = np.inf
    best_train_loss = np.inf
    best_model_path = None
    train_losses, val_losses = [], []

    for epoch in range(EPOCHS):
        print(f"\n[{ARCH_KEY} | fold {fold+1}] Epoch {epoch+1}/{EPOCHS} (LR: {optimizer.param_groups[0]['lr']:.2e})")

        # TRAIN
        model.train()
        train_loss = 0
        for imgs, tgts in tqdm(train_loader, desc="Train"):
            imgs, tgts = imgs.to(device), tgts.to(device)
            optimizer.zero_grad()
            with autocast():
                loss = criterion(model(imgs), tgts)
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
            train_loss += loss.item()

        # VALIDATION
        model.eval()
        val_loss = 0
        preds, trues = [], []
        with torch.no_grad():
            for imgs, tgts in tqdm(val_loader, desc="Val"):
                imgs, tgts = imgs.to(device), tgts.to(device)
                with autocast():
                    outputs = model(imgs)
                    v_loss  = criterion(outputs, tgts)
                val_loss += v_loss.item()
                preds.extend(outputs.argmax(1).cpu().numpy())
                trues.extend(tgts.cpu().numpy())

        avg_train_loss = train_loss / len(train_loader)
        avg_val_loss   = val_loss / len(val_loader)

        acc       = accuracy_score(trues, preds)
        precision = precision_score(trues, preds, average="weighted", zero_division=0)
        recall    = recall_score(trues, preds, average="weighted", zero_division=0)
        f1        = f1_score(trues, preds, average="weighted", zero_division=0)

        scheduler.step(f1)

        train_losses.append(avg_train_loss)
        val_losses.append(avg_val_loss)

        print(f"Train Loss : {avg_train_loss:.4f} | Val Loss  : {avg_val_loss:.4f}")
        print(f"Accuracy   : {acc:.4f}  | Precision : {precision:.4f}")
        print(f"Recall     : {recall:.4f}  | F1 Score  : {f1:.4f}")

        run.log({
            "epoch": epoch + 1,
            f"fold_{fold+1}/train_loss": avg_train_loss,
            f"fold_{fold+1}/val_loss": avg_val_loss,
            f"fold_{fold+1}/accuracy": acc,
            f"fold_{fold+1}/precision": precision,
            f"fold_{fold+1}/recall": recall,
            f"fold_{fold+1}/f1_score": f1,
            f"fold_{fold+1}/lr": optimizer.param_groups[0]["lr"],
        })

        # SAVE BEST MODEL -- kriteria val_f1 tertinggi (bukan val_loss terendah)
        if f1 > best_val_f1:
            best_val_f1 = f1
            best_val_acc = acc
            best_val_precision = precision
            best_val_recall = recall
            best_val_loss = avg_val_loss
            best_train_loss = avg_train_loss

            save_path = f"{OUTPUT_DIR}/{ARCH_KEY}_fold{fold+1}.pth"
            torch.save({
                "model_state_dict": model.state_dict(),
                "val_loss": avg_val_loss,
                "f1": f1,
                "fold": fold + 1,
                "arch": ARCH_KEY,
            }, save_path)
            best_model_path = save_path
            print(f"  ✓ Model saved → {save_path} (F1: {f1:.4f})")

        if early_stopping.step(f1):
            print("Early Stopping Triggered")
            break

    # ── PLOT LOSS CURVE PER FOLD ──────────────────────────────────────────────
    epochs_ran = range(1, len(train_losses) + 1)
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(epochs_ran, train_losses, label="Train Loss", marker="o", markersize=3)
    ax.plot(epochs_ran, val_losses, label="Val Loss", marker="o", markersize=3)
    ax.set_title(f"{ARCH_KEY} — Fold {fold+1} Loss Curve")
    ax.set_xlabel("Epoch"); ax.set_ylabel("Loss")
    ax.legend(); ax.grid(True, alpha=0.3)
    curve_path = f"{OUTPUT_DIR}/{ARCH_KEY}_Fold_{fold+1}_Loss_Curve.png"
    fig.savefig(curve_path, dpi=150, bbox_inches="tight")
    run.log({f"Loss_Curve/Fold_{fold+1}": wandb.Image(curve_path)})
    plt.close(fig)

    return {
        "arch": ARCH_KEY,
        "fold": fold + 1,
        "train_loss": best_train_loss,
        "val_loss": best_val_loss,
        # PERBAIKAN: sertakan accuracy/precision/recall (bukan cuma f1), supaya
        # results_df punya kolom yang sama seperti fold_accuracies/fold_precision/
        # fold_recall/fold_f1 di ViT exp01.
        "accuracy": best_val_acc,
        "precision": best_val_precision,
        "recall": best_val_recall,
        "f1": best_val_f1,
        "model_path": best_model_path,
    }

## 7. MAIN LOOP — 5 Fold (ResNet50)

Kalau waktu habis di tengah jalan: checkpoint tiap fold udah ke-save duluan (di `all_results`), aman buat dilanjut manual per-fold.

In [8]:
all_results = []

run = wandb.init(
    project="SkinDisease-CNN",
    entity="devianestnarendra_Team",
    name=f"{ARCH_KEY}",
    reinit=True,
    config={
        "architecture": ARCH_KEY,
        "n_folds": N_FOLDS,
        "epochs": EPOCHS,
        "batch_size": BATCH_SIZE,
        "img_size": IMG_SIZE,
        "optimizer": "AdamW",
        "scheduler": f"ReduceLROnPlateau(mode=max, factor={SCHEDULER_FACTOR}, patience={SCHEDULER_PATIENCE})",
        "lr": LR,
        "dropout": DROPOUT,
        "weight_decay": WEIGHT_DECAY,
        "label_smoothing": LABEL_SMOOTHING,
        "unfreeze_patterns": UNFREEZE_PATTERNS,
        "checkpoint_criteria": "best_val_f1",
        "amp": True,
        "seed": SEED,
        "use_eca": USE_ECA,
        "eca_k_size": ECA_K_SIZE,
    }
)

for fold, (train_idx, val_idx) in enumerate(skf.split(filepaths, labels)):
    result = train_one_fold(fold, train_idx, val_idx, run)
    all_results.append(result)

run.finish()

results_df = pd.DataFrame(all_results)
results_df

wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.

C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:54: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler()

  [ECA] Disisipkan ke 16 Bottleneck block (layer1-4).
  [EXP02_ResNet50_ECA] Trainable params: 23,329,863 / 23,555,207 (99.0%)

[EXP02_ResNet50_ECA | fold 1] Epoch 1/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [03:17<00:00,  1.96it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:40<00:00,  2.44it/s]

Train Loss : 3.1719 | Val Loss  : 3.1670
Accuracy   : 0.2089  | Precision : 0.2274
Recall     : 0.2089  | F1 Score  : 0.1805
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.1805)

[EXP02_ResNet50_ECA | fold 1] Epoch 2/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.70it/s]

Train Loss : 2.9165 | Val Loss  : 2.9414
Accuracy   : 0.2744  | Precision : 0.3184
Recall     : 0.2744  | F1 Score  : 0.2567
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.2567)

[EXP02_ResNet50_ECA | fold 1] Epoch 3/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.69it/s]

Train Loss : 2.7237 | Val Loss  : 2.8099
Accuracy   : 0.3098  | Precision : 0.3428
Recall     : 0.3098  | F1 Score  : 0.2952
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.2952)

[EXP02_ResNet50_ECA | fold 1] Epoch 4/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.71it/s]

Train Loss : 2.5878 | Val Loss  : 2.7267
Accuracy   : 0.3384  | Precision : 0.3805
Recall     : 0.3384  | F1 Score  : 0.3308
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.3308)

[EXP02_ResNet50_ECA | fold 1] Epoch 5/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.69it/s]

Train Loss : 2.4639 | Val Loss  : 2.7039
Accuracy   : 0.3416  | Precision : 0.4020
Recall     : 0.3416  | F1 Score  : 0.3365
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.3365)

[EXP02_ResNet50_ECA | fold 1] Epoch 6/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.70it/s]

Train Loss : 2.3665 | Val Loss  : 2.6217
Accuracy   : 0.3750  | Precision : 0.4239
Recall     : 0.3750  | F1 Score  : 0.3726
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.3726)

[EXP02_ResNet50_ECA | fold 1] Epoch 7/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 2.2697 | Val Loss  : 2.5893
Accuracy   : 0.3882  | Precision : 0.4444
Recall     : 0.3882  | F1 Score  : 0.3887
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.3887)

[EXP02_ResNet50_ECA | fold 1] Epoch 8/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:24<00:00,  2.69it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.71it/s]

Train Loss : 2.1854 | Val Loss  : 2.5526
Accuracy   : 0.4091  | Precision : 0.4649
Recall     : 0.4091  | F1 Score  : 0.4116
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.4116)

[EXP02_ResNet50_ECA | fold 1] Epoch 9/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.48it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.71it/s]

Train Loss : 2.0965 | Val Loss  : 2.5374
Accuracy   : 0.4245  | Precision : 0.4810
Recall     : 0.4245  | F1 Score  : 0.4289
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.4289)

[EXP02_ResNet50_ECA | fold 1] Epoch 10/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:38<00:00,  2.45it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.60it/s]

Train Loss : 2.0161 | Val Loss  : 2.5217
Accuracy   : 0.4271  | Precision : 0.4817
Recall     : 0.4271  | F1 Score  : 0.4295
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.4295)

[EXP02_ResNet50_ECA | fold 1] Epoch 11/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:37<00:00,  2.47it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.62it/s]

Train Loss : 1.9373 | Val Loss  : 2.4786
Accuracy   : 0.4444  | Precision : 0.4904
Recall     : 0.4444  | F1 Score  : 0.4496
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.4496)

[EXP02_ResNet50_ECA | fold 1] Epoch 12/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:38<00:00,  2.45it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.62it/s]

Train Loss : 1.8613 | Val Loss  : 2.4887
Accuracy   : 0.4499  | Precision : 0.5054
Recall     : 0.4499  | F1 Score  : 0.4567
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.4567)

[EXP02_ResNet50_ECA | fold 1] Epoch 13/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.48it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.63it/s]

Train Loss : 1.7939 | Val Loss  : 2.4410
Accuracy   : 0.4672  | Precision : 0.5097
Recall     : 0.4672  | F1 Score  : 0.4689
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.4689)

[EXP02_ResNet50_ECA | fold 1] Epoch 14/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.48it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.7289 | Val Loss  : 2.4696
Accuracy   : 0.4569  | Precision : 0.5039
Recall     : 0.4569  | F1 Score  : 0.4584

[EXP02_ResNet50_ECA | fold 1] Epoch 15/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:37<00:00,  2.47it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.58it/s]

Train Loss : 1.6606 | Val Loss  : 2.4209
Accuracy   : 0.4794  | Precision : 0.5088
Recall     : 0.4794  | F1 Score  : 0.4801
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.4801)

[EXP02_ResNet50_ECA | fold 1] Epoch 16/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:40<00:00,  2.42it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 1.6069 | Val Loss  : 2.4470
Accuracy   : 0.4740  | Precision : 0.5192
Recall     : 0.4740  | F1 Score  : 0.4785

[EXP02_ResNet50_ECA | fold 1] Epoch 17/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:40<00:00,  2.43it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.62it/s]

Train Loss : 1.5452 | Val Loss  : 2.4091
Accuracy   : 0.4929  | Precision : 0.5283
Recall     : 0.4929  | F1 Score  : 0.4960
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.4960)

[EXP02_ResNet50_ECA | fold 1] Epoch 18/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:41<00:00,  2.41it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.52it/s]

Train Loss : 1.4875 | Val Loss  : 2.3758
Accuracy   : 0.4965  | Precision : 0.5218
Recall     : 0.4965  | F1 Score  : 0.4982
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.4982)

[EXP02_ResNet50_ECA | fold 1] Epoch 19/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:44<00:00,  2.37it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.68it/s]

Train Loss : 1.4519 | Val Loss  : 2.4045
Accuracy   : 0.4974  | Precision : 0.5274
Recall     : 0.4974  | F1 Score  : 0.5005
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.5005)

[EXP02_ResNet50_ECA | fold 1] Epoch 20/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.49it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.70it/s]

Train Loss : 1.4059 | Val Loss  : 2.3837
Accuracy   : 0.5035  | Precision : 0.5294
Recall     : 0.5035  | F1 Score  : 0.5058
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.5058)

[EXP02_ResNet50_ECA | fold 1] Epoch 21/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.3817 | Val Loss  : 2.3671
Accuracy   : 0.5145  | Precision : 0.5334
Recall     : 0.5145  | F1 Score  : 0.5152
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.5152)

[EXP02_ResNet50_ECA | fold 1] Epoch 22/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.69it/s]

Train Loss : 1.3429 | Val Loss  : 2.3764
Accuracy   : 0.5132  | Precision : 0.5376
Recall     : 0.5132  | F1 Score  : 0.5155
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.5155)

[EXP02_ResNet50_ECA | fold 1] Epoch 23/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.49it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 1.3005 | Val Loss  : 2.3293
Accuracy   : 0.5299  | Precision : 0.5443
Recall     : 0.5299  | F1 Score  : 0.5321
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.5321)

[EXP02_ResNet50_ECA | fold 1] Epoch 24/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.48it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.69it/s]

Train Loss : 1.2724 | Val Loss  : 2.3589
Accuracy   : 0.5222  | Precision : 0.5398
Recall     : 0.5222  | F1 Score  : 0.5234

[EXP02_ResNet50_ECA | fold 1] Epoch 25/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:37<00:00,  2.47it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.69it/s]

Train Loss : 1.2545 | Val Loss  : 2.3716
Accuracy   : 0.5241  | Precision : 0.5441
Recall     : 0.5241  | F1 Score  : 0.5260

[EXP02_ResNet50_ECA | fold 1] Epoch 26/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.49it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.61it/s]

Train Loss : 1.2224 | Val Loss  : 2.3362
Accuracy   : 0.5276  | Precision : 0.5419
Recall     : 0.5276  | F1 Score  : 0.5282

[EXP02_ResNet50_ECA | fold 1] Epoch 27/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.49it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.69it/s]

Train Loss : 1.1848 | Val Loss  : 2.3211
Accuracy   : 0.5318  | Precision : 0.5447
Recall     : 0.5318  | F1 Score  : 0.5325
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.5325)

[EXP02_ResNet50_ECA | fold 1] Epoch 28/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:37<00:00,  2.47it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.70it/s]

Train Loss : 1.1732 | Val Loss  : 2.3176
Accuracy   : 0.5370  | Precision : 0.5466
Recall     : 0.5370  | F1 Score  : 0.5360
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.5360)

[EXP02_ResNet50_ECA | fold 1] Epoch 29/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.1705 | Val Loss  : 2.3080
Accuracy   : 0.5379  | Precision : 0.5474
Recall     : 0.5379  | F1 Score  : 0.5380
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.5380)

[EXP02_ResNet50_ECA | fold 1] Epoch 30/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.48it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.71it/s]

Train Loss : 1.1555 | Val Loss  : 2.3022
Accuracy   : 0.5437  | Precision : 0.5541
Recall     : 0.5437  | F1 Score  : 0.5449
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold1.pth (F1: 0.5449)

[EXP02_ResNet50_ECA | fold 1] Epoch 31/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.62it/s]

Train Loss : 1.1606 | Val Loss  : 2.3124
Accuracy   : 0.5392  | Precision : 0.5486
Recall     : 0.5392  | F1 Score  : 0.5397

[EXP02_ResNet50_ECA | fold 1] Epoch 32/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.49it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.70it/s]

Train Loss : 1.1561 | Val Loss  : 2.3247
Accuracy   : 0.5389  | Precision : 0.5520
Recall     : 0.5389  | F1 Score  : 0.5401

[EXP02_ResNet50_ECA | fold 1] Epoch 33/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:38<00:00,  2.46it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.1481 | Val Loss  : 2.3267
Accuracy   : 0.5408  | Precision : 0.5551
Recall     : 0.5408  | F1 Score  : 0.5415

[EXP02_ResNet50_ECA | fold 1] Epoch 34/50 (LR: 1.00e-06)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.49it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.1472 | Val Loss  : 2.3121
Accuracy   : 0.5392  | Precision : 0.5508
Recall     : 0.5392  | F1 Score  : 0.5395

[EXP02_ResNet50_ECA | fold 1] Epoch 35/50 (LR: 1.00e-06)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:38<00:00,  2.46it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.1502 | Val Loss  : 2.3115
Accuracy   : 0.5437  | Precision : 0.5521
Recall     : 0.5437  | F1 Score  : 0.5432

[EXP02_ResNet50_ECA | fold 1] Epoch 36/50 (LR: 1.00e-06)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:37<00:00,  2.47it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 1.1478 | Val Loss  : 2.3192
Accuracy   : 0.5337  | Precision : 0.5468
Recall     : 0.5337  | F1 Score  : 0.5350

[EXP02_ResNet50_ECA | fold 1] Epoch 37/50 (LR: 1.00e-07)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.71it/s]

Train Loss : 1.1475 | Val Loss  : 2.3092
Accuracy   : 0.5418  | Precision : 0.5526
Recall     : 0.5418  | F1 Score  : 0.5416
Early Stopping Triggered

C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:54: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler()

  [ECA] Disisipkan ke 16 Bottleneck block (layer1-4).
  [EXP02_ResNet50_ECA] Trainable params: 23,329,863 / 23,555,207 (99.0%)

[EXP02_ResNet50_ECA | fold 2] Epoch 1/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:38<00:00,  2.46it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 3.1922 | Val Loss  : 3.1894
Accuracy   : 0.1677  | Precision : 0.2095
Recall     : 0.1677  | F1 Score  : 0.1326
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.1326)

[EXP02_ResNet50_ECA | fold 2] Epoch 2/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:38<00:00,  2.45it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.60it/s]

Train Loss : 2.9341 | Val Loss  : 2.9579
Accuracy   : 0.2654  | Precision : 0.3090
Recall     : 0.2654  | F1 Score  : 0.2428
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.2428)

[EXP02_ResNet50_ECA | fold 2] Epoch 3/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.48it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.70it/s]

Train Loss : 2.7409 | Val Loss  : 2.8326
Accuracy   : 0.3043  | Precision : 0.3441
Recall     : 0.3043  | F1 Score  : 0.2922
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.2922)

[EXP02_ResNet50_ECA | fold 2] Epoch 4/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:39<00:00,  2.44it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 2.5977 | Val Loss  : 2.7484
Accuracy   : 0.3316  | Precision : 0.3695
Recall     : 0.3316  | F1 Score  : 0.3237
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.3237)

[EXP02_ResNet50_ECA | fold 2] Epoch 5/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:37<00:00,  2.47it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 2.4791 | Val Loss  : 2.6640
Accuracy   : 0.3618  | Precision : 0.3958
Recall     : 0.3618  | F1 Score  : 0.3516
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.3516)

[EXP02_ResNet50_ECA | fold 2] Epoch 6/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.48it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.69it/s]

Train Loss : 2.3682 | Val Loss  : 2.6367
Accuracy   : 0.3728  | Precision : 0.4147
Recall     : 0.3728  | F1 Score  : 0.3714
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.3714)

[EXP02_ResNet50_ECA | fold 2] Epoch 7/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:37<00:00,  2.48it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.69it/s]

Train Loss : 2.2593 | Val Loss  : 2.6124
Accuracy   : 0.3789  | Precision : 0.4271
Recall     : 0.3789  | F1 Score  : 0.3766
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.3766)

[EXP02_ResNet50_ECA | fold 2] Epoch 8/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.49it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.68it/s]

Train Loss : 2.1528 | Val Loss  : 2.5898
Accuracy   : 0.3914  | Precision : 0.4513
Recall     : 0.3914  | F1 Score  : 0.3932
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.3932)

[EXP02_ResNet50_ECA | fold 2] Epoch 9/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.48it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.69it/s]

Train Loss : 2.0648 | Val Loss  : 2.5465
Accuracy   : 0.4113  | Precision : 0.4595
Recall     : 0.4113  | F1 Score  : 0.4116
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.4116)

[EXP02_ResNet50_ECA | fold 2] Epoch 10/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.48it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.68it/s]

Train Loss : 1.9772 | Val Loss  : 2.5312
Accuracy   : 0.4277  | Precision : 0.4846
Recall     : 0.4277  | F1 Score  : 0.4357
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.4357)

[EXP02_ResNet50_ECA | fold 2] Epoch 11/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:37<00:00,  2.48it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.70it/s]

Train Loss : 1.8942 | Val Loss  : 2.5096
Accuracy   : 0.4322  | Precision : 0.4891
Recall     : 0.4322  | F1 Score  : 0.4400
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.4400)

[EXP02_ResNet50_ECA | fold 2] Epoch 12/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 1.8167 | Val Loss  : 2.4883
Accuracy   : 0.4489  | Precision : 0.4968
Recall     : 0.4489  | F1 Score  : 0.4529
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.4529)

[EXP02_ResNet50_ECA | fold 2] Epoch 13/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.7358 | Val Loss  : 2.4963
Accuracy   : 0.4492  | Precision : 0.5069
Recall     : 0.4492  | F1 Score  : 0.4580
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.4580)

[EXP02_ResNet50_ECA | fold 2] Epoch 14/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.6726 | Val Loss  : 2.4740
Accuracy   : 0.4579  | Precision : 0.5055
Recall     : 0.4579  | F1 Score  : 0.4642
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.4642)

[EXP02_ResNet50_ECA | fold 2] Epoch 15/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.71it/s]

Train Loss : 1.6023 | Val Loss  : 2.4881
Accuracy   : 0.4672  | Precision : 0.5220
Recall     : 0.4672  | F1 Score  : 0.4758
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.4758)

[EXP02_ResNet50_ECA | fold 2] Epoch 16/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.5431 | Val Loss  : 2.4470
Accuracy   : 0.4820  | Precision : 0.5271
Recall     : 0.4820  | F1 Score  : 0.4907
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.4907)

[EXP02_ResNet50_ECA | fold 2] Epoch 17/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.70it/s]

Train Loss : 1.4867 | Val Loss  : 2.4594
Accuracy   : 0.4810  | Precision : 0.5230
Recall     : 0.4810  | F1 Score  : 0.4877

[EXP02_ResNet50_ECA | fold 2] Epoch 18/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.4419 | Val Loss  : 2.4502
Accuracy   : 0.4839  | Precision : 0.5312
Recall     : 0.4839  | F1 Score  : 0.4914
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.4914)

[EXP02_ResNet50_ECA | fold 2] Epoch 19/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.71it/s]

Train Loss : 1.3997 | Val Loss  : 2.4462
Accuracy   : 0.5022  | Precision : 0.5426
Recall     : 0.5022  | F1 Score  : 0.5096
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.5096)

[EXP02_ResNet50_ECA | fold 2] Epoch 20/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.3626 | Val Loss  : 2.4524
Accuracy   : 0.5006  | Precision : 0.5426
Recall     : 0.5006  | F1 Score  : 0.5074

[EXP02_ResNet50_ECA | fold 2] Epoch 21/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:25<00:00,  3.83it/s]

Train Loss : 1.3283 | Val Loss  : 2.4489
Accuracy   : 0.5061  | Precision : 0.5522
Recall     : 0.5061  | F1 Score  : 0.5164
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.5164)

[EXP02_ResNet50_ECA | fold 2] Epoch 22/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.2981 | Val Loss  : 2.4589
Accuracy   : 0.5048  | Precision : 0.5481
Recall     : 0.5048  | F1 Score  : 0.5126

[EXP02_ResNet50_ECA | fold 2] Epoch 23/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.71it/s]

Train Loss : 1.2631 | Val Loss  : 2.4433
Accuracy   : 0.5084  | Precision : 0.5450
Recall     : 0.5084  | F1 Score  : 0.5152

[EXP02_ResNet50_ECA | fold 2] Epoch 24/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.70it/s]

Train Loss : 1.2397 | Val Loss  : 2.4264
Accuracy   : 0.5157  | Precision : 0.5432
Recall     : 0.5157  | F1 Score  : 0.5196
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.5196)

[EXP02_ResNet50_ECA | fold 2] Epoch 25/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.71it/s]

Train Loss : 1.2146 | Val Loss  : 2.4196
Accuracy   : 0.5202  | Precision : 0.5477
Recall     : 0.5202  | F1 Score  : 0.5246
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.5246)

[EXP02_ResNet50_ECA | fold 2] Epoch 26/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.49it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.71it/s]

Train Loss : 1.1923 | Val Loss  : 2.4363
Accuracy   : 0.5186  | Precision : 0.5479
Recall     : 0.5186  | F1 Score  : 0.5227

[EXP02_ResNet50_ECA | fold 2] Epoch 27/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.49it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 1.1709 | Val Loss  : 2.3942
Accuracy   : 0.5270  | Precision : 0.5486
Recall     : 0.5270  | F1 Score  : 0.5312
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.5312)

[EXP02_ResNet50_ECA | fold 2] Epoch 28/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:37<00:00,  2.47it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.58it/s]

Train Loss : 1.1520 | Val Loss  : 2.3929
Accuracy   : 0.5353  | Precision : 0.5553
Recall     : 0.5353  | F1 Score  : 0.5386
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.5386)

[EXP02_ResNet50_ECA | fold 2] Epoch 29/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:37<00:00,  2.46it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.71it/s]

Train Loss : 1.1339 | Val Loss  : 2.4094
Accuracy   : 0.5302  | Precision : 0.5516
Recall     : 0.5302  | F1 Score  : 0.5336

[EXP02_ResNet50_ECA | fold 2] Epoch 30/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 1.1108 | Val Loss  : 2.3944
Accuracy   : 0.5357  | Precision : 0.5603
Recall     : 0.5357  | F1 Score  : 0.5409
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.5409)

[EXP02_ResNet50_ECA | fold 2] Epoch 31/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 1.1010 | Val Loss  : 2.3842
Accuracy   : 0.5402  | Precision : 0.5577
Recall     : 0.5402  | F1 Score  : 0.5441
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.5441)

[EXP02_ResNet50_ECA | fold 2] Epoch 32/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 1.0876 | Val Loss  : 2.3990
Accuracy   : 0.5392  | Precision : 0.5577
Recall     : 0.5392  | F1 Score  : 0.5429

[EXP02_ResNet50_ECA | fold 2] Epoch 33/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.75it/s]

Train Loss : 1.0702 | Val Loss  : 2.3633
Accuracy   : 0.5450  | Precision : 0.5589
Recall     : 0.5450  | F1 Score  : 0.5470
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.5470)

[EXP02_ResNet50_ECA | fold 2] Epoch 34/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 1.0579 | Val Loss  : 2.3615
Accuracy   : 0.5511  | Precision : 0.5643
Recall     : 0.5511  | F1 Score  : 0.5533
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.5533)

[EXP02_ResNet50_ECA | fold 2] Epoch 35/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 1.0539 | Val Loss  : 2.3817
Accuracy   : 0.5537  | Precision : 0.5703
Recall     : 0.5537  | F1 Score  : 0.5569
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.5569)

[EXP02_ResNet50_ECA | fold 2] Epoch 36/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 1.0343 | Val Loss  : 2.3667
Accuracy   : 0.5472  | Precision : 0.5606
Recall     : 0.5472  | F1 Score  : 0.5489

[EXP02_ResNet50_ECA | fold 2] Epoch 37/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.49it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 1.0291 | Val Loss  : 2.3738
Accuracy   : 0.5504  | Precision : 0.5639
Recall     : 0.5504  | F1 Score  : 0.5534

[EXP02_ResNet50_ECA | fold 2] Epoch 38/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.48it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.0195 | Val Loss  : 2.3525
Accuracy   : 0.5543  | Precision : 0.5708
Recall     : 0.5543  | F1 Score  : 0.5581
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.5581)

[EXP02_ResNet50_ECA | fold 2] Epoch 39/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:38<00:00,  2.45it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:28<00:00,  3.49it/s]

Train Loss : 1.0101 | Val Loss  : 2.3567
Accuracy   : 0.5578  | Precision : 0.5756
Recall     : 0.5578  | F1 Score  : 0.5614
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.5614)

[EXP02_ResNet50_ECA | fold 2] Epoch 40/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:37<00:00,  2.48it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.75it/s]

Train Loss : 1.0048 | Val Loss  : 2.3715
Accuracy   : 0.5572  | Precision : 0.5732
Recall     : 0.5572  | F1 Score  : 0.5602

[EXP02_ResNet50_ECA | fold 2] Epoch 41/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.71it/s]

Train Loss : 0.9943 | Val Loss  : 2.3557
Accuracy   : 0.5553  | Precision : 0.5651
Recall     : 0.5553  | F1 Score  : 0.5567

[EXP02_ResNet50_ECA | fold 2] Epoch 42/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.49it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 0.9908 | Val Loss  : 2.3486
Accuracy   : 0.5623  | Precision : 0.5775
Recall     : 0.5623  | F1 Score  : 0.5653
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.5653)

[EXP02_ResNet50_ECA | fold 2] Epoch 43/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.49it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.69it/s]

Train Loss : 0.9726 | Val Loss  : 2.3633
Accuracy   : 0.5578  | Precision : 0.5778
Recall     : 0.5578  | F1 Score  : 0.5621

[EXP02_ResNet50_ECA | fold 2] Epoch 44/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:37<00:00,  2.47it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.75it/s]

Train Loss : 0.9775 | Val Loss  : 2.3488
Accuracy   : 0.5575  | Precision : 0.5685
Recall     : 0.5575  | F1 Score  : 0.5584

[EXP02_ResNet50_ECA | fold 2] Epoch 45/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.49it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.76it/s]

Train Loss : 0.9664 | Val Loss  : 2.3383
Accuracy   : 0.5646  | Precision : 0.5768
Recall     : 0.5646  | F1 Score  : 0.5669
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.5669)

[EXP02_ResNet50_ECA | fold 2] Epoch 46/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.51it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.76it/s]

Train Loss : 0.9589 | Val Loss  : 2.3211
Accuracy   : 0.5742  | Precision : 0.5853
Recall     : 0.5742  | F1 Score  : 0.5765
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold2.pth (F1: 0.5765)

[EXP02_ResNet50_ECA | fold 2] Epoch 47/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:25<00:00,  3.77it/s]

Train Loss : 0.9584 | Val Loss  : 2.3235
Accuracy   : 0.5713  | Precision : 0.5799
Recall     : 0.5713  | F1 Score  : 0.5715

[EXP02_ResNet50_ECA | fold 2] Epoch 48/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.76it/s]

Train Loss : 0.9532 | Val Loss  : 2.3505
Accuracy   : 0.5639  | Precision : 0.5755
Recall     : 0.5639  | F1 Score  : 0.5659

[EXP02_ResNet50_ECA | fold 2] Epoch 49/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.51it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:25<00:00,  3.77it/s]

Train Loss : 0.9441 | Val Loss  : 2.3307
Accuracy   : 0.5639  | Precision : 0.5791
Recall     : 0.5639  | F1 Score  : 0.5666

[EXP02_ResNet50_ECA | fold 2] Epoch 50/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.75it/s]

Train Loss : 0.9330 | Val Loss  : 2.3201
Accuracy   : 0.5717  | Precision : 0.5853
Recall     : 0.5717  | F1 Score  : 0.5744

C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:54: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler()

  [ECA] Disisipkan ke 16 Bottleneck block (layer1-4).
  [EXP02_ResNet50_ECA] Trainable params: 23,329,863 / 23,555,207 (99.0%)

[EXP02_ResNet50_ECA | fold 3] Epoch 1/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:55<00:00,  2.22it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:40<00:00,  2.45it/s]

Train Loss : 3.1777 | Val Loss  : 3.1919
Accuracy   : 0.1964  | Precision : 0.2665
Recall     : 0.1964  | F1 Score  : 0.1714
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.1714)

[EXP02_ResNet50_ECA | fold 3] Epoch 2/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:37<00:00,  2.48it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 2.9039 | Val Loss  : 2.9723
Accuracy   : 0.2636  | Precision : 0.2972
Recall     : 0.2636  | F1 Score  : 0.2499
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.2499)

[EXP02_ResNet50_ECA | fold 3] Epoch 3/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:37<00:00,  2.48it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.69it/s]

Train Loss : 2.7126 | Val Loss  : 2.8904
Accuracy   : 0.2861  | Precision : 0.3486
Recall     : 0.2861  | F1 Score  : 0.2812
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.2812)

[EXP02_ResNet50_ECA | fold 3] Epoch 4/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 2.5741 | Val Loss  : 2.7847
Accuracy   : 0.3189  | Precision : 0.3671
Recall     : 0.3189  | F1 Score  : 0.3127
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.3127)

[EXP02_ResNet50_ECA | fold 3] Epoch 5/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.49it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 2.4594 | Val Loss  : 2.7319
Accuracy   : 0.3407  | Precision : 0.4003
Recall     : 0.3407  | F1 Score  : 0.3409
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.3409)

[EXP02_ResNet50_ECA | fold 3] Epoch 6/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.48it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 2.3561 | Val Loss  : 2.6792
Accuracy   : 0.3616  | Precision : 0.4314
Recall     : 0.3616  | F1 Score  : 0.3645
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.3645)

[EXP02_ResNet50_ECA | fold 3] Epoch 7/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:43<00:00,  2.39it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.63it/s]

Train Loss : 2.2618 | Val Loss  : 2.6407
Accuracy   : 0.3783  | Precision : 0.4490
Recall     : 0.3783  | F1 Score  : 0.3825
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.3825)

[EXP02_ResNet50_ECA | fold 3] Epoch 8/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:37<00:00,  2.46it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.62it/s]

Train Loss : 2.1748 | Val Loss  : 2.5665
Accuracy   : 0.4057  | Precision : 0.4654
Recall     : 0.4057  | F1 Score  : 0.4140
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.4140)

[EXP02_ResNet50_ECA | fold 3] Epoch 9/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.48it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.58it/s]

Train Loss : 2.0863 | Val Loss  : 2.5622
Accuracy   : 0.4143  | Precision : 0.4779
Recall     : 0.4143  | F1 Score  : 0.4237
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.4237)

[EXP02_ResNet50_ECA | fold 3] Epoch 10/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:38<00:00,  2.45it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 2.0008 | Val Loss  : 2.5220
Accuracy   : 0.4304  | Precision : 0.4864
Recall     : 0.4304  | F1 Score  : 0.4360
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.4360)

[EXP02_ResNet50_ECA | fold 3] Epoch 11/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:39<00:00,  2.44it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 1.9132 | Val Loss  : 2.5273
Accuracy   : 0.4323  | Precision : 0.5017
Recall     : 0.4323  | F1 Score  : 0.4411
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.4411)

[EXP02_ResNet50_ECA | fold 3] Epoch 12/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:37<00:00,  2.47it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.60it/s]

Train Loss : 1.8468 | Val Loss  : 2.5200
Accuracy   : 0.4426  | Precision : 0.5139
Recall     : 0.4426  | F1 Score  : 0.4508
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.4508)

[EXP02_ResNet50_ECA | fold 3] Epoch 13/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:41<00:00,  2.41it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.58it/s]

Train Loss : 1.7714 | Val Loss  : 2.4690
Accuracy   : 0.4555  | Precision : 0.5068
Recall     : 0.4555  | F1 Score  : 0.4606
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.4606)

[EXP02_ResNet50_ECA | fold 3] Epoch 14/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:40<00:00,  2.42it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.54it/s]

Train Loss : 1.7060 | Val Loss  : 2.4808
Accuracy   : 0.4638  | Precision : 0.5211
Recall     : 0.4638  | F1 Score  : 0.4708
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.4708)

[EXP02_ResNet50_ECA | fold 3] Epoch 15/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:40<00:00,  2.43it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.57it/s]

Train Loss : 1.6462 | Val Loss  : 2.4385
Accuracy   : 0.4799  | Precision : 0.5217
Recall     : 0.4799  | F1 Score  : 0.4857
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.4857)

[EXP02_ResNet50_ECA | fold 3] Epoch 16/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:38<00:00,  2.45it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.68it/s]

Train Loss : 1.5719 | Val Loss  : 2.4593
Accuracy   : 0.4844  | Precision : 0.5293
Recall     : 0.4844  | F1 Score  : 0.4918
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.4918)

[EXP02_ResNet50_ECA | fold 3] Epoch 17/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:39<00:00,  2.44it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.60it/s]

Train Loss : 1.5253 | Val Loss  : 2.4610
Accuracy   : 0.4844  | Precision : 0.5254
Recall     : 0.4844  | F1 Score  : 0.4880

[EXP02_ResNet50_ECA | fold 3] Epoch 18/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:40<00:00,  2.42it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.68it/s]

Train Loss : 1.4786 | Val Loss  : 2.4327
Accuracy   : 0.4963  | Precision : 0.5276
Recall     : 0.4963  | F1 Score  : 0.4993
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.4993)

[EXP02_ResNet50_ECA | fold 3] Epoch 19/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:41<00:00,  2.40it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.60it/s]

Train Loss : 1.4297 | Val Loss  : 2.3989
Accuracy   : 0.5014  | Precision : 0.5335
Recall     : 0.5014  | F1 Score  : 0.5068
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.5068)

[EXP02_ResNet50_ECA | fold 3] Epoch 20/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:40<00:00,  2.43it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.69it/s]

Train Loss : 1.3912 | Val Loss  : 2.3900
Accuracy   : 0.5111  | Precision : 0.5363
Recall     : 0.5111  | F1 Score  : 0.5148
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.5148)

[EXP02_ResNet50_ECA | fold 3] Epoch 21/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:37<00:00,  2.47it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 1.3496 | Val Loss  : 2.4373
Accuracy   : 0.5031  | Precision : 0.5472
Recall     : 0.5031  | F1 Score  : 0.5103

[EXP02_ResNet50_ECA | fold 3] Epoch 22/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:39<00:00,  2.44it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.3199 | Val Loss  : 2.4132
Accuracy   : 0.5143  | Precision : 0.5427
Recall     : 0.5143  | F1 Score  : 0.5174
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.5174)

[EXP02_ResNet50_ECA | fold 3] Epoch 23/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:38<00:00,  2.46it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 1.2884 | Val Loss  : 2.4258
Accuracy   : 0.5108  | Precision : 0.5409
Recall     : 0.5108  | F1 Score  : 0.5135

[EXP02_ResNet50_ECA | fold 3] Epoch 24/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:39<00:00,  2.43it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.63it/s]

Train Loss : 1.2587 | Val Loss  : 2.3773
Accuracy   : 0.5227  | Precision : 0.5502
Recall     : 0.5227  | F1 Score  : 0.5265
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.5265)

[EXP02_ResNet50_ECA | fold 3] Epoch 25/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:40<00:00,  2.42it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 1.2269 | Val Loss  : 2.3835
Accuracy   : 0.5243  | Precision : 0.5519
Recall     : 0.5243  | F1 Score  : 0.5289
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.5289)

[EXP02_ResNet50_ECA | fold 3] Epoch 26/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:39<00:00,  2.44it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.70it/s]

Train Loss : 1.2017 | Val Loss  : 2.3588
Accuracy   : 0.5352  | Precision : 0.5567
Recall     : 0.5352  | F1 Score  : 0.5385
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.5385)

[EXP02_ResNet50_ECA | fold 3] Epoch 27/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:37<00:00,  2.47it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.60it/s]

Train Loss : 1.1848 | Val Loss  : 2.3791
Accuracy   : 0.5371  | Precision : 0.5574
Recall     : 0.5371  | F1 Score  : 0.5400
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.5400)

[EXP02_ResNet50_ECA | fold 3] Epoch 28/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.48it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.68it/s]

Train Loss : 1.1679 | Val Loss  : 2.3492
Accuracy   : 0.5378  | Precision : 0.5580
Recall     : 0.5378  | F1 Score  : 0.5412
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.5412)

[EXP02_ResNet50_ECA | fold 3] Epoch 29/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.70it/s]

Train Loss : 1.1473 | Val Loss  : 2.3663
Accuracy   : 0.5407  | Precision : 0.5619
Recall     : 0.5407  | F1 Score  : 0.5430
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.5430)

[EXP02_ResNet50_ECA | fold 3] Epoch 30/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.71it/s]

Train Loss : 1.1244 | Val Loss  : 2.3462
Accuracy   : 0.5519  | Precision : 0.5673
Recall     : 0.5519  | F1 Score  : 0.5529
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.5529)

[EXP02_ResNet50_ECA | fold 3] Epoch 31/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 1.1104 | Val Loss  : 2.3463
Accuracy   : 0.5535  | Precision : 0.5746
Recall     : 0.5535  | F1 Score  : 0.5579
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.5579)

[EXP02_ResNet50_ECA | fold 3] Epoch 32/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:25<00:00,  3.81it/s]

Train Loss : 1.0959 | Val Loss  : 2.3242
Accuracy   : 0.5468  | Precision : 0.5615
Recall     : 0.5468  | F1 Score  : 0.5502

[EXP02_ResNet50_ECA | fold 3] Epoch 33/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.69it/s]

Train Loss : 1.0743 | Val Loss  : 2.3224
Accuracy   : 0.5558  | Precision : 0.5661
Recall     : 0.5558  | F1 Score  : 0.5568

[EXP02_ResNet50_ECA | fold 3] Epoch 34/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.69it/s]

Train Loss : 1.0691 | Val Loss  : 2.3172
Accuracy   : 0.5567  | Precision : 0.5686
Recall     : 0.5567  | F1 Score  : 0.5587
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.5587)

[EXP02_ResNet50_ECA | fold 3] Epoch 35/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.71it/s]

Train Loss : 1.0517 | Val Loss  : 2.3129
Accuracy   : 0.5542  | Precision : 0.5652
Recall     : 0.5542  | F1 Score  : 0.5548

[EXP02_ResNet50_ECA | fold 3] Epoch 36/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.0430 | Val Loss  : 2.3148
Accuracy   : 0.5535  | Precision : 0.5692
Recall     : 0.5535  | F1 Score  : 0.5569

[EXP02_ResNet50_ECA | fold 3] Epoch 37/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.0378 | Val Loss  : 2.3607
Accuracy   : 0.5474  | Precision : 0.5628
Recall     : 0.5474  | F1 Score  : 0.5488

[EXP02_ResNet50_ECA | fold 3] Epoch 38/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.71it/s]

Train Loss : 1.0092 | Val Loss  : 2.3133
Accuracy   : 0.5513  | Precision : 0.5618
Recall     : 0.5513  | F1 Score  : 0.5530

[EXP02_ResNet50_ECA | fold 3] Epoch 39/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:37<00:00,  2.47it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 1.0016 | Val Loss  : 2.3158
Accuracy   : 0.5564  | Precision : 0.5668
Recall     : 0.5564  | F1 Score  : 0.5576

[EXP02_ResNet50_ECA | fold 3] Epoch 40/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.68it/s]

Train Loss : 1.0011 | Val Loss  : 2.2943
Accuracy   : 0.5599  | Precision : 0.5703
Recall     : 0.5599  | F1 Score  : 0.5609
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.5609)

[EXP02_ResNet50_ECA | fold 3] Epoch 41/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:37<00:00,  2.47it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.66it/s]

Train Loss : 0.9977 | Val Loss  : 2.2986
Accuracy   : 0.5571  | Precision : 0.5665
Recall     : 0.5571  | F1 Score  : 0.5587

[EXP02_ResNet50_ECA | fold 3] Epoch 42/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:38<00:00,  2.45it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.69it/s]

Train Loss : 1.0002 | Val Loss  : 2.2829
Accuracy   : 0.5644  | Precision : 0.5738
Recall     : 0.5644  | F1 Score  : 0.5656
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.5656)

[EXP02_ResNet50_ECA | fold 3] Epoch 43/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:38<00:00,  2.46it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.71it/s]

Train Loss : 0.9932 | Val Loss  : 2.2841
Accuracy   : 0.5638  | Precision : 0.5697
Recall     : 0.5638  | F1 Score  : 0.5633

[EXP02_ResNet50_ECA | fold 3] Epoch 44/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:38<00:00,  2.45it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:25<00:00,  3.82it/s]

Train Loss : 0.9848 | Val Loss  : 2.2762
Accuracy   : 0.5657  | Precision : 0.5720
Recall     : 0.5657  | F1 Score  : 0.5657
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.5657)

[EXP02_ResNet50_ECA | fold 3] Epoch 45/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:39<00:00,  2.44it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:24<00:00,  3.96it/s]

Train Loss : 0.9899 | Val Loss  : 2.2878
Accuracy   : 0.5641  | Precision : 0.5710
Recall     : 0.5641  | F1 Score  : 0.5647

[EXP02_ResNet50_ECA | fold 3] Epoch 46/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:40<00:00,  2.42it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:25<00:00,  3.81it/s]

Train Loss : 0.9868 | Val Loss  : 2.2824
Accuracy   : 0.5651  | Precision : 0.5715
Recall     : 0.5651  | F1 Score  : 0.5657

[EXP02_ResNet50_ECA | fold 3] Epoch 47/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:38<00:00,  2.45it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.60it/s]

Train Loss : 0.9915 | Val Loss  : 2.2808
Accuracy   : 0.5664  | Precision : 0.5740
Recall     : 0.5664  | F1 Score  : 0.5667
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.5667)

[EXP02_ResNet50_ECA | fold 3] Epoch 48/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:39<00:00,  2.44it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.63it/s]

Train Loss : 0.9858 | Val Loss  : 2.2831
Accuracy   : 0.5677  | Precision : 0.5761
Recall     : 0.5677  | F1 Score  : 0.5690
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.5690)

[EXP02_ResNet50_ECA | fold 3] Epoch 49/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:39<00:00,  2.44it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.70it/s]

Train Loss : 0.9863 | Val Loss  : 2.2862
Accuracy   : 0.5673  | Precision : 0.5754
Recall     : 0.5673  | F1 Score  : 0.5674

[EXP02_ResNet50_ECA | fold 3] Epoch 50/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:37<00:00,  2.47it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.58it/s]

Train Loss : 0.9796 | Val Loss  : 2.2798
Accuracy   : 0.5702  | Precision : 0.5770
Recall     : 0.5702  | F1 Score  : 0.5710
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold3.pth (F1: 0.5710)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:54: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler()

  [ECA] Disisipkan ke 16 Bottleneck block (layer1-4).
  [EXP02_ResNet50_ECA] Trainable params: 23,329,863 / 23,555,207 (99.0%)

[EXP02_ResNet50_ECA | fold 4] Epoch 1/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:41<00:00,  2.41it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.64it/s]

Train Loss : 3.1992 | Val Loss  : 3.2142
Accuracy   : 0.1954  | Precision : 0.2745
Recall     : 0.1954  | F1 Score  : 0.1609
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.1609)

[EXP02_ResNet50_ECA | fold 4] Epoch 2/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:40<00:00,  2.42it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 2.9631 | Val Loss  : 2.9907
Accuracy   : 0.2453  | Precision : 0.2875
Recall     : 0.2453  | F1 Score  : 0.2139
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.2139)

[EXP02_ResNet50_ECA | fold 4] Epoch 3/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:43<00:00,  2.37it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.52it/s]

Train Loss : 2.7769 | Val Loss  : 2.8647
Accuracy   : 0.2944  | Precision : 0.3245
Recall     : 0.2944  | F1 Score  : 0.2796
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.2796)

[EXP02_ResNet50_ECA | fold 4] Epoch 4/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:30<00:00,  2.59it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:28<00:00,  3.47it/s]

Train Loss : 2.6291 | Val Loss  : 2.7725
Accuracy   : 0.3279  | Precision : 0.3691
Recall     : 0.3279  | F1 Score  : 0.3200
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.3200)

[EXP02_ResNet50_ECA | fold 4] Epoch 5/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:43<00:00,  2.38it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:28<00:00,  3.50it/s]

Train Loss : 2.5098 | Val Loss  : 2.7005
Accuracy   : 0.3497  | Precision : 0.4106
Recall     : 0.3497  | F1 Score  : 0.3490
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.3490)

[EXP02_ResNet50_ECA | fold 4] Epoch 6/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:45<00:00,  2.35it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.54it/s]

Train Loss : 2.4024 | Val Loss  : 2.6495
Accuracy   : 0.3700  | Precision : 0.4255
Recall     : 0.3700  | F1 Score  : 0.3697
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.3697)

[EXP02_ResNet50_ECA | fold 4] Epoch 7/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:41<00:00,  2.41it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.62it/s]

Train Loss : 2.3047 | Val Loss  : 2.5881
Accuracy   : 0.3941  | Precision : 0.4468
Recall     : 0.3941  | F1 Score  : 0.3954
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.3954)

[EXP02_ResNet50_ECA | fold 4] Epoch 8/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:39<00:00,  2.43it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.67it/s]

Train Loss : 2.2102 | Val Loss  : 2.5528
Accuracy   : 0.4134  | Precision : 0.4610
Recall     : 0.4134  | F1 Score  : 0.4121
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.4121)

[EXP02_ResNet50_ECA | fold 4] Epoch 9/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:39<00:00,  2.44it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.65it/s]

Train Loss : 2.1288 | Val Loss  : 2.5315
Accuracy   : 0.4301  | Precision : 0.4890
Recall     : 0.4301  | F1 Score  : 0.4323
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.4323)

[EXP02_ResNet50_ECA | fold 4] Epoch 10/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:38<00:00,  2.45it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.68it/s]

Train Loss : 2.0344 | Val Loss  : 2.4880
Accuracy   : 0.4294  | Precision : 0.4782
Recall     : 0.4294  | F1 Score  : 0.4280

[EXP02_ResNet50_ECA | fold 4] Epoch 11/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:39<00:00,  2.44it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.55it/s]

Train Loss : 1.9585 | Val Loss  : 2.4887
Accuracy   : 0.4384  | Precision : 0.4950
Recall     : 0.4384  | F1 Score  : 0.4393
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.4393)

[EXP02_ResNet50_ECA | fold 4] Epoch 12/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:42<00:00,  2.40it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.70it/s]

Train Loss : 1.8836 | Val Loss  : 2.4484
Accuracy   : 0.4558  | Precision : 0.5015
Recall     : 0.4558  | F1 Score  : 0.4591
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.4591)

[EXP02_ResNet50_ECA | fold 4] Epoch 13/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:41<00:00,  2.41it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.50it/s]

Train Loss : 1.8019 | Val Loss  : 2.4585
Accuracy   : 0.4516  | Precision : 0.5036
Recall     : 0.4516  | F1 Score  : 0.4550

[EXP02_ResNet50_ECA | fold 4] Epoch 14/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:40<00:00,  2.43it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:27<00:00,  3.59it/s]

Train Loss : 1.7407 | Val Loss  : 2.4236
Accuracy   : 0.4699  | Precision : 0.5158
Recall     : 0.4699  | F1 Score  : 0.4753
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.4753)

[EXP02_ResNet50_ECA | fold 4] Epoch 15/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:37<00:00,  2.47it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.77it/s]

Train Loss : 1.6811 | Val Loss  : 2.4121
Accuracy   : 0.4809  | Precision : 0.5233
Recall     : 0.4809  | F1 Score  : 0.4842
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.4842)

[EXP02_ResNet50_ECA | fold 4] Epoch 16/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.48it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.71it/s]

Train Loss : 1.6201 | Val Loss  : 2.3868
Accuracy   : 0.4918  | Precision : 0.5309
Recall     : 0.4918  | F1 Score  : 0.4946
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.4946)

[EXP02_ResNet50_ECA | fold 4] Epoch 17/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:39<00:00,  2.44it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 1.5627 | Val Loss  : 2.3868
Accuracy   : 0.4883  | Precision : 0.5304
Recall     : 0.4883  | F1 Score  : 0.4921

[EXP02_ResNet50_ECA | fold 4] Epoch 18/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.75it/s]

Train Loss : 1.5089 | Val Loss  : 2.3869
Accuracy   : 0.4976  | Precision : 0.5352
Recall     : 0.4976  | F1 Score  : 0.4987
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.4987)

[EXP02_ResNet50_ECA | fold 4] Epoch 19/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:25<00:00,  3.78it/s]

Train Loss : 1.4759 | Val Loss  : 2.3706
Accuracy   : 0.5040  | Precision : 0.5430
Recall     : 0.5040  | F1 Score  : 0.5089
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.5089)

[EXP02_ResNet50_ECA | fold 4] Epoch 20/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.75it/s]

Train Loss : 1.4232 | Val Loss  : 2.3901
Accuracy   : 0.5063  | Precision : 0.5484
Recall     : 0.5063  | F1 Score  : 0.5090
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.5090)

[EXP02_ResNet50_ECA | fold 4] Epoch 21/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.75it/s]

Train Loss : 1.3844 | Val Loss  : 2.3529
Accuracy   : 0.5233  | Precision : 0.5510
Recall     : 0.5233  | F1 Score  : 0.5266
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.5266)

[EXP02_ResNet50_ECA | fold 4] Epoch 22/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.3565 | Val Loss  : 2.3626
Accuracy   : 0.5175  | Precision : 0.5481
Recall     : 0.5175  | F1 Score  : 0.5204

[EXP02_ResNet50_ECA | fold 4] Epoch 23/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 1.3296 | Val Loss  : 2.3334
Accuracy   : 0.5239  | Precision : 0.5484
Recall     : 0.5239  | F1 Score  : 0.5276
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.5276)

[EXP02_ResNet50_ECA | fold 4] Epoch 24/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.2870 | Val Loss  : 2.3541
Accuracy   : 0.5265  | Precision : 0.5496
Recall     : 0.5265  | F1 Score  : 0.5285
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.5285)

[EXP02_ResNet50_ECA | fold 4] Epoch 25/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 1.2643 | Val Loss  : 2.3223
Accuracy   : 0.5368  | Precision : 0.5599
Recall     : 0.5368  | F1 Score  : 0.5386
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.5386)

[EXP02_ResNet50_ECA | fold 4] Epoch 26/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.75it/s]

Train Loss : 1.2393 | Val Loss  : 2.3645
Accuracy   : 0.5297  | Precision : 0.5595
Recall     : 0.5297  | F1 Score  : 0.5333

[EXP02_ResNet50_ECA | fold 4] Epoch 27/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 1.2155 | Val Loss  : 2.3236
Accuracy   : 0.5391  | Precision : 0.5572
Recall     : 0.5391  | F1 Score  : 0.5420
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.5420)

[EXP02_ResNet50_ECA | fold 4] Epoch 28/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.1902 | Val Loss  : 2.3055
Accuracy   : 0.5509  | Precision : 0.5676
Recall     : 0.5509  | F1 Score  : 0.5542
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.5542)

[EXP02_ResNet50_ECA | fold 4] Epoch 29/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.48it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.75it/s]

Train Loss : 1.1790 | Val Loss  : 2.3358
Accuracy   : 0.5439  | Precision : 0.5653
Recall     : 0.5439  | F1 Score  : 0.5472

[EXP02_ResNet50_ECA | fold 4] Epoch 30/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 1.1552 | Val Loss  : 2.3465
Accuracy   : 0.5397  | Precision : 0.5612
Recall     : 0.5397  | F1 Score  : 0.5433

[EXP02_ResNet50_ECA | fold 4] Epoch 31/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 1.1369 | Val Loss  : 2.3559
Accuracy   : 0.5410  | Precision : 0.5608
Recall     : 0.5410  | F1 Score  : 0.5426

[EXP02_ResNet50_ECA | fold 4] Epoch 32/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 1.1057 | Val Loss  : 2.3268
Accuracy   : 0.5458  | Precision : 0.5617
Recall     : 0.5458  | F1 Score  : 0.5478

[EXP02_ResNet50_ECA | fold 4] Epoch 33/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 1.0980 | Val Loss  : 2.3283
Accuracy   : 0.5452  | Precision : 0.5607
Recall     : 0.5452  | F1 Score  : 0.5475

[EXP02_ResNet50_ECA | fold 4] Epoch 34/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 1.0890 | Val Loss  : 2.3205
Accuracy   : 0.5526  | Precision : 0.5697
Recall     : 0.5526  | F1 Score  : 0.5550
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.5550)

[EXP02_ResNet50_ECA | fold 4] Epoch 35/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.49it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:25<00:00,  3.83it/s]

Train Loss : 1.0863 | Val Loss  : 2.3256
Accuracy   : 0.5487  | Precision : 0.5640
Recall     : 0.5487  | F1 Score  : 0.5512

[EXP02_ResNet50_ECA | fold 4] Epoch 36/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:25<00:00,  3.77it/s]

Train Loss : 1.0792 | Val Loss  : 2.3278
Accuracy   : 0.5522  | Precision : 0.5721
Recall     : 0.5522  | F1 Score  : 0.5565
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.5565)

[EXP02_ResNet50_ECA | fold 4] Epoch 37/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.75it/s]

Train Loss : 1.0795 | Val Loss  : 2.3191
Accuracy   : 0.5542  | Precision : 0.5710
Recall     : 0.5542  | F1 Score  : 0.5569
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.5569)

[EXP02_ResNet50_ECA | fold 4] Epoch 38/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.49it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:25<00:00,  3.77it/s]

Train Loss : 1.0778 | Val Loss  : 2.3190
Accuracy   : 0.5548  | Precision : 0.5697
Recall     : 0.5548  | F1 Score  : 0.5572
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.5572)

[EXP02_ResNet50_ECA | fold 4] Epoch 39/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.48it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 1.0763 | Val Loss  : 2.3237
Accuracy   : 0.5500  | Precision : 0.5657
Recall     : 0.5500  | F1 Score  : 0.5520

[EXP02_ResNet50_ECA | fold 4] Epoch 40/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 1.0781 | Val Loss  : 2.3136
Accuracy   : 0.5529  | Precision : 0.5667
Recall     : 0.5529  | F1 Score  : 0.5547

[EXP02_ResNet50_ECA | fold 4] Epoch 41/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 1.0698 | Val Loss  : 2.2992
Accuracy   : 0.5561  | Precision : 0.5668
Recall     : 0.5561  | F1 Score  : 0.5573
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.5573)

[EXP02_ResNet50_ECA | fold 4] Epoch 42/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.77it/s]

Train Loss : 1.0702 | Val Loss  : 2.3110
Accuracy   : 0.5606  | Precision : 0.5751
Recall     : 0.5606  | F1 Score  : 0.5634
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold4.pth (F1: 0.5634)

[EXP02_ResNet50_ECA | fold 4] Epoch 43/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 1.0684 | Val Loss  : 2.3051
Accuracy   : 0.5522  | Precision : 0.5673
Recall     : 0.5522  | F1 Score  : 0.5545

[EXP02_ResNet50_ECA | fold 4] Epoch 44/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.0622 | Val Loss  : 2.3073
Accuracy   : 0.5532  | Precision : 0.5688
Recall     : 0.5532  | F1 Score  : 0.5562

[EXP02_ResNet50_ECA | fold 4] Epoch 45/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 1.0635 | Val Loss  : 2.3057
Accuracy   : 0.5487  | Precision : 0.5637
Recall     : 0.5487  | F1 Score  : 0.5518

[EXP02_ResNet50_ECA | fold 4] Epoch 46/50 (LR: 1.00e-06)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 1.0645 | Val Loss  : 2.3050
Accuracy   : 0.5558  | Precision : 0.5674
Recall     : 0.5558  | F1 Score  : 0.5568

[EXP02_ResNet50_ECA | fold 4] Epoch 47/50 (LR: 1.00e-06)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.0534 | Val Loss  : 2.3046
Accuracy   : 0.5532  | Precision : 0.5697
Recall     : 0.5532  | F1 Score  : 0.5557

[EXP02_ResNet50_ECA | fold 4] Epoch 48/50 (LR: 1.00e-06)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.75it/s]

Train Loss : 1.0585 | Val Loss  : 2.3038
Accuracy   : 0.5564  | Precision : 0.5720
Recall     : 0.5564  | F1 Score  : 0.5590

[EXP02_ResNet50_ECA | fold 4] Epoch 49/50 (LR: 1.00e-07)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 1.0603 | Val Loss  : 2.2953
Accuracy   : 0.5561  | Precision : 0.5686
Recall     : 0.5561  | F1 Score  : 0.5570
Early Stopping Triggered

C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:54: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler()

  [ECA] Disisipkan ke 16 Bottleneck block (layer1-4).
  [EXP02_ResNet50_ECA] Trainable params: 23,329,863 / 23,555,207 (99.0%)

[EXP02_ResNet50_ECA | fold 5] Epoch 1/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.75it/s]

Train Loss : 3.1765 | Val Loss  : 3.1803
Accuracy   : 0.2025  | Precision : 0.2672
Recall     : 0.2025  | F1 Score  : 0.1782
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.1782)

[EXP02_ResNet50_ECA | fold 5] Epoch 2/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.76it/s]

Train Loss : 2.9329 | Val Loss  : 2.9932
Accuracy   : 0.2414  | Precision : 0.3011
Recall     : 0.2414  | F1 Score  : 0.2277
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.2277)

[EXP02_ResNet50_ECA | fold 5] Epoch 3/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.69it/s]

Train Loss : 2.7445 | Val Loss  : 2.8656
Accuracy   : 0.2973  | Precision : 0.3499
Recall     : 0.2973  | F1 Score  : 0.2916
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.2916)

[EXP02_ResNet50_ECA | fold 5] Epoch 4/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 2.6112 | Val Loss  : 2.7953
Accuracy   : 0.3250  | Precision : 0.3870
Recall     : 0.3250  | F1 Score  : 0.3180
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.3180)

[EXP02_ResNet50_ECA | fold 5] Epoch 5/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.75it/s]

Train Loss : 2.4908 | Val Loss  : 2.7208
Accuracy   : 0.3607  | Precision : 0.4200
Recall     : 0.3607  | F1 Score  : 0.3606
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.3606)

[EXP02_ResNet50_ECA | fold 5] Epoch 6/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.49it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.76it/s]

Train Loss : 2.3984 | Val Loss  : 2.6625
Accuracy   : 0.3770  | Precision : 0.4301
Recall     : 0.3770  | F1 Score  : 0.3771
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.3771)

[EXP02_ResNet50_ECA | fold 5] Epoch 7/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.71it/s]

Train Loss : 2.3097 | Val Loss  : 2.6522
Accuracy   : 0.3806  | Precision : 0.4635
Recall     : 0.3806  | F1 Score  : 0.3868
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.3868)

[EXP02_ResNet50_ECA | fold 5] Epoch 8/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 2.2191 | Val Loss  : 2.5829
Accuracy   : 0.3973  | Precision : 0.4562
Recall     : 0.3973  | F1 Score  : 0.4019
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.4019)

[EXP02_ResNet50_ECA | fold 5] Epoch 9/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 2.1383 | Val Loss  : 2.5552
Accuracy   : 0.4153  | Precision : 0.4837
Recall     : 0.4153  | F1 Score  : 0.4183
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.4183)

[EXP02_ResNet50_ECA | fold 5] Epoch 10/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 2.0633 | Val Loss  : 2.5221
Accuracy   : 0.4217  | Precision : 0.4828
Recall     : 0.4217  | F1 Score  : 0.4282
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.4282)

[EXP02_ResNet50_ECA | fold 5] Epoch 11/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 1.9857 | Val Loss  : 2.5226
Accuracy   : 0.4330  | Precision : 0.5019
Recall     : 0.4330  | F1 Score  : 0.4372
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.4372)

[EXP02_ResNet50_ECA | fold 5] Epoch 12/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 1.9337 | Val Loss  : 2.4934
Accuracy   : 0.4452  | Precision : 0.5092
Recall     : 0.4452  | F1 Score  : 0.4494
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.4494)

[EXP02_ResNet50_ECA | fold 5] Epoch 13/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.75it/s]

Train Loss : 1.8450 | Val Loss  : 2.4844
Accuracy   : 0.4503  | Precision : 0.5095
Recall     : 0.4503  | F1 Score  : 0.4558
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.4558)

[EXP02_ResNet50_ECA | fold 5] Epoch 14/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 1.7785 | Val Loss  : 2.4579
Accuracy   : 0.4603  | Precision : 0.5228
Recall     : 0.4603  | F1 Score  : 0.4694
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.4694)

[EXP02_ResNet50_ECA | fold 5] Epoch 15/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.75it/s]

Train Loss : 1.7235 | Val Loss  : 2.4443
Accuracy   : 0.4732  | Precision : 0.5186
Recall     : 0.4732  | F1 Score  : 0.4770
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.4770)

[EXP02_ResNet50_ECA | fold 5] Epoch 16/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.6711 | Val Loss  : 2.4083
Accuracy   : 0.4873  | Precision : 0.5371
Recall     : 0.4873  | F1 Score  : 0.4935
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.4935)

[EXP02_ResNet50_ECA | fold 5] Epoch 17/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.71it/s]

Train Loss : 1.6117 | Val Loss  : 2.3887
Accuracy   : 0.4876  | Precision : 0.5228
Recall     : 0.4876  | F1 Score  : 0.4913

[EXP02_ResNet50_ECA | fold 5] Epoch 18/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 1.5524 | Val Loss  : 2.3940
Accuracy   : 0.4924  | Precision : 0.5286
Recall     : 0.4924  | F1 Score  : 0.4956
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.4956)

[EXP02_ResNet50_ECA | fold 5] Epoch 19/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.71it/s]

Train Loss : 1.5101 | Val Loss  : 2.4271
Accuracy   : 0.4986  | Precision : 0.5406
Recall     : 0.4986  | F1 Score  : 0.5009
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.5009)

[EXP02_ResNet50_ECA | fold 5] Epoch 20/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.71it/s]

Train Loss : 1.4536 | Val Loss  : 2.3867
Accuracy   : 0.5088  | Precision : 0.5461
Recall     : 0.5088  | F1 Score  : 0.5142
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.5142)

[EXP02_ResNet50_ECA | fold 5] Epoch 21/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 1.4228 | Val Loss  : 2.3842
Accuracy   : 0.5069  | Precision : 0.5484
Recall     : 0.5069  | F1 Score  : 0.5122

[EXP02_ResNet50_ECA | fold 5] Epoch 22/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 1.3783 | Val Loss  : 2.3716
Accuracy   : 0.5198  | Precision : 0.5546
Recall     : 0.5198  | F1 Score  : 0.5255
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.5255)

[EXP02_ResNet50_ECA | fold 5] Epoch 23/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.75it/s]

Train Loss : 1.3517 | Val Loss  : 2.3720
Accuracy   : 0.5291  | Precision : 0.5585
Recall     : 0.5291  | F1 Score  : 0.5339
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.5339)

[EXP02_ResNet50_ECA | fold 5] Epoch 24/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.70it/s]

Train Loss : 1.3199 | Val Loss  : 2.3567
Accuracy   : 0.5239  | Precision : 0.5552
Recall     : 0.5239  | F1 Score  : 0.5280

[EXP02_ResNet50_ECA | fold 5] Epoch 25/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.2751 | Val Loss  : 2.3495
Accuracy   : 0.5381  | Precision : 0.5616
Recall     : 0.5381  | F1 Score  : 0.5416
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.5416)

[EXP02_ResNet50_ECA | fold 5] Epoch 26/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.48it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.75it/s]

Train Loss : 1.2511 | Val Loss  : 2.3249
Accuracy   : 0.5439  | Precision : 0.5633
Recall     : 0.5439  | F1 Score  : 0.5465
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.5465)

[EXP02_ResNet50_ECA | fold 5] Epoch 27/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 1.2325 | Val Loss  : 2.3582
Accuracy   : 0.5410  | Precision : 0.5688
Recall     : 0.5410  | F1 Score  : 0.5446

[EXP02_ResNet50_ECA | fold 5] Epoch 28/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.2069 | Val Loss  : 2.3568
Accuracy   : 0.5397  | Precision : 0.5733
Recall     : 0.5397  | F1 Score  : 0.5455

[EXP02_ResNet50_ECA | fold 5] Epoch 29/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 1.1870 | Val Loss  : 2.3508
Accuracy   : 0.5426  | Precision : 0.5693
Recall     : 0.5426  | F1 Score  : 0.5469
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.5469)

[EXP02_ResNet50_ECA | fold 5] Epoch 30/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 1.1695 | Val Loss  : 2.3268
Accuracy   : 0.5439  | Precision : 0.5623
Recall     : 0.5439  | F1 Score  : 0.5461

[EXP02_ResNet50_ECA | fold 5] Epoch 31/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 1.1507 | Val Loss  : 2.3288
Accuracy   : 0.5432  | Precision : 0.5656
Recall     : 0.5432  | F1 Score  : 0.5469
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.5469)

[EXP02_ResNet50_ECA | fold 5] Epoch 32/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.69it/s]

Train Loss : 1.1309 | Val Loss  : 2.3159
Accuracy   : 0.5535  | Precision : 0.5730
Recall     : 0.5535  | F1 Score  : 0.5580
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.5580)

[EXP02_ResNet50_ECA | fold 5] Epoch 33/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 1.1088 | Val Loss  : 2.3012
Accuracy   : 0.5561  | Precision : 0.5708
Recall     : 0.5561  | F1 Score  : 0.5589
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.5589)

[EXP02_ResNet50_ECA | fold 5] Epoch 34/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 1.1034 | Val Loss  : 2.2866
Accuracy   : 0.5574  | Precision : 0.5688
Recall     : 0.5574  | F1 Score  : 0.5595
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.5595)

[EXP02_ResNet50_ECA | fold 5] Epoch 35/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.71it/s]

Train Loss : 1.0895 | Val Loss  : 2.3288
Accuracy   : 0.5558  | Precision : 0.5795
Recall     : 0.5558  | F1 Score  : 0.5590

[EXP02_ResNet50_ECA | fold 5] Epoch 36/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.49it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.76it/s]

Train Loss : 1.0727 | Val Loss  : 2.2940
Accuracy   : 0.5654  | Precision : 0.5744
Recall     : 0.5654  | F1 Score  : 0.5666
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.5666)

[EXP02_ResNet50_ECA | fold 5] Epoch 37/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 1.0569 | Val Loss  : 2.3103
Accuracy   : 0.5648  | Precision : 0.5787
Recall     : 0.5648  | F1 Score  : 0.5663

[EXP02_ResNet50_ECA | fold 5] Epoch 38/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 1.0537 | Val Loss  : 2.2940
Accuracy   : 0.5612  | Precision : 0.5761
Recall     : 0.5612  | F1 Score  : 0.5641

[EXP02_ResNet50_ECA | fold 5] Epoch 39/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.0383 | Val Loss  : 2.2779
Accuracy   : 0.5728  | Precision : 0.5876
Recall     : 0.5728  | F1 Score  : 0.5751
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.5751)

[EXP02_ResNet50_ECA | fold 5] Epoch 40/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.49it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.75it/s]

Train Loss : 1.0294 | Val Loss  : 2.2632
Accuracy   : 0.5818  | Precision : 0.5955
Recall     : 0.5818  | F1 Score  : 0.5850
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.5850)

[EXP02_ResNet50_ECA | fold 5] Epoch 41/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 1.0183 | Val Loss  : 2.2836
Accuracy   : 0.5725  | Precision : 0.5859
Recall     : 0.5725  | F1 Score  : 0.5732

[EXP02_ResNet50_ECA | fold 5] Epoch 42/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 1.0170 | Val Loss  : 2.2696
Accuracy   : 0.5709  | Precision : 0.5824
Recall     : 0.5709  | F1 Score  : 0.5727

[EXP02_ResNet50_ECA | fold 5] Epoch 43/50 (LR: 1.00e-04)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.74it/s]

Train Loss : 1.0130 | Val Loss  : 2.2461
Accuracy   : 0.5831  | Precision : 0.5934
Recall     : 0.5831  | F1 Score  : 0.5841

[EXP02_ResNet50_ECA | fold 5] Epoch 44/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 0.9894 | Val Loss  : 2.2377
Accuracy   : 0.5844  | Precision : 0.5944
Recall     : 0.5844  | F1 Score  : 0.5860
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.5860)

[EXP02_ResNet50_ECA | fold 5] Epoch 45/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.49it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.76it/s]

Train Loss : 0.9866 | Val Loss  : 2.2347
Accuracy   : 0.5799  | Precision : 0.5910
Recall     : 0.5799  | F1 Score  : 0.5814

[EXP02_ResNet50_ECA | fold 5] Epoch 46/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:36<00:00,  2.49it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.75it/s]

Train Loss : 0.9821 | Val Loss  : 2.2454
Accuracy   : 0.5760  | Precision : 0.5879
Recall     : 0.5760  | F1 Score  : 0.5776

[EXP02_ResNet50_ECA | fold 5] Epoch 47/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 0.9787 | Val Loss  : 2.2371
Accuracy   : 0.5850  | Precision : 0.5949
Recall     : 0.5850  | F1 Score  : 0.5867
  ✓ Model saved → outputs/EXP02_ResNet50_ECA_fold5.pth (F1: 0.5867)

[EXP02_ResNet50_ECA | fold 5] Epoch 48/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 0.9734 | Val Loss  : 2.2264
Accuracy   : 0.5818  | Precision : 0.5927
Recall     : 0.5818  | F1 Score  : 0.5834

[EXP02_ResNet50_ECA | fold 5] Epoch 49/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.73it/s]

Train Loss : 0.9712 | Val Loss  : 2.2222
Accuracy   : 0.5834  | Precision : 0.5923
Recall     : 0.5834  | F1 Score  : 0.5841

[EXP02_ResNet50_ECA | fold 5] Epoch 50/50 (LR: 1.00e-05)

Train:   0%|          | 0/389 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:78: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Train: 100%|██████████| 389/389 [02:35<00:00,  2.50it/s]
Val:   0%|          | 0/98 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3272042763.py:92: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Val: 100%|██████████| 98/98 [00:26<00:00,  3.72it/s]

Train Loss : 0.9711 | Val Loss  : 2.2246
Accuracy   : 0.5834  | Precision : 0.5930
Recall     : 0.5834  | F1 Score  : 0.5847

,arch,fold,train_loss,val_loss,accuracy,precision,recall,f1,model_path
0,EXP02_ResNet50_ECA,1,1.155485,2.302210,0.543702,0.554148,0.543702,0.544915,outputs/EXP02_ResNet50_ECA_fold1.pth
1,EXP02_ResNet50_ECA,2,0.958918,2.321102,0.574229,0.585339,0.574229,0.576488,outputs/EXP02_ResNet50_ECA_fold2.pth
2,EXP02_ResNet50_ECA,3,0.979588,2.279820,0.570235,0.576991,0.570235,0.571012,outputs/EXP02_ResNet50_ECA_fold3.pth
3,EXP02_ResNet50_ECA,4,1.070162,2.310969,0.560591,0.575115,0.560591,0.563365,outputs/EXP02_ResNet50_ECA_fold4.pth
4,EXP02_ResNet50_ECA,5,0.978695,2.237113,0.585021,0.594943,0.585021,0.586707,outputs/EXP02_ResNet50_ECA_fold5.pth

## 8. Rekap 5-Fold

In [9]:
# PERBAIKAN: format summary disamakan persis dengan ViT exp01 -- laporkan
# Mean ± Std untuk keempat metrik (Accuracy, Precision, Recall, F1), bukan
# cuma F1 saja.
print("\n" + "="*50)
print(f"  FINAL RESULT — ALL FOLDS ({ARCH_KEY})")
print("="*50)
print(f"Mean Accuracy  : {results_df['accuracy'].mean():.4f} ± {results_df['accuracy'].std():.4f}")
print(f"Mean Precision : {results_df['precision'].mean():.4f} ± {results_df['precision'].std():.4f}")
print(f"Mean Recall    : {results_df['recall'].mean():.4f} ± {results_df['recall'].std():.4f}")
print(f"Mean F1 Score  : {results_df['f1'].mean():.4f} ± {results_df['f1'].std():.4f}")

# ── WANDB LOG SUMMARY (format sama seperti ViT exp01) ─────────────────────────
try:
    run.log({
        "summary/mean_accuracy"  : results_df["accuracy"].mean(),
        "summary/mean_precision" : results_df["precision"].mean(),
        "summary/mean_recall"    : results_df["recall"].mean(),
        "summary/mean_f1"        : results_df["f1"].mean(),
        "summary/std_accuracy"   : results_df["accuracy"].std(),
        "summary/std_precision"  : results_df["precision"].std(),
        "summary/std_recall"     : results_df["recall"].std(),
        "summary/std_f1"         : results_df["f1"].std(),
    })
except Exception as e:
    print(f"  ⚠ W&B log summary gagal (dilewati): {e}")

# ── GRAFIK: 4 metrik per fold (bukan cuma F1) ──────────────────────────────────
fig, axes = plt.subplots(1, 4, figsize=(20, 4))
metric_cols = ["accuracy", "precision", "recall", "f1"]
metric_titles = ["Accuracy", "Precision", "Recall", "F1-Score"]

for ax, col, title in zip(axes, metric_cols, metric_titles):
    ax.bar(results_df["fold"].astype(str), results_df[col], color="#1f3a5f")
    ax.axhline(results_df[col].mean(), color="red", linestyle="--", label=f"Mean = {results_df[col].mean():.3f}")
    ax.set_xlabel("Fold"); ax.set_ylabel(f"Val {title}")
    ax.set_title(f"{ARCH_KEY} — {title} per Fold")
    ax.set_ylim(0, 1); ax.legend()

plt.tight_layout()
plt.savefig(f"{OUTPUT_DIR}/{ARCH_KEY}_fold_metrics_chart.png", dpi=200)
plt.show()

results_df.to_csv(f"{OUTPUT_DIR}/{ARCH_KEY}_all_folds.csv", index=False)

==================================================
  FINAL RESULT — ALL FOLDS (EXP02_ResNet50_ECA)
==================================================
Mean Accuracy  : 0.5668 ± 0.0156
Mean Precision : 0.5773 ± 0.0151
Mean Recall    : 0.5668 ± 0.0156
Mean F1 Score  : 0.5685 ± 0.0157
  ⚠ W&B log summary gagal (dilewati): Run (yo9eodcr) is finished. The call to `log` will be ignored. Please make sure that you are using an active run.

C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\1248490208.py:41: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## 9. Test Evaluation (Fold Terbaik)

In [10]:
best_fold_result = max(all_results, key=lambda r: r["f1"])
best_overall_path = best_fold_result["model_path"]
print(f"Fold terbaik    : {best_fold_result['fold']}")
print(f"Checkpoint      : {best_overall_path}")
print(f"Val F1 terbaik  : {best_fold_result['f1']:.4f}")

_, eval_tf = get_transforms(IMG_SIZE)
test_dataset = datasets.ImageFolder(TEST_DIR, transform=eval_tf)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

model = build_model(num_classes)
model = model.to(device)
checkpoint = torch.load(best_overall_path, map_location=device)
model.load_state_dict(checkpoint["model_state_dict"])
model.eval()

y_true, y_pred = [], []
with torch.no_grad():
    for imgs, tgts in tqdm(test_loader, desc="Test"):
        imgs = imgs.to(device)
        with autocast():
            out = model(imgs)
        y_true.extend(tgts.numpy())
        y_pred.extend(out.argmax(1).cpu().numpy())

acc = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average="weighted", zero_division=0)
recall = recall_score(y_true, y_pred, average="weighted", zero_division=0)
f1 = f1_score(y_true, y_pred, average="weighted", zero_division=0)

print(f"Accuracy  : {acc:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1-Score  : {f1:.4f}")
print()
print(classification_report(y_true, y_pred, target_names=classes, zero_division=0))

cm = confusion_matrix(y_true, y_pred)
fig, ax = plt.subplots(figsize=(15, 15))
ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=classes).plot(cmap="Blues", ax=ax, xticks_rotation=90)
plt.tight_layout()
plt.savefig(f"{OUTPUT_DIR}/{ARCH_KEY}_Test_Confusion_Matrix.png", dpi=150, bbox_inches="tight")
plt.show()

test_summary_df = pd.DataFrame([{
    "arch": ARCH_KEY, "Accuracy": acc, "Precision": precision, "Recall": recall, "F1": f1
}])
test_summary_df.to_csv(f"{OUTPUT_DIR}/{ARCH_KEY}_Test_Summary.csv", index=False)
print(f"\n✓ Test summary disimpan -> {OUTPUT_DIR}/{ARCH_KEY}_Test_Summary.csv")

Fold terbaik    : 5
Checkpoint      : outputs/EXP02_ResNet50_ECA_fold5.pth
Val F1 terbaik  : 0.5867
  [ECA] Disisipkan ke 16 Bottleneck block (layer1-4).

Test:   0%|          | 0/126 [00:00<?, ?it/s]C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3000596476.py:21: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Test: 100%|██████████| 126/126 [00:46<00:00,  2.69it/s]

Accuracy  : 0.5940
Precision : 0.6040
Recall    : 0.5940
F1-Score  : 0.5937

                                                                    precision    recall  f1-score   support

                                           Acne and Rosacea Photos       0.76      0.91      0.83       312
Actinic Keratosis Basal Cell Carcinoma and other Malignant Lesions       0.67      0.62      0.65       288
                                          Atopic Dermatitis Photos       0.47      0.65      0.54       123
                                            Bullous Disease Photos       0.57      0.46      0.51       113
                Cellulitis Impetigo and other Bacterial Infections       0.32      0.37      0.34        73
                                                     Eczema Photos       0.63      0.52      0.57       309
                                      Exanthems and Drug Eruptions       0.46      0.58      0.52       101
                 Hair Loss Photos Alopecia and other Hair Diseases       0.39      0.78      0.52        60
                                  Herpes HPV and other STDs Photos       0.45      0.53      0.48       102
                      Light Diseases and Disorders of Pigmentation       0.47      0.46      0.46       143
                        Lupus and other Connective Tissue diseases       0.62      0.43      0.51       105
                               Melanoma Skin Cancer Nevi and Moles       0.67      0.74      0.70       116
                                Nail Fungus and other Nail Disease       0.83      0.76      0.79       261
                    Poison Ivy Photos and other Contact Dermatitis       0.35      0.65      0.45        65
             Psoriasis pictures Lichen Planus and related diseases       0.59      0.50      0.54       352
             Scabies Lyme Disease and other Infestations and Bites       0.46      0.44      0.45       108
                      Seborrheic Keratoses and other Benign Tumors       0.63      0.58      0.61       343
                                                  Systemic Disease       0.55      0.43      0.48       152
            Tinea Ringworm Candidiasis and other Fungal Infections       0.67      0.58      0.62       325
                                                   Urticaria Hives       0.59      0.68      0.63        53
                                                   Vascular Tumors       0.57      0.58      0.58       121
                                                 Vasculitis Photos       0.56      0.57      0.56       105
                        Warts Molluscum and other Viral Infections       0.56      0.56      0.56       272

                                                          accuracy                           0.59      4002
                                                         macro avg       0.56      0.58      0.56      4002
                                                      weighted avg       0.60      0.59      0.59      4002


✓ Test summary disimpan -> outputs/EXP02_ResNet50_ECA_Test_Summary.csv

C:\Users\UNIDA\AppData\Local\Temp\ipykernel_2292\3000596476.py:43: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## 9b. Per-Image Test Prediction (True/False per gambar)

Dump terpisah dari summary agregat di atas -- CSV ini berisi 1 baris per gambar test (filepath, label asli, label prediksi, benar/salah), supaya bisa dicek manual gambar mana saja yang salah diklasifikasikan (misal untuk lampiran/analisis kualitatif di skripsi).

In [11]:
# PERBAIKAN: dump prediksi per-gambar (bukan cuma summary agregat) -- pakai
# y_true/y_pred/test_dataset yang sudah dihitung di cell sebelumnya (state Jupyter
# masih ada, tidak perlu re-run inference).
test_filepaths = [fp for fp, _ in test_dataset.samples]   # urutan sama dgn y_true/y_pred (shuffle=False)
assert len(test_filepaths) == len(y_true) == len(y_pred), "Jumlah filepath tidak sama dengan jumlah prediksi!"

per_image_df = pd.DataFrame({
    "filepath": test_filepaths,
    "true_label": [classes[t] for t in y_true],
    "pred_label": [classes[p] for p in y_pred],
    "correct": [t == p for t, p in zip(y_true, y_pred)],
})

per_image_csv_path = f"{OUTPUT_DIR}/{ARCH_KEY}_Test_PerImage_Predictions.csv"
per_image_df.to_csv(per_image_csv_path, index=False)

n_correct = int(per_image_df["correct"].sum())
n_total = len(per_image_df)
print(f"✓ Per-image prediction disimpan -> {per_image_csv_path}")
print(f"  Benar : {n_correct} / {n_total} ({100 * n_correct / n_total:.2f}%)")
print(f"  Salah : {n_total - n_correct} / {n_total} ({100 * (n_total - n_correct) / n_total:.2f}%)")

# Preview baris yang salah -- 10 contoh pertama, berguna buat dicek manual
per_image_df[~per_image_df["correct"]].head(10)

✓ Per-image prediction disimpan -> outputs/EXP02_ResNet50_ECA_Test_PerImage_Predictions.csv
  Benar : 2377 / 4002 (59.40%)
  Salah : 1625 / 4002 (40.60%)

,filepath,true_label,pred_label,correct
14,D:\Devianest_SkripsiTest\test\Acne and Rosacea...,Acne and Rosacea Photos,Systemic Disease,False
54,D:\Devianest_SkripsiTest\test\Acne and Rosacea...,Acne and Rosacea Photos,Warts Molluscum and other Viral Infections,False
73,D:\Devianest_SkripsiTest\test\Acne and Rosacea...,Acne and Rosacea Photos,Vascular Tumors,False
74,D:\Devianest_SkripsiTest\test\Acne and Rosacea...,Acne and Rosacea Photos,Exanthems and Drug Eruptions,False
80,D:\Devianest_SkripsiTest\test\Acne and Rosacea...,Acne and Rosacea Photos,Systemic Disease,False
90,D:\Devianest_SkripsiTest\test\Acne and Rosacea...,Acne and Rosacea Photos,Atopic Dermatitis Photos,False
146,D:\Devianest_SkripsiTest\test\Acne and Rosacea...,Acne and Rosacea Photos,Vascular Tumors,False
159,D:\Devianest_SkripsiTest\test\Acne and Rosacea...,Acne and Rosacea Photos,Warts Molluscum and other Viral Infections,False
162,D:\Devianest_SkripsiTest\test\Acne and Rosacea...,Acne and Rosacea Photos,Hair Loss Photos Alopecia and other Hair Diseases,False
167,D:\Devianest_SkripsiTest\test\Acne and Rosacea...,Acne and Rosacea Photos,Seborrheic Keratoses and other Benign Tumors,False

## Catatan

- **Isolasi variabel**: satu-satunya perbedaan dari `exp01-cnn-baseline.ipynb` adalah `USE_ECA=True` + penyisipan `ECAAttention` di tiap Bottleneck (`layer1-4`). Semua hyperparameter lain (LR, WEIGHT_DECAY, DROPOUT, UNFREEZE_PATTERNS, scheduler, augmentasi, seed) identik -- supaya selisih F1 vs EXP01 bisa diatribusikan murni ke ECA.
- **Titik insersi**: slot `.se` bawaan timm Bottleneck (dipanggil setelah `conv3+bn3`, sebelum residual add) -- bukan hack, ini memang disediakan timm untuk attention module CNN-native (SE-Net dkk), jadi tidak perlu re-write forward pass ResNet secara manual.
- **ECA selalu trainable**: meskipun `layer1` di luar `UNFREEZE_PATTERNS` (backbone-nya beku), modul ECA di `layer1` tetap dilatih -- karena bobotnya random-init, bukan pretrained. Ini prinsip yang sama dengan attention submodule di exp02 ViT ECA (selalu unfrozen).
- **Checkpoint & test evaluation**: karena `build_model()` sudah otomatis memanggil `inject_eca()` saat `USE_ECA=True`, sel Test Evaluation (§9) TIDAK perlu perubahan apa pun -- `build_model(num_classes)` di situ akan otomatis merekonstruksi arsitektur ber-ECA sebelum `load_state_dict`, jadi key-nya pasti cocok dengan checkpoint hasil training.
- Checkpoint format & kolom `results_df` tetap sama seperti EXP01 -- tinggal `pd.concat()` untuk rekap akhir baseline vs ECA.